- prow_config.yaml
* This allows the prow jobs to run.
/assign @gaocegege
> Create a prow_config file with an empty list of workflows.

- content/docs/started/getting-started-gke.md
Fixed a few typos and formatting issues in the Kubeflow GKE instructions. Also added some missing steps during credentials creation.
> Fixing some typos and formatting on the GKE instructions page

- content/_redirects
Fix kubeflow/kubeflow#1156
After this PR you could something like
```
curl -L https://kubeflow.org/version/stable/gke/scripts/deploy.sh | bash
```
We can then update the version that stable points to as part of our release process.
> Add redirects to GitHub content.

- content/docs/started/pytorch.md
> Moved pytorch doc from 'About' to 'Getting Started' - issue #82

- content/docs/started/getting-started.md
Fixes #117 
The user guide  was broken into smaller topic pages and added into a Guides section. Updating all links to it.
> Update broken links to user_guide.

- content/docs/guides/components/tftraining.md
* Move over the documentation in kubeflow/tf-operator/README.md and
update it for v1alpha2.
* Add a what is TFJob section that describes the TFJob
* Provide information about the spec
* Provide information about exit codes.
* Provide stackdriver sections for both the legacy and new Kubernetes
stackdriver.
* Add a troubleshooting section.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/107)
> Update TFJob docs with information about monitoring.

- content/docs/started/getting-started-gke.md
* Add troubleshooting instructions for 404's on central dashboard.
* Add gcloud/kubectl commands for getting backend health status
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/126)
> Improve troubleshooting instructions for GKE.

- content/docs/guides/components/jupyter.md
Fixes: https://github.com/kubeflow/website/issues/171
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/187)
> NAMESPACE is set in Jupyter guide

- content/docs/started/getting-started-minikube.md
The current instructions on the website are already out-of-date as we noticed recently. Updating to reflect current valid procedure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/198)
> Updating instructions for installing KVM2 on Ubuntu & CentOS

- config.toml
- content/docs/about/community.md
- content/docs/about/contributing.md
- content/docs/about/events.md
- content/docs/about/kubeflow.md
- themes/kf/layouts/index.html
Fixes #185 which requests that we make it easier to find community resources on the website:
* Adds a **Contribute** button to the front page of the site, linking to the contributor's guide.
* Adds a section in the contributor's guide about the community page.
* Moves the community page higher in the list of "about" pages.
* Updates the info on the community page.
* Adds a section on the Kubeflow page about the community and contributor's guides.
* Makes various small improvements to the contributor's guide.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/203)
> Various updates to emphasize community resources

- config.toml
- content/docs/guides/gke/cloud-filestore.md
- content/docs/guides/gke/custom-domain.md
- content/docs/guides/gke/customizing-gke.md
- content/docs/guides/gke/private-clusters.md
- content/docs/guides/gke/troubleshooting-gke.md
- content/docs/started/getting-started-gke.md
Shortens the GKE getting-started guide by splitting out the info on customizations and troubleshooting into a new section of the guides. This also makes the info easier to find and gives us a good place to put more GKE-specific guides when they arrive, such as the GKE end-to-end guide that's currently in progress.
Fixes issue #227
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/228)
> Refactors the GKE getting-started guide

- content/docs/guides/components/tftraining.md
- content/docs/guides/job-scheduling.md
This PR add the tutorial of  job scheduling with kube-arbitrator and gang-scheduling into guides.
Fixed the issue: [kubeflow/tf-operator#743](https://github.com/kubeflow/tf-operator/issues/743)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/241)
> add job scheduling section into guides

- content/docs/guides/job-scheduling.md
According to the discussion in [kubernetes/org#112](https://github.com/kubernetes/org/issues/112), we changed the name from kube-arbitrator to kube-batch. So this PR update the doc to keep consistency.
Fix the issue [kubeflow/tf-operator#837](https://github.com/kubeflow/tf-operator/issues/837)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/253)
> update kube-arbitrator to kube-batch in the doc

- content/docs/started/getting-started-gke.md
- content/docs/started/getting-started-minikube.md
* We want to use KUBEFLOW_TAG in the URL so we use the download.sh script
on the release branch.
Fix kubeflow/kubeflow#1738
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/257)
> Fix version in download.sh

- content/blog/nvidia_tensorrt.md
Old link pointed to personal github rather than master.
New link: https://github.com/kubeflow/kubeflow/tree/master/kubeflow/nvidia-inference-server
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/258)
> Corrected Github Repo link

- content/docs/guides/components/istio.md
- content/docs/guides/components/tfserving_new.md
- update doc on TF serving with the new template
- update doc on using Istio 1.0
I forked the original tf serving doc, and update it for the new template.
My plan is to continue improve on the new template, and when all the features are included in the new one, we can remove the old one.
/cc @jlewi 
@amygdala
ref https://github.com/kubeflow/kubeflow/pull/1795
ref https://github.com/kubeflow/kubeflow/pull/1309
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/265)
> update doc on TF serving and Istio

- config.toml
- content/blog/_index.md
Flixing blog menu item and the title on the blog page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/281)
> Fixing Blog title and menu

- content/docs/guides/components/istio.md
- content/docs/guides/components/tfserving_new.md
https://github.com/kubeflow/kubeflow/issues/1309
https://github.com/kubeflow/kubeflow/issues/1844
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/280)
> Add doc for rollout model

- content/docs/guides/gke/customizing-gke.md
- content/docs/guides/gke/troubleshooting-gke.md
The link to cluster-kubeflow.yaml is broken for 0.3.  I think this section should be more emphasized in the docs at some point, but I wanted to make sure the link was at least up to date for now
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/287)
> Fix Broken Link

- content/docs/guides/pipelines/pipelines-ui.md
The viewer link is not right, link to unknown page. 
The PR to correct the link to reasonable page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/356)
> correct link for viewers in pipelines-ui page

- content/docs/guides/components/tfserving_new.md
`http://` protocol is not helpful here and leads TF-Serving fail to downloads model bits. 
Logs:
```
2018-12-10 05:52:56.685207: I external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:54] Found secret key
2018-12-10 05:52:56.685308: I external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:54] Pool grown by 2
2018-12-10 05:52:56.685333: I external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-12-10 05:52:56.744106: E external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:60] Curl returned error code 6
2018-12-10 05:52:56.744211: W external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust …
```
> Use right S3 API Endpoint to avoid hostname can not resolve issue

- content/docs/guides/pipelines/pipelines-metrics.md
This page missed the boat on the main Docsy conversion, because the page was added after I converted all front matter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/392)
> Updated page front matter for Docsy theme.

- content/docs/started/getting-started-multipass.md
- content/docs/started/getting-started.md
This branch/pull request replaces PR #391, which was closed due to
errant rebase.
This change updates the instructions for installing Microk8s, including
making it clear that Multipass isn't required if the user is already on
a Linux system.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/398)
> Updated instructions for Microk8s getting started

- content/docs/started/getting-started.md
KFAPP cannot be a path based on [kfctl.sh](https://github.com/kubeflow/kubeflow/blob/master/scripts/kfctl.sh#L325-L354). `cd ${KFAPP}` may mislead user to name it as a path. We should clarify what it is.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/431)
> clarify that KFAPP should not be a path

- content/docs/other-guides/troubleshooting.md
Added entry to troubleshooting guide "Pods stuck in Pending state" to help users debug issue seen when the 3 PVCs required for Kubeflow to successfully start all pods are not satisfied. This change closes issue #317
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/423)
> Updated troubleshooting for getting started (#317)

- content/docs/components/tfserving_new.md
Added additional optional instructions on how to change the service type of the model service, should give some users a hint on how to expose the external IP. Per default this param seems to be set to ClusterIP, which only exposes internal IP.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/440)
> Added optional instructions on how to change the service type

- netlify.toml
Our website has never been indexed. This may be one of the causes of our low SEO (issue https://github.com/kubeflow/website/issues/98). The lack of index also makes our upcoming search page (PR https://github.com/kubeflow/website/pull/471) empty.
By adding the production environment config to the Netlify build, this PR should result in the site index being built.
See info:
https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify
I'm submitting this change in a separate PR from the search box PR, because it may take a day or two before the index is built and search results start appearing.
The setting of the production environment may also trigger the creation of the `sitemap.xml` file, in which case I won't need to do that in PR …
>  Sets Hugo prod environment in Netlify to trigger indexing of site.

- content/docs/pipelines/pipelines-metrics.md
In [Pipeline metrics](https://www.kubeflow.org/docs/pipelines/pipelines-metrics/) guide, there is a link issue which is point to unreasonable line. Correct that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/478)
> update doc to point reasonable line

- config.toml
The URL had one too many zeroes at the beginning. This should fix the emptiness of our search box.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/483)
> Fixes the URL for our custom search.

- layouts/sitemap.xml
Google Search Console does not recognise the format of the URLs in our sitemap. Error given:
```
This is not a valid URL. Please correct it and resubmit.
Examples
URL:
/docs/about/
Line 6
Parent tag:
url
Tag:
loc
URL:
/docs/gke/customizing-gke/
Line 11
Parent tag:
url
Tag:
loc
URL:
/docs/started/getting-started/
Line 16
Parent tag:
url
Tag:
loc
```
To fix this, I'm inserting the URL directly into the sitemap template.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/508)
> Added base URL to sitemap.

- config.toml
- content/docs/components/tftraining.md
- content/docs/reference/_index.md
- content/docs/reference/index.md
- content/docs/reference/overview.md
- content/docs/reference/tfjob/_index.md
- content/docs/reference/tfjob/v1beta1/_index.md
- content/docs/reference/tfjob/v1beta2/_index.md
I've added an index page for API references, in preparation for the TFJob reference described in issue https://github.com/kubeflow/tf-operator/issues/731
I've also added a link from the TFJob user guide to the (upcoming) reference, and configured a compact left-hand nav to make it easier to see all the doc sections.
Note that this PR isn't ready to submit, as it assumes the existence of the v1beta2 API reference for TFJob.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/514)
> Added the framework for API references.

- content/docs/reference/tfjob/v1beta1/common.md
- content/docs/reference/tfjob/v1beta1/tensorflow.md
- content/docs/reference/tfjob/v1beta2/common.md
- content/docs/reference/tfjob/v1beta2/tensorflow.md
- gen-api-reference/README.md
- gen-api-reference/gen-tfjob-api.sh
- gen-api-reference/kubeflow-config.json
Also fixed an incorrect version name in the docs.
Fixes https://github.com/kubeflow/tf-operator/issues/731.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/521)
> Add instructions for running API reference generation tool

- content/docs/started/getting-started-gke.md
I ran into some troublesome errors when installing Kubeflow on the command line. This PR updates the instructions so other people don't run into the same issues.
* Prerequisite: Must have pyyaml installed.
* The value of KUBEFLOW_SRC must contain the full path to the directory, else you get errors when you try to run kfctl.sh.
* The value of KFAPP cannot be > 25 characters. It must contain just the directory name, not the full path to the directory.
* The value of KFAPP becomes the name of your deployment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/522)
> Clarified the GKE getting-started guide for command line.

- README.md
- content/docs/started/getting-started.md
- content/docs/started/requirements.md
- layouts/shortcodes/kubernetes-min-version.html
Removed broken link from the shortcode for the Kubernetes version. I decided not to replace the link with another, as (a) we no longer use a link for the ksonnet version, which is used in the same places in the docs, and (b) any link we use may break again.
I also added the word "version" in the two docs that use this shortcode, for consistency with the usage for the ksonnet version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/526)
> Removed broken link from K8s version shortcode

- content/docs/started/getting-started-gke.md
* Added description for `${PROJECT}` variable
* `${PROJECT}` was not defined in step 2 of the `Deploy Kubeflow on GKE using the command line` section. 
* While it is pretty intuitive for those that use GCP, without a description it can be easy to forget to set it when running the command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/541)
> Add description PROJECT variable

- content/docs/pipelines/reusable-components.md
- Pulls out the component output from each component to make it a tiny bit easier to find with a quick scan.
- Makes a guess at what the component output for the BigQuery query might be (needs verification).
- Removes the **Component:** preceding each component -- this seems redundant, unless other non-component items will be added to this list. Otherwise, the bolded URL / name gives each component sufficient visual distinction on the page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/551)
> Sets apart component output for each component.

- content/docs/reference/_index.md
- content/docs/reference/overview.md
- content/docs/reference/pytorchjob/_index.md
- content/docs/reference/pytorchjob/v1beta1/_index.md
- content/docs/reference/pytorchjob/v1beta1/pytorch.md
- content/docs/reference/pytorchjob/v1beta2/_index.md
- content/docs/reference/pytorchjob/v1beta2/pytorch.md
- content/docs/reference/tfjob/v1beta1/common.md
- content/docs/reference/tfjob/v1beta1/tensorflow.md
- content/docs/reference/tfjob/v1beta2/common.md
- content/docs/reference/tfjob/v1beta2/tensorflow.md
- gen-api-reference/gen-pytorchjob-api.sh
- gen-api-reference/gen-tfjob-api.sh
- gen-api-reference/kubeflow-config.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/545)
> Pytorch documentation for v1beta1 and v1beta2

- content/docs/pipelines/sdk/install-sdk.md
Most recent version of miniconda installs pip, not pip3 with Python 3.7.  When using GCP Cloud Shell, pip3 is in /usr/bin and will cause kfp package to end up in the users site packages directory and not in the mlpipelines env.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/589)
> Fix typo(s) in installation of kfp package via conda

- content/docs/gke/deploy/delete-cli.md
- content/docs/gke/deploy/delete-ui.md
- content/docs/gke/deploy/deploy-cli.md
- content/docs/gke/deploy/deploy-ui.md
- content/docs/gke/deploy/next-steps.md
- content/docs/gke/deploy/reasons.md
Fixes some issues in the CLI deployment guide, as described in issue https://github.com/kubeflow/website/issues/584.
Moves the section about deleting via CLI into a new page, for parity with deleting via UI.
Fixes link to Netlify preview instead of actual doc page in the UI deletion page (https://github.com/kubeflow/website/issues/605).
Makes various textual improvements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/606)
> Fixes up the GKE deployment and deletion guides

- content/docs/fairing/gcp-kubeflow-notebook.md
Adds documentation for using the Fairing XGBoost quickstart in a Kubeflow hosted notebook.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/620)
> Adds gcp-kubeflow-notebook.md to Fairing docs.

- content/docs/started/getting-started-k8s.md
- content/docs/started/getting-started.md
* Add a getting started page for on prem users and users with an existing K8s
cluster. This guide should explain how to use kfctl go binary rather
than kfctl.sh
* The main getting started page should link to individual getting started pages.
Fix #630 - remove who should consider using Kubeflw.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/642)
> Update Getting started guide for 0.5;

- content/docs/fairing/gcp-kubeflow-notebook.md
In the Fairing guide to training/deploying from a Kubeflow notebook, this PR makes it clear that the Kubeflow notebook already includes Fairing as well as other ML libraries. This PR also links to our new guide to setting up notebooks.
fixes https://github.com/kubeflow/website/issues/644
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/645)
> Clarified notebook setup in Fairing guide

- content/docs/gke/private-clusters.md
- content/docs/gke/troubleshooting-gke.md
* Provide instructions for how to replicate non-GCR images to a GCR registry
so that they are accessible from private GKE.
* We no longer depend on Kubeflow hosting a mirror for all images; instead
user's will mirrror the images to their own GCR and then update
relevant Kubeflow components
* The relevant scripts will be submitted in a pending PR to kubeflow/kubeflow
* Update instructions for dealing with legacy networks
* The cluster isn't fully functional yet
* Pipelines is having some issues; looks like mnio might not be deployed
fully.
* vizier db and vizier core are also crash looping.
* Will file additional issues to track that.
Related to: kubeflow/kubeflow#2086 deploy private GKE cluster
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> Update docs for enabling private clusters for 0.5.

- content/docs/gke/deploy/deploy-cli.md
It's a critical option to set at generate step.
The default value is us-east1-b.
If it's not specified at the generate step.  generated config files have the default zone hardcoded in multiple places.
Manually changing it in cluster*.yaml and doing the apply doesn't seem to work.
Even if it did, it's better that the users are aware of this option when they are creating the deployment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/618)
> Add --zone option to kfctl generate step

- content/docs/started/getting-started-k8s.md
The guide does not refer to ks but it is needed. 
The error can be found here: https://github.com/kubeflow/kubeflow/issues/3132
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/687)
> Getting started guide does not refer ks

- README.md
- config.toml
Added v0.5 branch to dropdown in config file, and also updated the README to explain how to do this. 
Note that the v0.5 site isn't serving content: https://v0-5.kubeflow.org/ 
When we know more about how to fix the above problem, I'll add that info to the README in this PR too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/701)
> Added v0.5 branch to dropdown

- README.md
- content/docs/about/docs.md
- content/docs/about/style-guide.md
Adds a style guide to help contributors to write documentation that readers can understand quickly and correctly.  The style guide is also needed for our upcoming Kubeflow Doc Sprint.
The guide includes the stylistic points that come up most frequently in PR reviews. My goal isn't to write a complete style guide. For people who do want more detailed information I've linked to the Google Developer Documentation Style Guide, as it's comprehensive, friendly, and easy to scan.
This PR is open to comments about other style guides we should link to and other style guidelines we should add for the Kubeflow docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/696)
> Adds a style guide for the Kubeflow docs

- content/docs/gke/customizing-gke.md
This very short PR updates the GCP docs on customizing the deployment under the section for adding IAM permissions. The current instructions don't work. These instructions do.
I deleted the old instructions. If they should remain, and are useful in some cases, please let me know and I can restore them. Thanks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/710)
> Update to how to create users

- content/docs/gke/deploy/deploy-cli.md
Indentation on code block was off by one space. Verified fix by running Hugo server locally.
fixes kubeflow/kubeflow#3266
Signed-off-by: Chris Hupman <chupman@us.ibm.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/709)
> Fixed indentation that broke numbering on CLI deployment page.

- content/docs/components/pytorch.md
Updated language to match what's in the `pytorch-operator` `README.md`
Here's the [diff](https://github.com/kubeflow/pytorch-operator/pull/126/files#diff-04c6e90faac2675aa89e2176d2eec7d8R22) with the change
fixes #635 
Signed-off-by: Chris Hupman <chupman@us.ibm.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/715)
> Updated language in pytorch-operator to fix broken link in issue 635

- content/docs/pipelines/pipelines-overview.md
Fixes the issue that imply Pipelines is available only on GCP
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/721)
> Fix for issue #704

- content/docs/other-guides/accessing-uis.md
- content/docs/started/getting-started-minikube.md
- layouts/shortcodes/code-webui-port-forward.html
Added instructions to start port forwarding before trying to access Web UIs, after installation via Minikube.
Also created short code to share commands with relevant section in "Accessing UIs" page.
_(addresses issue #656)_
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/731)
> Added instructions to start port forwarding before trying to access Web UIs

- resources/_gen/assets/scss/scss/main.scss_9fadf33d895a46083cdd64396b57ef68.content
- themes/docsy/assets/scss/_code.scss
Fixes https://github.com/kubeflow/website/issues/730
Code formatting embedded in text within a table is hard to read - the colour is too light. This change makes the inline code style within a table the same as the style outside a table.
**Before:**
**After:**
I'll submit this change to the Docsy theme as well, so that it won't be overwritten next time we get an updated version of Docsy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/733)
> Added code style within tables

- content/docs/gke/gcp-e2e.md
Fix issue for GOOGLE_APPLICATION_CREDENTIALS cannot be found on kubeflow.
Here is the [issue](https://stackoverflow.com/questions/56287936/google-application-credentials-cannot-be-found-on-kubeflow).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/735)
> Fix an issue in gcp-e2e.md.

- content/docs/pipelines/reference/_index.md
- content/docs/pipelines/reference/sdk.md
On this page:
https://www.kubeflow.org/docs/pipelines/reference/
PR https://github.com/kubeflow/website/pull/740 attempted to add a link to the Pipelines SDK docs, but the PR added the link in the wrong place. The result is no link.
Fixes https://github.com/kubeflow/website/issues/769
Fixes https://github.com/kubeflow/website/issues/345
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/770)
> Fixed link to Pipelines SDK reference

- content/docs/pipelines/reference/api.md
- content/docs/pipelines/reference/api/kubeflow-pipeline-api-spec.html
There's an empty bullet point on the Pipelines reference index page:
https://www.kubeflow.org/docs/pipelines/reference/
And the navigation of the website is broken by the Pipelines API reference (generated HTML):
https://www.kubeflow.org/docs/pipelines/reference/api/kubeflow-pipeline-api-spec/
This PR goes some way to improving the situation, given that the HTML file is auto-generated from Swagger. The style of the website nav is affected by the styling injected by Swagger, but at least we have a navigation now. And the index page no longer has an empty bullet point.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/772)
> Improves link and formatting of Pipelines API reference docs

- .gitattributes
Fixes https://github.com/kubeflow/website/issues/716
I've checked the [docs](https://git-scm.com/docs/gitattributes), which state:
> patterns that match a directory do not recursively match paths inside that directory (so using the trailing-slash `path/` syntax is pointless in an attributes file; use `path/**` instead)
I've also tested the new setting by making a change to the site's CSS, which resulted in a change in the files under `/resources` - it seemed to work as expected. I'll keep an eye on the diff/merge behaviour for CSS-related changes for a while.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/777)
> Fixed path in gitattributes file

- content/docs/about/kubeflow.md
Reorganised the info on the page and added links through to the docs.
Based on analytics report for the [about Kubeflow](https://www.kubeflow.org/docs/about/kubeflow/) page, March 1 to April 19:
* Bounce rate is 63%. That’s higher than average (average is ~ 41 to 55 percent). Given that this page is just an introduction and our intention is to draw people in to get more info about Kubeflow, we need to lower the bounce rate.
* **Action:** Optimize the links on this page. At the moment, the first 3 links point to external sites (TensorFlow and Jupyter) and only one link points to a Kubeflow doc.
Fixes https://github.com/kubeflow/website/issues/692
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Refactored the 'about Kubeflow' page to provide more info and links

- content/docs/aws/deploy/install-kubeflow.md
Recently master branch is actively changed there're several breaking changes to AWS. Since aws is not part of testing framework, it's hard for us to detect those changes. 
Users reported several issues https://github.com/kubeflow/kubeflow/issues/3332 https://github.com/kubeflow/kubeflow/issues/3421 https://github.com/kubeflow/kubeflow/issues/3433
Let's use most recent stable version in documentation to avoid these issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/798)
> Use stable kf version in aws deployment

- layouts/partials/page-meta-links.html
Added a site-specific version of the `layouts/partials/page-meta-links.html` file, so that I can add code to inject the page URL into any issue created when the user clicks the **Create issue** option on a doc page. In the file, line 9 is new and file 10 is adjusted to add the `body` of the issue:
```
{{$doc_url := printf "https://www.kubeflow.org%s" .URL }}
{{ $issuesURL := printf "%s/issues/new?title=%s&body=%s" $gh_repo (htmlEscape $.Title) (htmlEscape $doc_url) }}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/807)
> Added doc URL to 'Create issue' option

- content/docs/pipelines/tutorials/pipelines-tutorial.md
This will remove the problem to ensure ```activate``` and ```deactivate``` are in the ```PATH```.
https://askubuntu.com/questions/1068768/when-using-conda-source-activate-env-name-doesnt-work-but-conda-activate
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/828)
> fix: conda environment selection

- content/docs/pipelines/sdk/install-sdk.md
Closes #830.
The [other](https://github.com/kubeflow/website/blob/aeccc6297bcf23d588b14cca6d732796ac2e3c59/content/docs/pipelines/tutorials/build-pipeline.md) occurrence of 'source activate' should not be change as it is not limited to conda and may refer to other virtual environments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/831)
> Change 'source activate' to 'conda activate'

- content/docs/notebooks/setup.md
- content/docs/pipelines/overview/pipelines-overview.md
- content/docs/pipelines/pipelines-quickstart.md
- content/docs/pipelines/sdk/install-sdk.md
- content/docs/pipelines/tutorials/build-pipeline.md
- content/docs/pipelines/tutorials/pipelines-tutorial.md
- content/docs/started/getting-started.md
We recently added an introduction to the Pipelines SDK (https://github.com/kubeflow/website/pull/811). This PR adds links from various pages to the new new intro, so that people can find the intro more easily.
I've also fixed a couple of links that pointed to the obsolete "guides" section - our redirects are handling those links, but it's good to fix them when we find them.
Where necessary, I've adjusted other lines in the "Next steps" sections to ensure that the bullet items have parallel syntax.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/827)
>  Linked to the new Pipelines SDK intro from various pages

- content/docs/started/getting-started-k8s.md
The `existing_arrikto` platform and config file is a curated way to deploy Kubeflow on existing clusters using no cloud-specific features.
This PR updates the `Kubeflow on Kubernetes` page with the current working options for deploying Kubeflow on an existing Kubernetes cluster.
cc @sarahmaddox @jlewi 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/861)
> existing cluster: existing_arrikto: update docs on options for installing on existing K8s clusters

- content/docs/components/pytorchserving.md
Related to #826 though really more of an existing edit at this point.
While reading through the PyTorch Serving example I discovered the old URL to the Seldon Docs was not working. This appears to be their updated python wrapper documentation which has links to using Seldon-Core with Python.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/895)
> Updated non-working URL

- content/docs/other-guides/troubleshooting.md
The PVCs aren't all requesting 10Gi.
```
$ k get pvc -o custom-columns='name:{.metadata.name},storage:{.spec.resources.requests.storage}'
name             storage
katib-mysql      10Gi
minio-pvc        20Gi
mysql-pv-claim   20Gi
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/854)
> update troubleshooting guide to reflect size of pending PVCs

- content/docs/aws/deploy/install-kubeflow.md
- content/docs/azure/deploy/install-kubeflow.md
- Removed references to ksonnet on AWS deployment page
- Removed references to ksonnet on Azure deployment page
- Removed unnecessary whitespace
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/911)
> #864: Remove ksonnet from AWS Azure deployment pages

- content/docs/started/getting-started-k8s.md
- content/docs/use-cases/kubeflow-on-multinode-cluster.md
I described in this use case how to setup in on-prem multi-node Kubernetes cluster Dynamic Provisioning using NFS volumes in order to allow KubeFlow installation and bind existing Persistent Volume Claims without pain.
I added also a Limitations section for this solution and a Resources section to get information about Kubernetes resources used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/897)
> Kubeflow multinode cluster installation #896

- content/docs/other-guides/troubleshooting.md
I goofed this up in my last PR.
sudo mkdir /mnt/pv[1-3]
creates a single directory name `/mnt/pv[1-3]`. Instead, we want
sudo mkdir /mnt/pv{1..3}
which will create the desired 3 directories: `/mnt/pv1`, `/mnt/pv2`, and `/mnt/pv3`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/936)
> fix bash brace expansion in troubleshooting guide

- content/docs/aws/deploy/existing-cluster.md
I found that we use `REGION` env parameter for aws_region at the document, but one command use `AWS_REGION` which isn't declared.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/944)
> AWS_REGION to REGION

- content/docs/gke/authentication.md
I wrote an auth guide to explain how to authenticate/control access to the different systems that make up Kubeflow on GCP. 
Related to https://github.com/kubeflow/website/issues/679
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/916)
> GCP Auth guide

- content/docs/started/getting-started-k8s.md
This PR extends the documentation on existing_arrikto and adds instructions for connecting with LDAP/AD
cc @sarahmaddox 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/898)
> kubeflow on kubernetes: existing_arrikto: add instructions for connecting with LDAP/AD

- content/docs/aws/deploy/install-kubeflow.md
Currently kubeflow's installation script use `eksctl` commands such as below.
https://github.com/kubeflow/kubeflow/blob/master/scripts/aws/util.sh#L28
But the command option is hard coded and we can't use `--profile` option.
When we'd like to install kubeflow using switch role, we have to use `aws sts assume-role` before installation.
I think it's better to write about it on the installation document.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/947)
> add statement about assumerole

- content/docs/use-cases/kubeflow-on-multinode-cluster.md
Minio PVC is not called " minio-pvc" but " minio-pv-claim"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/965)
> Fixed spelling mistake to reflect actual naming

- content/docs/examples/codelabs-tutorials.md
- content/docs/started/getting-started.md
Fixes https://github.com/kubeflow/website/issues/983
Fixes https://github.com/kubeflow/website/issues/1002
* Moved the long list of tutorial/codelabs from the getting-started page, and added a link to the tutorials/codelabs page instead.
* Reorganised the tutorials/codelabs page for better readability.
* Removed all links to Qwiklabs, as the labs are all either non-existent or restricted access.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1003)
> Fixed links to tutorials and codelabs

- content/docs/notebooks/setup.md
Fixes https://github.com/kubeflow/website/issues/993
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1001)
> Added link from notebooks setup to multi-user isolation doc

- content/docs/other-guides/job-scheduling.md
Ref https://github.com/volcano-sh/volcano/issues/241
volcano scheduler is migrated into volcano repo, thus we need to update the website.
/cc @k82cn
Signed-off-by: Ce Gao <gaoce@caicloud.io>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1005)
> fix: Fix the repo

- content/docs/gke/deploy/project-setup.md
Users are still confused what role/permissions they might need to deploy Kubeflow. Additionally, clarifying why the role is needed.
Fixes #1013
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1016)
> add owner role requirement in GCP project setup

- layouts/partials/scripts.html
Hi @sarahmaddox, I made a little color adjustment to make the heading anchor use default coloring for a link. It now has on hovering effect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1022)
> Fix anchor icon color + formatting

- content/docs/gke/deploy/deploy-cli.md
Sarah, feel free to reject any of these changes :).
Of note: I clarified that the the KFPAPP-storage deployment is not a (GKE) cluster.
I also moved the 'check cluster namespace' step to after the step that describes the 2 deployments, and added the command to set up the cluster credentials first.
Made a couple other minor mods as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1026)
> added a few clarifications to the GKE CLI installation instructions

- content/docs/gke/deploy/deploy-ui.md
Following the instructions above:
- go to https://deploy.kubeflow.cloud
- enter previously created GCP project name and other required information
- click 'Create Deployment'
Result:
An error message indicates that the project can't be located. The required information was the project ID, not the project name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1028)
> Deployment UI requires project id, not name

- content/docs/gke/deploy/deploy-cli.md
- content/docs/gke/deploy/oauth-setup.md
I ran through the GCP deployment process using the CLI for v0.6 and fixed up any hiccups in the docs.
Fixes https://github.com/kubeflow/website/issues/1020
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1021)
> Fixed up the GCP deployment guide for CLI v0.6

- content/docs/pipelines/tutorials/build-pipeline.md
Some file links can't be fond and report as the 404 errors.  URL:https://www.kubeflow.org/docs/pipelines/tutorials/build-pipeline/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1032)
> Fix docs link 404 errors.

- content/docs/fairing/gcp/tutorials/gcp-kubeflow-notebook.md
There is no var named `path-to-cloned-fairing-repo`, and in fact, that's no need since git clone to current path, Just remove `path-to-cloned-fairing-rep` to avoid confusing user. Thanks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1031)
> fix mini problem in fairing doc

- content/docs/reference/images.md
For now, when install kubeflow, Katib v1alpha2 is installed. We should update Katib related Dockerfile to v1alpha2 instead of v1alpha1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1049)
> Update katib Dockerfile locations link

- content/docs/started/k8s/kfctl-k8s-istio.md
Resolves kubeflow/kubeflow#3774
The current instructions for kfctl_k8s_istio.yaml deployment of Kubeflow lack volume provisioner instructions before Kubeflow's deployment which lead to all of Kubeflow's PVCs to `Pending` state in Kubernetes clusters not having a dynamic volume provisioner.
This PR updates the instructions for the setup of a dynamic volume provisioner or alternative methods of handling the same issue.
/assign @krishnadurai 
/cc @johnugeorge @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1040)
> Instructions on setting up dynamic volume provisioner

- content/docs/pipelines/overview/pipelines-overview.md
Pipeline overview doc reflected a stale URL for the xgboost-spark sample. This commit updates to the correct URL of the xgboost-spark directory of the Kubeflow repo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1052)
> xgboost url update

- content/docs/pipelines/pipelines-quickstart.md
- content/docs/pipelines/sdk/output-viewer.md
Fix two stale links due to recent sample test refactoring.
See [relevant PR](https://github.com/kubeflow/pipelines/pull/1730).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1060)
> Fix broken links

- content/docs/other-guides/accessing-uis.md
- layouts/shortcodes/code-webui-port-forward.html
See #1041 and kubeflow/kubeflow#3618
* With 0.6 if no auth is setup and you want to connect via port-forwarding
then you need to port-forward to the ISTIO gateway; not ambassador
* I suspect the original suggestion in #1041 to port-forward to Ambassador
only worked in the basic auth setting in which case we are still setting
up Ambassador.
Fix: #1041
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1067)
> Fix port-forarding instructions; port-forward to istio gateway

- content/docs/gke/deploy/deploy-cli.md
- content/docs/gke/deploy/deploy-ui.md
- content/docs/gke/pipelines-tutorial.md
- content/docs/gke/troubleshooting-gke.md
- content/docs/other-guides/accessing-uis.md
Fixes https://github.com/kubeflow/website/issues/1082
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1083)
> Clarified port forwarding and auth for GCP

- content/docs/aws/deploy/install-kubeflow.md
- content/docs/started/k8s/kfctl-existing-arrikto.md
- content/docs/started/k8s/kfctl-k8s-istio.md
Fixes https://github.com/kubeflow/website/issues/1070
/hold
Until the existing_arrikto rename is cherry picked in v0.6-branch: https://github.com/kubeflow/kubeflow/pull/3884
/cc @abhi-g @lluunn 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1071)
> pin config links for v0.6 to v0.6-branch

- content/docs/other-guides/usage-reporting.md
Fixes issue: #1084
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1085)
> Modify the out of date guaid docs.

- content/docs/started/k8s/kfctl-existing-arrikto.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1086)
> Fixing command to retrieve the existing Dex configmap

- content/docs/other-guides/usage-reporting.md
Moved content around and fixed code formatting to clarify the guide, which tells folks how to opt out of or disable usage reporting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1087)
> Clarified the usage reporting guide

- content/docs/other-guides/virtual-dev/getting-started-minikube.md
this fix changes markdown formating for link to `/docs/started/k8s/overview` page,
that currently broken on the website.
see - https://www.kubeflow.org/docs/other-guides/virtual-dev/getting-started-minikube/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1088)
> markdown formatting fix.

- content/docs/started/cloud/getting-started-icp.md
Since Ambassador service has been dropped in Kubeflow 0.6.1, update the instruction to access Kubeflow Dashboard via istio-ingressgateway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1105)
> Fixed launching Kubeflow dashboard in 0.6.1.

- content/docs/gke/deploy/deploy-cli.md
With 0.6.2 we want to start using the --config flag.
We decided to pin to specific commits of the KFDef files. This
might be overkill because on the tip of the branch the config files
are named based on the version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1106)
> Update the v0.6.2 gcp instructions.

- content/docs/gke/deploy/deploy-cli.md
on v0.6.2 we still need `--use_basic_auth` during init
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1112)
> add --use_basic_auth flag to cli doc

- content/docs/gke/cloud-filestore.md
* We can just link to the instructions on the GKE site which describes how
to create PVs and PVC to access the volume.
Fix #842
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1136)
> Remove ksonnet from the Cloud Filestore instructions.

- content/docs/other-guides/virtual-dev/getting-started-minikf.md
Add the `request an invite` link for the Kubeflow Slack workspace to the MiniKF guide, so that people who are not members of the workspace can join easily.
> Add invite link for Kubeflow Slack workspace to the MiniKF guide

- README.md
Removed info about configuring a new version of the website, and linked to the Kubeflow release guide instead. PR https://github.com/kubeflow/kubeflow/pull/4127 adds the info to the Kubeflow release guide.
Fixes https://github.com/kubeflow/website/issues/1153
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1154)
> Moved versioning config info to Kubeflow release guide

- config.toml
Added v0.6 to the menu and branded the main website as v0.7.
Fixes https://github.com/kubeflow/website/issues/1138
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1152)
> Added version 0.6 branch of the website

- content/docs/fairing/install-fairing.md
Since the fairing has been a subpackage of kubeflow, renamed to kubeflow-fairing, see more in the PR https://github.com/kubeflow/fairing/pull/359 and ticket https://github.com/kubeflow/fairing/issues/234. And kubeflow-fairing 0.6.0 version has been released.
The PR is to update fairing to kubeflow-fairing, thanks.
Fixes: #1146 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1155)
> update fairing to kubeflow-fairing

- content/docs/components/misc/metadata.md
Fixes: #1171 
update to kubeflow-metadata due to metadata SDK has been renamed to kubeflow-metadata
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1173)
> update to kubeflow-metadata due to renaming

- content/docs/started/cloud/getting-started-icp.md
Installed new kubeflow on ICP, seems there are some changes. Update related docs to fit new version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1158)
> update getting-started-icp for new version kubeflow installing

- content/docs/gke/troubleshooting-gke.md
Fix incorrect namespace for command "kubeflow" -> "istio-system"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1162)
> Ingress is in the istio-system namespace

- content/docs/components/training/tftraining.md
This explanation is duplicated with previous previous line.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1179)
> Delete duplicated explanation for 'restartPolicy ExitCode' in tfJob

- content/docs/pipelines/overview/pipelines-overview.md
- content/docs/pipelines/sdk/build-component.md
- content/docs/pipelines/sdk/manipulate-resources.md
- content/docs/pipelines/sdk/pipelines-metrics.md
- content/docs/pipelines/tutorials/build-pipeline.md
This is global update, its meaning to fix links to kubeflow/pipelines
repository
1. `pipeline-metrics.md` - taxy pipeline and notebook link (tfx)
2. `manipulate-reposerces.md` - renamed resources
see kubeflow/pipelines@fe0bc678a
3. `build-pipeline.md` link to tfx notebook + general link to
samples/core, as notebooks now located in multiple directories.
4. `build-pipeline.md` - other pipeline repo changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1199)
> updating broken pipelines references

- content/docs/started/cloud/getting-started-icp.md
When deployed a service of LoadBalancer type in ICP, the EXTERNAL-IP field will stuck in PENDING state, this PR will add info on how to resolve this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1227)
> Add troubeshooting for ICP LoadBalancer

- content/docs/started/k8s/kfctl-k8s-istio.md
Resolves: kubeflow/kubeflow#3939
Removes the linux/darwin script to download and install kfctl. Preferred way of installing would be to download the tar file and unpack - this instruction wouldn't base it on the platform kfctl is being deployed on. Rather, the downloader should be able to download the appropriate kfctl build for their platform.
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1231)
> Removes kfctl download and unpack script

- content/docs/gke/gcp-e2e.md
tracking issue: https://github.com/kubeflow/website/issues/1221 .
Accompanying update to the example code: https://github.com/kubeflow/examples/pull/658 (pin the TF version in the web-ui dockerfile) .
My text editor trims EOL whitespace, so there are a bunch of diffs for those.  The changes of substance:
- changed the tf-serving service from `mnist-gcs-dist` to `mnist-service` so that the web UI would work out of the box. (If there is a good reason for using the other name, we can have them edit the service in the web ui, but they'll see that scary error first)
- when they set up their bucket paths, add a timestamp-based subdir (so that they can run the example more than once)
- since the web-ui service is using `ClusterIP`, and not generating an external IP, changed the instructions to …
> intro tutorial updates

- content/docs/started/k8s/kfctl-k8s-istio.md
This is done because the config also points to the same version.
Relates to issue #1246
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1250)
> Pin kfctl release binary to v0.6.2

- config.toml
Now that we're changing the deployment guides to use the new v0.7 kfctl and config files, it makes sense to indicate that the docs are for v0.7 RCs. This will prompt people to open the version menu and go to the v0.6 docs if they want v0.6.
Working towards https://github.com/kubeflow/website/issues/1222 - we'll need to remove the "RC" from the version label when we release the final version of v0.7.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1264)
> Changed website label to v0.7RC

- layouts/shortcodes/config-uri-existing-arrikto.html
PR https://github.com/kubeflow/manifests/pull/565 added the version number to the `kfctl_existing_arrikto` YAML file, so we need to update the URL in the docs too.
Working towards closing https://github.com/kubeflow/website/issues/1224
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1270)
> Updated config URL to include version num for existing_arrikto

- content/docs/pipelines/sdk/gcp/preemptible.md
Fixes the last-remaining occurrence of `KFAPP` (should be `KF_NAME` to match new deployment guides). Also replaces some absolute doc URLs with relative URLs.
Fixes https://github.com/kubeflow/website/issues/1252
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1266)
> Replaced KFAPP with KF_NAME and fixed some URLs

- content/docs/other-guides/kustomize.md
The [kustomize](https://github.com/kubernetes-sigs/kustomize/releases) has releases for other assets than `kustomize` and the latest one is not `kustomize`. Hence the current script is broken. Fix to download the kustomize latest version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1274)
> update kustomize download script

- content/docs/aws/deploy/install-kubeflow.md
- content/docs/gke/cloud-filestore.md
- content/docs/gke/customizing-gke.md
- content/docs/gke/deploy/delete-cli.md
- content/docs/gke/deploy/deploy-cli.md
- content/docs/gke/troubleshooting-gke.md
- content/docs/other-guides/kustomize.md
- content/docs/other-guides/usage-reporting.md
- content/docs/started/cloud/getting-started-icp.md
- content/docs/started/k8s/kfctl-k8s-istio.md
- content/docs/upgrading/upgrade.md
- layouts/shortcodes/config-file-aws-cognito.html
- layouts/shortcodes/config-file-aws-standard.html
- layouts/shortcodes/config-file-gcp-basic-auth.html
- layouts/shortcodes/config-file-gcp-iap.html
- layouts/shortcodes/config-file-k8s-istio.html
The config files created by kfctl now include version number in the file name. We've adjusted all the config URIs but we also need to adjust the file names as referred to in the docs. For example, this:
```
export CONFIG_FILE=${KF_DIR}/kfctl_gcp_iap.yaml
```
Should become:
```
export CONFIG_FILE=${KF_DIR}/kfctl_gcp_iap.0.7.0.yaml
```
This PR creates the relevant shortcodes to future-proof this change throughout the deployment guides and other docs. It sets the shortcode values to the `<config file name>.0.7.0.yaml` pattern which we use for Kubeflow v0.7.0. We'll need to update the shortcodes for each release, along with the similar shortcodes for the config URIs.
This PR doesn't change the guide for [`kfctl_existing_arrikto`](https://www.kubeflow.org/docs/started/k8s/kfctl-existing-arrikto …
> Fixed and parameterised local config file names

- content/docs/aws/deploy/install-kubeflow.md
Once we run `kfctl build`, `aws_config` and `kustomize` are generate and `kfctl apply` will not regenerate them as they exist. (see PR https://github.com/kubeflow/kubeflow/pull/4369)
The problem is aws customization will be done after `build`. `apply` won't pick up new parameters.
Since PR is included in RC6 and later versions. We need to make this change to unblock deployment.
Talked with team jeremy on solutions here. https://github.com/kubeflow/kubeflow/issues/4368#issuecomment-545889048
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1284)
> Add extra step to clean up kustomize for aws 

- content/docs/aws/deploy/install-kubeflow.md
- content/docs/started/cloud/getting-started-aws.md
old name: Amazon Elastic Container Service for Kubernetes
new name: Amazon Elastic Kubernetes Service
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1294)
> update Amazon EKS name on aws docs

- content/docs/gke/deploy/deploy-cli.md
- content/docs/gke/deploy/deploy-ui.md
- content/docs/gke/deploy/project-setup.md
Adds more GCP APIs that need to be enabled, and clarifies the quota situation for GCP free tier.
Fixes https://github.com/kubeflow/website/issues/1288
Fixes https://github.com/kubeflow/website/issues/1248
Fixes https://github.com/kubeflow/website/issues/1065
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1289)
> Clarified GCP APIs and quota requirements

- content/docs/started/k8s/kfctl-existing-arrikto.md
following these directions exactly ends you up with a path of `/opt//kf-test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1297)
> remove trailing slash for example BASE_DIR

- content/docs/reference/_index.md
Removed some obsolete sections from the reference docs index page. The sections are now duplicated in the overview page:
https://www.kubeflow.org/docs/reference/overview/
The index page need only contain a list of pages in the reference section.
Fixes https://github.com/kubeflow/website/issues/1309
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1310)
> Removed obsolete sections from the reference index page

- content/docs/components/serving/tfserving_new.md
In k8s 1.16 extensions/v1beta1 is no longer available, while apps/v1 has
been available for some time now and should be a safe to transition to.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1321)
> Use apps/v1 Deployments

- content/docs/notebooks/setup.md
Removes Ambassador reference and duplicating instructions on connecting to Kubeflow UI and links the relevant page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1322)
> remove ambassador reference in jupyter notebook doc

- OWNERS
This change adds @alecglassford  and @rionam to the website OWNERS file as approvers and reviewers, so that we can review + approve changes contributed during the [Write the Docs AU 2019 doc fixit](https://www.writethedocs.org/conf/australia/2019/doc-fixit-kubeflow/).
This is intended to be a temporary change, and I'll send a followup change removing the two of us after the event(~2019-11-15).
@sarahmaddox: The [contributors guide section on OWNERS](https://www.kubeflow.org/docs/about/contributing/#owners-a-name-owners-1-a) says, "All users are expected to be assignable. In GitHub terms, this means they are either collaborators of the repo, or members of the organization to which the repo belongs," so I think you will indeed need to add us as collaborators on the kubeflow/website repo. …
> Add doc fixit hosts to OWNERS for WtD AU 2019

- content/docs/gke/authentication.md
Fixes https://github.com/kubeflow/website/issues/1382
* Expand abbreviation in page description - change "Authentication and authorization to GCP" to "Authentication and authorization to Google Cloud Platform (GCP)".
* Find the first occurrence of "GKE" and similary expand it to "Google Kubernetes Engine (GKE)".
* Add an intro sentence before the first heading: "This page describes in-cluster and local authentication for Kubeflow GCP deployments." 
* Change "i.e., " to "that is,".
* Change "you will need to" to "you must". (NOTE: even "you must" is probably too much here)
* Change all references to Kubeflow versions to include "v" in the version name: "Kubeflow version 0.6" -> "Kubeflow v0.6"; "Starting in 0.7" -> "Starting in v0.7"; and any others.
* Change all in-page headings to …
> WtD fixit: Readability improvements for Authenticating Kubeflow to GCP

- content/docs/about/contributing.md
Resolved #1332 
For help wanted issue link which is added
https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22+org%3Akubeflow
@sarahmaddox Please review it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1406)
> Changed link of "good first issue" and "help wanted"

- content/docs/aws/deploy/install-kubeflow.md
I had to remove the space between `sed -i` and the extension because I received this error: `# sed: can't read .bak: No such file or directory`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1407)
> Fix invalid sed statement in install docu

- .github/workflows/triage_issues.yaml
* This will automatically add/remove issues from the needs triage
Kanban board depending on whether the issue satisfies the triage
criterion.
* Related to kubeflow/community#278
* Related to kubeflow/community#306
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1414)
> Add a GitHub action to automatically add/remove issues from needs triage Kanban board

- OWNERS
Reverts kubeflow/website#1335 now that the fixit has passed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1418)
> Remove WtD AU 2019 doc fixit hosts from OWNERS

- content/docs/upgrading/upgrade.md
Currently, kfctl of v0.6.2 does not support -f flag, following exiting documentation in https://www.kubeflow.org/docs/upgrading/upgrade/ 
Step 2 : 
...
kfctl delete -V -f ${CONFIG_FILE}
will throw an error. 
The documentation should be modified to download the kfctl of v0.7.0 first.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1420)
> Update upgrade doc for upgrading from v0.6.2

- content/docs/started/cloud/getting-started-icp.md
Installing Kubeflow v0.7 in IBM Cloud Private 3.1.0 may encounter the following error:
failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: Apply.Run  Error error when creating "/tmp/kout904105401": CustomResourceDefinition.apiextensions.k8s.io "profiles.kubeflow.org" is invalid: spec.validation.openAPIV3Schema: Invalid value:...
must only have "properties", "required" or "description" at the root if the status subresource is enabled
This is because the Kubernetes version 1.11 in IBM Cloud Private 3.1.0 is incompatible with Kubeflow v0.7.  Document this in the trouble shooting section to remind user to upgrade.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> Incompatible k8s version causes v0.7 installation fail

- content/docs/started/cloud/getting-started-icp.md
When installing Kubeflow v0.7 in IBM Cloud Private 3.2.0, pods may stuck in CreateContainerConfigError state and describe pod show the following error:
Error: container has runAsNonRoot and image will run as root
This is because new installation of IBM Cloud Private version 3.2.0 or later, the default pod security policy setting is the ibm-restricted-psp policy, which is applied to all of the existing and newly created namespaces. Document workaround in the trouble shooting section to handle this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1452)
> CreateContainerConfigError in Kubeflow v0.7 pod in ICP 3.2.0

- README.md
- quick-github-guide.md
Moved the guide to command-line git from the README to a new file, and added a section on using the GitHub UI. This guide is useful for new contributors to the Kubeflow docs, including people who take part in doc fixits and doc sprints.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1446)
> Expanded the quick guide to git/GitHub for novice contributors

- config.toml
- content/_index.html
The Slack invite link on the homepage was out-of-date. See this relevant
issue: https://github.com/kubeflow/website/issues/1456
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1457)
> Update the Slack invite link

- content/docs/examples/codelabs-tutorials.md
Add the Codelab of the Kubeflow workshop that was presented at KubeCon +
CloudNativeCon NA 2019, San Diego.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1461)
> Add the Codelab of the Kubeflow workshop

- content/docs/components/serving/kfserving.md
Add link to Azure, Kafka, S3, pvc to kfserving example website:
https://www.kubeflow.org/docs/components/serving/kfserving/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1468)
> Add link to Azure, Kafka, S3, pvc to kfserving example website

- content/docs/components/serving/overview.md
In https://www.kubeflow.org/docs/components/serving/overview/
under "Further Information" > KFServing: 3rd bullet:
- [Community]/docs/about/community/)
Use this PR to fix this (to point to the community url)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1471)
> Fix link to Kubeflow community in Serving overview site

- content/_redirects
- content/docs/pipelines/installation/_index.md
- content/docs/pipelines/installation/overview.md
- content/docs/pipelines/installation/standalone-deployment.md
Fixes https://github.com/kubeflow/website/issues/1429
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1472)
> Explained the various installation options for Kubeflow Pipelines

- content/docs/gke/customizing-gke.md
Add minimum CPU instructions to common customizations section
Instructs user how to specify a minimum CPU during cluster and node creation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1463)
> Adding minimum CPU instructions to common customizations section

- content/docs/gke/deploy/deploy-cli.md
@rmgogogo found this step is also required for following actions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1484)
> Add missing `gcloud auth login` step to "Deploy using CLI" doc

- content/docs/gke/authentication-pipelines.md
- content/docs/gke/authentication.md
- content/docs/gke/cloud-filestore.md
- content/docs/gke/custom-domain.md
- content/docs/gke/customizing-gke.md
- content/docs/gke/deploy/_index.md
- content/docs/gke/gcp-e2e.md
- content/docs/gke/monitoring.md
- content/docs/gke/pipelines-tutorial.md
- content/docs/gke/private-clusters.md
- content/docs/gke/troubleshooting-gke.md
- content/docs/pipelines/installation/standalone-deployment.md
/cc @IronPan
This is part of https://github.com/kubeflow/pipelines/issues/1691#issuecomment-568991297
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1489)
> Introducing workload identity setup for pipelines standalone

- content/docs/components/serving/overview.md
Currently in KFServing overview website: https://www.kubeflow.org/docs/components/serving/overview/
KFServing and Seldon Core info for ONNX are both pointing to same Seldon-core documentation.
Modify one to point to KFServing sample.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1479)
> Add ONNX sample to website

- content/docs/aws/troubleshooting-aws.md
Added details on troubleshooting steps when there are issues with the ALB ingress controller. The public subnets should have the correct tag **Name:** ```kubernetes.io/role/elb``` and **Value:** ```1```.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1470)
> Updated AWS Troubleshooting guide to add tag for public subnets

- content/docs/components/serving/kfserving.md
**What this PR does / why we need it**:
In https://www.kubeflow.org/docs/components/serving/kfserving/#kfserving-installation-using-kubectl,  add info about the yaml file so that user can install KFServing without cloning the Github repo.
**Which issue(s) this PR fixes** :
Fixes #1464
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1497)
> Add yaml info in KFServing install #1464

- content/docs/started/workstation/getting-started-linux.md
Current installation instructions will install (at the time of writing) k8s v1.17 - which is listed on https://www.kubeflow.org/docs/started/k8s/overview/ as being an incompatible version. Specifying the installation channel ensures the user installs a version that Kubeflow is verified against. 
These instructions will need to be updated as Kubeflow supports newer versions of K8s.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1519)
> Update Microk8s install to specify K8s version

- content/docs/about/community.md
Updated Slack info on the [community page](https://www.kubeflow.org/docs/about/community/): Added  a few channels, fixed the Slack terminology (workspace vs channel), and separated the Slack info into a new section, so that we can link to it more easily. In particular, the new v1.0 support page needs to link to the Slack info.
Fixes https://github.com/kubeflow/website/issues/1521
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1522)
> Clarified and expanded the Slack info

- content/docs/about/events.md
Preview: https://deploy-preview-1527--competent-brattain-de2d6d.netlify.com/docs/about/events/
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1527)
> Added the 2020 doc sprint to the events page

- content/docs/reference/katib/_index.md
- content/docs/reference/katib/v1alpha3/_index.md
- content/docs/reference/katib/v1alpha3/katib.md
**What this PR does / why we need it:**
Add the Katib API reference to the website docs
**Which issue(s) this PR fixes** 
Fixes #1481
Special notes for your reviewer:
@sarahmaddox 
Please review. Please note that I use PyTorchJob as example rather than Metedata reference since the katib reference is the description of each field (like type, description, etc.) which is closer to that in PyTorchJob reference.
**Question:**  there are two TODO in the original document in Github. How should we handle this in the website ? Leave them as TODO or remove them?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1531)
> Added Katib API reference to the website docs

- content/docs/components/training/mxnet.md
Add a useful way to install MXNet-Operator.
The documentation is from https://github.com/kubeflow/mxnet-operator/blob/master/README.md
Besides, I add code below to distinguish repos for users.
```
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1529)
> update mxjob docs

- config.toml
- layouts/docs/baseof.html
- layouts/partials/version-banner.html
v0.6 branch: Added logic to create a banner on archived doc sets (cherry-pick of PR https://github.com/kubeflow/website/pull/1535 plus updates specific to this branch).
Preview: https://deploy-preview-1550--confident-wescoff-57e975.netlify.com/docs/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1550)
> Kubeflow v0.6 docs: Added logic to create a banner on archived doc sets (#1535)

- config.toml
- layouts/docs/baseof.html
- layouts/partials/version-banner.html
v0.5 branch: Added logic to create a banner on archived doc sets (cherry-pick of PR https://github.com/kubeflow/website/pull/1535 plus updates specific to this branch).
Preview: https://deploy-preview-1556--practical-neumann-e70801.netlify.com/docs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1556)
> Kubeflow v0.5 docs: Added logic to create a banner on archived doc sets (#1535)

- config.toml
- layouts/docs/baseof.html
- layouts/partials/version-banner.html
v0.4 branch: Added logic to create a banner on archived doc sets (cherry-pick of PR https://github.com/kubeflow/website/pull/1535 plus updates specific to this branch).
Preview: https://deploy-preview-1558--infallible-hermann-cb44b2.netlify.com/docs/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1558)
> Kubeflow v0.4 docs: Added logic to create a banner on archived doc sets (#1535)

- config.toml
- themes/kf/layouts/docs/single.html
- themes/kf/layouts/partials/version-banner.html
v0.3 branch: Added logic to create a banner on archived doc sets (cherry-pick of PR https://github.com/kubeflow/website/pull/1535 plus updates specific to this branch).
Preview: https://deploy-preview-1559--competent-jones-a15cc2.netlify.com/docs/about/kubeflow/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1559)
> Kubeflow v0.3 docs: Added logic to create a banner on archived doc sets (#1535)

- config.toml
- themes/kf/layouts/docs/single.html
- themes/kf/layouts/partials/version-banner.html
v0.2 branch: Added logic to create a banner on archived doc sets (cherry-pick of PR https://github.com/kubeflow/website/pull/1535 plus updates specific to this branch).
Preview: https://deploy-preview-1560--eager-nobel-1708cf.netlify.com/docs/about/kubeflow/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1560)
> Kubeflow v0.2 docs: Added logic to create a banner on archived doc sets (#1535)

- content/docs/other-guides/support.md
- content/docs/other-guides/troubleshooting.md
This PR adds a page describing **support options** for customers using Kubeflow v1.0 or later.
This PR is now ready for approval.
Preview: https://deploy-preview-1520--competent-brattain-de2d6d.netlify.com/docs/other-guides/support/
Fixes https://github.com/kubeflow/website/issues/1131
Reference: [Kubeflow v1.0 Docs and Processes Design](https://bit.ly/2OX11vw)
DO NOT MERGE UNTIL v1.0.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1520)
> Added a support page for Kubeflow v1.0.0

- config.toml
* We are now redirecting www.kubeflow.org to the v0.7-branch
this is what users should see until we are ready to publish
the 1.0 docs.
* Related to kubeflow/website#1581
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1585)
> Remove the archived version banner from the v0.7-branch.

- config.toml
- content/docs/gke/customizing-gke.md
Changed relevant version numbers to v1.0 in config, including changing the title of the version menu to **v1.0RC**.
Fixes https://github.com/kubeflow/website/issues/1587
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1589)
> Change version to v1.0RC in label for website menu

- content/docs/gke/gcp-e2e.md
This is necessary b/c the kubeflow namespace, by default, doesn't have sufficient permissions.
Addresses https://github.com/kubeflow/website/issues/1554.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1602)
> change e2e example to update to user profile namespace before tfjob deployment

- content/docs/components/central-dash/overview.md
The central dashboard page is new and therefore didn't get a banner in the first round. Added a banner now.
Preview: https://deploy-preview-1606--competent-brattain-de2d6d.netlify.com/docs/components/central-dash/overview/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1606)
> Added stable banner to central dashboard page

- content/docs/examples/kubeflow-samples.md
- layouts/shortcodes/blocks/sample-section.html
- The sample page now can read the date of the last commit for a reference project. 
- The Kubeflow versions are still not 100% correct but based on `app.yaml` `README` `Comment` a new label shows minimum tested version.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1620)
> Fixes kubeflow/website#1316

- content/docs/gke/deploy/deploy-cli.md
- content/docs/gke/deploy/deploy-ui.md
* See #1571
* Also reformat the existing instructions; break up the big code
block of code setting environment variables into multiple steps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1630)
> Basic Auth should be marked as deprecated for GCP

- content/docs/reference/images.md
Fixing broken links to Dockerfile locations.  Removing jupyterhub link since the code for jupyterhub was previously removed from the repo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1635)
> Fixing broken links to Dockerfile locations (#1293)

- content/docs/openshift/_index.md
- content/docs/openshift/install-kubeflow.md
- content/docs/openshift/uninstall-kubeflow.md
- content/docs/started/getting-started.md
- layouts/shortcodes/config-file-openshift.html
- layouts/shortcodes/config-uri-openshift.html
Adding documentation for deploying Kubeflow 0.7 on OpenShift 4 (specifically tested on 4.2, we'll update it when we re-test on latest 4.3)
This points to our fork of manifest repository, but we plan on proposing the changes to the KF upstream repository and get up to speed with master of the manifests repository, so we will also update that when we have things fixed there.
Resolves: #33 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1636)
> Add KF 0.7 on OpenShift docs content

- content/docs/components/hyperparameter-tuning/experiment.md
Related https://github.com/kubeflow/website/issues/1683.
I fixed some links in Katib documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1690)
> Fix Katib documentation links

- content/docs/ibm/install-kubeflow.md
Currently, in https://www.kubeflow.org/docs/ibm/install-kubeflow/
**Kubeflow installation**
Run the following commands to set up and deploy Kubeflow.
1. Download the kfctl v1.0-rc.4 release from the [Kubeflow releases page](https://github.com/kubeflow/kubeflow/releases/tag/v1.0-rc.4 ).
Follow Kubeflow release page -> 404
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1692)
> Fix broken link to release page

- content/docs/gke/deploy/deploy-cli.md
The `-O` option is used to download the file using the last path component for the name.
This is just a small change to use the small case option which allows you to specify the output file.
Reference: https://curl.haxx.se/docs/manpage.html#-o
Cheers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1698)
> fix: curl short --output to small case

- content/docs/gke/deploy/deploy-cli.md
Because we are using array notation to select the first position in the plugins under spec section, we need to enclose the keypath with ' ' otherwise bash will complain that can't find a match.
For the sake of consistency i have added it to `metadata.name` path.
Reference from yq help: `write       yq w [--inplace/-i] [--script/-s script_file] [--doc/-d index] sample.yaml 'b.e(name==fr*).value' newValue`
Cheers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1699)
> fix: add ' ' to yq command spec keypath

- content/docs/gke/deploy/deploy-cli.md
fix for #1700 
Accordingly to @sarahmaddox this is a copy-paste error .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1703)
> fix: build the configured manifest file instead of the one from the URI

- scripts/validate-urls.py
While working  [issue 1683](https://github.com/kubeflow/website/issues/1683), the current validate-urls.py incorrectly report the following errors (as the urls are truncated):
```
|/community.md | https://calendar.google.com/calendar/embed?src | 400|
|/community.md | https://calendar.google.com/calendar/ical/kubeflow.org_7l5vnbn8suj2se10sen81d9428 | 400|
```
However, inside community.md, the actual/working urls are:
`https://calendar.google.com/calendar/embed?src=kubeflow.org_7l5vnbn8suj2se10sen81d9428%40group.calendar.google.com` 
`https://calendar.google.com/calendar/ical/kubeflow.org_7l5vnbn8suj2se10sen81d9428%40group.calendar.google.com/public/basic.ics `
Use this PR to take care = and % in the urls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> Fix validate urls script: added = and % to HTTP_PATTERN

- content/docs/ibm/install-kubeflow.md
Rename IBM Cloud default cluster name from knative to Kubeflow.
Fixing minor typos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1711)
> Rename IBM Cloud default cluster name to Kubeflow

- content/docs/pipelines/tutorials/api-pipelines.md
This fixes https://github.com/kubeflow/website/issues/734.
Preview at https://deploy-preview-1688--competent-brattain-de2d6d.netlify.com/docs/pipelines/tutorials/api-pipelines/
The tutorial could be easily expanded by adding a section on "How to associate a run with an experiment". But I think this one is a good start.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1688)
> Create minimal usage example for the Pipelines API

- content/docs/aws/deploy/install-kubeflow.md
The command line to remove the load balancer didn't work for me.
The patch corrects it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1716)
> fix 'kubectl delete'

- content/docs/gke/deploy/deploy-cli.md
Believe mkdir -p ${KF_DIR} is in the wrong place in the example. If you following the tutorial you will try to step down to a folder that dosen't exists.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1741)
> updating bash commands in "Deploy using CLI"

- config.toml
Fixes https://github.com/kubeflow/website/issues/1745
Set `archived_version = true`.
This will add a banner at the top of all the v0.7 docs letting users know they are viewing an archived version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1747)
> Marked the v0.7 archive site as archived

- content/docs/ibm/existing-cluster.md
- content/docs/ibm/install-kubeflow.md
the doc referes to
`ibmcloud ks cluster-config` which is deprecated and will soon be unsupported.
`ibmcloud ks cluster config` is recommended.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1752)
> update ibmcloud ks cluster config command

- content/docs/gke/cloud-filestore.md
- content/docs/gke/customizing-gke.md
- content/docs/gke/deploy/delete-cli.md
- content/docs/gke/deploy/deploy-cli.md
- content/docs/gke/deploy/deploy-ui.md
- content/docs/gke/deploy/reasons.md
- content/docs/gke/private-clusters.md
- content/docs/upgrading/upgrade.md
Fixes https://github.com/kubeflow/website/issues/1764
The basic auth (username/password) option on GCP is already marked as not supported in the docs, but we currently give people instructions on how to use it if they want to. This is leading to problems for some, where the option does not work.
Instead, we should just say it's not supported, without giving usage instructions. In addition, we should remove most references to the basic auth config, leaving only the one in the troubleshooting guide.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1765)
> Clarified that GCP basic auth is not supported and removed most references

- content/docs/openshift/install-kubeflow.md
The current installation instruction is not clear on where the kfdef manifest should be and the installation may fail with the issue described here https://github.com/kubeflow/kfctl/issues/260. This PR fixes instructions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1760)
> update openshift installation doc

- content/docs/openshift/install-kubeflow.md
#1760 missed the file path update for `apply` command. This PR fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1771)
> correct file path for apply

- content/docs/pipelines/sdk/sdk-overview.md
Part of fixes for[ issue 1683](https://github.com/kubeflow/website/issues/1683).
In the following page: https://www.kubeflow.org/docs/pipelines/sdk/sdk-overview/
KubeFlow Pipelines basic component build -> https://github.com/kubeflow/pipelines/blob/master/samples/core/component_build/component_build.ipynb
-> 404
Under **4th** "More about the above workflow"
xgboost-training-cm.py->https://github.com/kubeflow/pipelines/blob/master/samples/core/xgboost-spark/xgboost-training-cm.py -> 404
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1768)
> Fixed broken links in pipeline sdk-overview

- content/docs/gke/troubleshooting-gke.md
This is a proposed fix for issue #1568.
I have added a new entry describing the steps on how to troubleshoot the certificate failure provided in the description of [issue](https://github.com/kubeflow/website/issues/1568). 
I also made just a couple of fixes in the section. 
I have a concern about the additional comment by @jlewi to this issue. It sounds too vague for me and most likely needs more detailed investigation and communication with SMEs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1664)
> Adding new section on managed certificates failure

- content/docs/ibm/install-kubeflow.md
IBM Cloud Block storage are recommended to use on RWO storage such as database. Therefore, we want to add the instructions for setting up IBM Cloud Block storage as the default storage class before installing Kubeflow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1753)
> Add block storage instructions to IBM Cloud

- content/docs/pipelines/sdk/output-viewer.md
/assign @joeliedtke 
Documentation for https://github.com/kubeflow/pipelines/pull/3177
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1766)
> [KFP] Introduce inline visualization

- content/docs/fairing/azure/_index.md
The Azure instructions were reusing the AKS cluster's internal service principal. These instructions no longer work reliably and do not follow best practices. I have updated the instructions to create a dedicated Azure service principal for use with Kubeflow Fairing only.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1792)
> Use dedicated service principals on Azure

- content/docs/started/k8s/kfctl-istio-dex.md
Fixes: #1778
Why is this needed?
It saves people a click and gives a sample config to follow during deployment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1779)
> document API Server flags for istio_dex config

- content/docs/ibm/existing-cluster.md
initial link was broken, this one redirects to the correct page
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1795)
> Updating broken link in IBM documentation

- content/docs/about/community.md
The old invitation link had expired. Thanks to @jlewi who provided this new link.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1802)
> Update invitation link to Kubeflow Slack channel

- config.toml
- content/_index.html
- content/docs/other-guides/virtual-dev/getting-started-minikf.md
- content/docs/started/k8s/kfctl-istio-dex.md
We had updated the Slack invitation link, but only on the community
page. This PR fixes 4 more pages that use this link.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1807)
> Update the Slack invitation link

- content/docs/pipelines/sdk/component-development.md
For example, change `{name: Input 1, type: GCSPath, description='Data for Input 1'}` to `{name: Input 1, type: GCSPath, description: 'Data for Input 1'}`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1799)
> Fix YAML dict syntax (use ":" instead of "=")

- content/docs/pipelines/tutorials/api-pipelines.md
fixed a typo in getting `Kubeflow Pipelines API Reference`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1810)
> fixed a typo in getting `Kubeflow Pipelines API Reference`

- content/docs/components/hyperparameter-tuning/experiment.md
Ref: [issue 1683](https://github.com/kubeflow/website/issues/1683)
In https://www.kubeflow.org/docs/components/hyperparameter-tuning/experiment/#metrics-collector
[tf.Event](https://www.tensorflow.org/api_docs/python/tf/Event) -> 404
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1816)
> Fix tf.Event link in hyperparameter-tunning

- content/docs/components/serving/overview.md
- content/docs/components/serving/seldon.md
Ref : [issue 1683](https://github.com/kubeflow/website/issues/1683)
1. In https://www.kubeflow.org/docs/components/serving/overview/#multi-framework-serving-with-kfserving-or-seldon-core
Click [doc](https://docs.seldon.io/projects/seldon-core/en/latest/wrappers/README.html)  --> page does not exist
2. In https://www.kubeflow.org/docs/components/serving/seldon/
[language specific model wrappers](https://docs.seldon.io/projects/seldon-core/en/latest/wrappers/README.html) --> page does not exist
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1818)
> Fixed broken links in serving component

- content/docs/components/serving/overview.md
The example has been removed as we need to update the available tech here. Will add a new link when available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1822)
> Remove onnx link for seldon in overview page

- content/docs/pipelines/sdk/component-development.md
Fixes #1827
https://www.kubeflow.org/docs/pipelines/sdk/component-development/
In build_image.sh
current last line:
docker inspect --format="{{index .RepoDigests 0}}" "${IMAGE_NAME}"
should be
docker inspect --format="{{index .RepoDigests 0}}" "${full_image_name}"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1829)
> Correct image name in docker inspect

- content/docs/pipelines/sdk/component-development.md
`kfp.Client().create_run_from_pipeline_func(my_pipeline, arguuments={})` changed to `kfp.Client().create_run_from_pipeline_func(my_pipeline, arguments={})`.
[kfp.Client.create_run_from_pipeline_func docs for reference](https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.client.html#kfp.Client.create_run_from_pipeline_func)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1830)
> Simple typo fix for SDK example

- content/docs/started/k8s/kfctl-istio-dex.md
Resolves #1782
This PR documents setup of a default StorageClass for on-premise systems with dynamic provisioning for kfctl_istio_dex.yaml configuration based deployments.
- Adds docs to check if on-premise installation has a default StorageClass with dynamic provisioning
-  Setup instructions for default StorageClass with dynamic provisioning
-  Reorganizes Troubleshooting guide and unifies them under one header
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1834)
> Adding StorageClass documentation to istio-dex installation

- content/docs/about/community.md
Just a small fix on the slack channel name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1835)
> Slack Channel name fixed

- content/docs/other-guides/virtual-dev/getting-started-multipass.md
Added documentation links to the next steps of the user guide. I added the multipass docs as well as the microk8s as I thought they might be helpful for people running in this configuration. I can remove if they are not wanted!
Issue: https://github.com/kubeflow/website/issues/1694
> added microk8s links too next steps

- content/docs/ibm/install-kubeflow.md
Per https://www.kubeflow.org/docs/started/k8s/overview/: "Kubeflow does not work on Kubernetes 1.16" (assuming this is the case for 1.17 and 1.18 too).
> Updating cluster config for IBM Cloud

- content/docs/components/training/mpi.md
This blog post provides much more information, including a link to the list of adopters.
> Add link to MPI Operator blog post

- content/docs/components/hyperparameter-tuning/env-variables.md
- content/docs/components/hyperparameter-tuning/experiment.md
- content/docs/components/hyperparameter-tuning/hyperparameter.md
- content/docs/components/hyperparameter-tuning/katib-config.md
- content/docs/components/hyperparameter-tuning/overview.md
I added documentation about Katib config and about all environment variables that can be set in Katib components.
I hope, I added everything.
I am not sure that we need DB_NAME variable, since we support only mysql https://github.com/kubeflow/katib/blob/master/pkg/db/v1alpha3/db.go#L12 @johnugeorge.
/cc @richardsliu @gaocegege @hougangliu
> Add documentation for the Katib config and Katib components env variables

- content/_redirects
- content/docs/other-guides/virtual-dev/_index.md
- content/docs/started/workstation/getting-started-linux.md
- content/docs/started/workstation/getting-started-macos.md
- content/docs/started/workstation/getting-started-minikf.md
- content/docs/started/workstation/getting-started-multipass.md
- content/docs/started/workstation/getting-started-windows.md
- content/docs/started/workstation/minikf-gcp.md
The [section on virtual dev environments](https://www.kubeflow.org/docs/other-guides/virtual-dev/) is misplaced and incomplete. We've moved other docs around in the time since that section was created. The docs in that section belong better with the getting-started docs than in the "further configuration" section.
Eventually we plan to re-org the entire left-hand nav, but for now I think it's best to move the two remaining "virtual dev environment" docs into the getting-started section. 
Fixes https://github.com/kubeflow/website/issues/1856
> Moved virtual env installation guides to getting-started section

- content/docs/components/misc/nuclio.md
In [Nuclio function example](https://www.kubeflow.org/docs/components/misc/nuclio/#nuclio-function-examples), 
[Real-Time Location-Based Recommendations](https://github.com/v3io/tutorials/blob/master/demos/location-based-recommendations/01-generate-stores-and-customers.ipynb)  -> 404
The target notebook is already [deleted](https://github.com/v3io/tutorials/commit/569f73ea94b0162c497c6385699a548c7d4639d1).
> remove Nuclio location-based example

- content/docs/ibm/install-kubeflow.md
In https://www.kubeflow.org/docs/ibm/install-kubeflow/#ibm-cloud-block-storage-setup
The correct command should be 
`kubectl get storageclasses | grep block`
(w/o shell in the front)
> Correct the get storageclass command

- content/docs/examples/videos.md
This is in response to the issue at https://github.com/kubeflow/kubeflow/issues/4904
I have added the videos to the list, in reverse chronological order. I have removed the start times from the URLs, as I think these may have been a mistake.
> Added new videos to the list

- content/docs/gke/private-clusters.md
* Add instructions for mirroring docker images to private repositories
* Fix kubeflow/kubeflow#3210
* Delete instructions under private GKE and just link to the doc issue #1705
* The instructions are outdated. Since managed certificates are used there
should be no reason to need to update iap-ingress.yaml anymore.
* Fix #1811
* Most of the other instructions under the private GKE section are also
very obsolete.
> Private GKE: Document image mirroring

- content/_redirects
The Minikube page has moved to workstation subdirectory. 
Add redirect to avoid 404.
> Added redirect for Minikube

- content/docs/components/serving/overview.md
In https://www.kubeflow.org/docs/components/serving/overview/#multi-framework-serving-with-kfserving-or-seldon-core
[doc](https://docs.seldon.io/projects/seldon-core/en/latest/graph/autoscaling.html) -> Pages does not exist
> Fixed broken link in serving-scaling-hpa

- content/docs/started/workstation/minikube-linux.md
Fixed typo in following sections:
https://deploy-preview-1870--competent-brattain-de2d6d.netlify.com/docs/started/workstation/minikube-linux/#step-2-install-jupyter-notebook
https://deploy-preview-1870--competent-brattain-de2d6d.netlify.com/docs/started/workstation/minikube-linux/#step-3-create-a-docker-id
> Fixed typo in Minikube tutorial

- content/docs/started/workstation/minikube-linux.md
Ref : https://github.com/kubeflow/website/pull/1870
Remove the invalid space between [] and (url) which cause the following in upgraded Hugo and Docsy:
> Remove space between [] and (url)

- .gitignore
- content/docs/components/misc/nuclio.md
The original installation command for Helm does not work on 3.1.2. This PR also adds a bit more details to help people get started.
> Fix Helm installation command

- content/docs/started/workstation/getting-started-multipass.md
Adds a note about the minimum version of Microk8s required to the `Microk8s for Kubeflow` doc
Fixes #1717
> Specify a minimum version of Microk8s

- content/docs/other-guides/troubleshooting.md
Ref : #1870
Remove the invalid space between [] and (url) which cause the [following in upgraded Hugo and Docsy](https://deploy-preview-1870--competent-brattain-de2d6d.netlify.com/docs/other-guides/troubleshooting/#pods-stuck-in-pending-state):
> Remove space between [] and (url) in TroubleShooting

- content/docs/started/k8s/kfctl-k8s-istio.md
Ref issue #1891 
Fixed the format in[ ktctl-k8s-istio](https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/#alternatively-set-up-your-configuration-for-later-deployment) caused by change to Goldmark renderer
> Fixed the format in kfctl-k8s-istio

- content/docs/ibm/iks-e2e.md
Ref issue #1891 
Removed the space between [] (url) caused by the restriction of Goldmark renderer.
In https://www.kubeflow.org/docs/ibm/iks-e2e/#overview-of-iks
> Removed space between [] (url) in ibm iks page

- content/docs/ibm/install-kubeflow.md
In https://www.kubeflow.org/docs/ibm/install-kubeflow/#setting-environment-variables, the cluster_name is in uppercase that don't match the description.
Use this PR to fix the typo in cluster_name to match the description.
> Fixed typo in cluster_name to match the instruction

- content/en/docs/started/k8s/kfctl-istio-dex.md
Ref : issue #1891 
In https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/#alternatively-set-up-your-configuration-for-later-deployment, the numbered list is borken by the new Goldmark renderer:
> Fixed format in kfctl-istio-dex.md

- content/en/docs/other-guides/troubleshooting.md
Ref issue #1891 
Removed the space between [] (url) caused by the restriction of Goldmark renderer.
In https://www.kubeflow.org/docs/other-guides/troubleshooting/#problems-spawning-jupyter-pods
> Removed space between [] (url) in other-guides/troubleshooting

- content/en/docs/reference/mpijob/_index.md
- content/en/docs/reference/mpijob/v1alpha2/_index.md
- content/en/docs/reference/mpijob/v1alpha2/mpi.md
- content/en/docs/reference/overview.md
Part of https://github.com/kubeflow/mpi-operator/issues/217. 
Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>
> Add MPIJob v1alpha2 API reference

- content/en/docs/reference/images.md
In https://www.kubeflow.org/docs/reference/images/
Dockerfile location for **katib/suggestion-nasrl**:
https://github.com/kubeflow/katib/blob/master/cmd/suggestion/nasrl/v1alpha3/Dockerfile
-> 404
This may be caused by recent directory/folder restructure in [PR 1143](https://github.com/kubeflow/katib/pull/1143)
> Fixed broken link for katib/suggestion-nasrl dockerfile

- content/en/docs/about/style-guide.md
In https://www.kubeflow.org/docs/about/style-guide/#style-your-images
page source -> https://raw.githubusercontent.com/kubeflow/website/master/content/docs/gke/deploy/oauth-setup.md
->404
It seems this is caused by restructure of the directory for translation: PR #1909
> Fixed broken link in about/style-guide

- content/en/docs/aws/storage.md
Ref issue #1891 
Removed the space between [] (url) caused by the restriction of Goldmark renderer.
In https://www.kubeflow.org/docs/aws/storage/#amazon-fsx-for-lustre:
> Removed space between [](url) in AWS storage page

- content/en/docs/components/serving/bentoml.md
- content/en/docs/components/serving/overview.md
Add model serving example using BentoML.
[BentoML](https://bentoml.org) is an open-source platform for high-performance ML model serving.
This example demos Kubeflow users another option to deploy their model to Kubeflow enabled Kubernetes cluster.
> [Documentation] Add model serving example using BentoML

- content/en/docs/components/training/tftraining.md
The hyperlink pointed to a non-existing section #deploy-kubeflow which I have changed to point to the appropriate section in Getting Started.
> Fix URL for tutorial to deploy Kubeflow

- content/en/docs/components/training/mpi.md
In https://www.kubeflow.org/docs/components/training/mpi/#installation:
[getting started guide](https://www.kubeflow.org/docs/components/training/mpi/docs/started/getting-started/) -> 404
> Fixed broken url in training/mpi page

- content/en/docs/pipelines/tutorials/sdk-examples.md
Add a pointer for users to find out an example on creating a run from a pipeline version. The code example is on github.
Fixes https://github.com/kubeflow/pipelines/issues/3249
> add a pointer to our example script of creating runs using pipeline

- content/en/docs/ibm/existing-cluster.md
- content/en/docs/ibm/install-kubeflow.md
This PR updates the IBM Cloud deployment instructions as follows:
- Use version 1.0  Kubernetes Services plug-in commands. "This version contains permanent syntax and behavior changes that are not backwards compatible. " (see [changelog](https://cloud.ibm.com/docs/containers?topic=containers-cs_cli_changelog#10))
- Use latest documentation links. The `console.bluemix.net` domain was deprecated and `cloud.ibm.com` is the current domain.
- Remove references to the `CLUSTER_REGION` setting, which no longer applies, as documented [here](https://cloud.ibm.com/docs/containers?topic=containers-regions-and-zones#bluemix_regions)
- Updated recommended k8s version to 16, which at the time of writing is the default on IBM Cloud
I verified that the updated links and commands work as expected using …
> Update IBM Cloud deployment instructions

- content/en/docs/aws/aws-e2e.md
Replacing hardcoded references to v1.0.1 manifests to use hugo shortcodes and point to latest v1.0.2
> Update AWS E2E Example Docs to use Hugo Shortcodes

- content/en/docs/pipelines/installation/standalone-deployment.md
/assign @joeliedtke @rmgogogo 
Fixes https://github.com/kubeflow/pipelines/issues/2767#issuecomment-571881081
As zsh is becoming the default for macos, we should expect more users for zsh. Update the instruction to be zsh compatible. (I'm also using zsh now.)
> Make KFP install command zsh compatible

- content/en/docs/started/k8s/overview.md
We can update the documentation since it seems that Kubeflow 1.0 is
compatible with Kubernetes 1.16.
> State compatibility with Kubernetes 1.16

- content/en/docs/components/hyperparameter-tuning/experiment.md
Part of: https://github.com/kubeflow/katib/issues/1211.
Ref PR: https://github.com/kubeflow/katib/pull/1065.
I added information that it is possible to run Katib Experiment without the `goal`. Also, I I added indent to read doc easier.
/assign @jlewi 
/cc @gaocegege @johnugeorge
> Update doc to run Katib experiment without the goal

- content/en/docs/components/hyperparameter-tuning/experiment.md
- content/en/docs/components/hyperparameter-tuning/katib-config.md
Update katib-config document to describe suggestion service images
Katib issue: https://github.com/kubeflow/katib/issues/1147
cc: @gaocegege @andreyvelich @sarahmaddox
> Update katib-config document to describe suggestion service images

- content/en/docs/components/hyperparameter-tuning/experiment.md
- content/en/docs/components/hyperparameter-tuning/overview.md
Part of https://github.com/kubeflow/katib/issues/1211.
Ref PR: https://github.com/kubeflow/katib/pull/1143.
I renamed NASRL to ENAS, fixed some links to API docs and added algorithm settings for ENAS.
/assign @jlewi 
/cc @gaocegege @johnugeorge
> Rename Katib NAS RL algorithm to ENAS

- content/en/docs/pipelines/tutorials/sdk-examples.md
This PR adds a small example of listing pipelines with a filter. Moreover, since we now have multiple sdk examples on this page, I also added explicit example id.
> Add a small example of listing pipeline with a filter

- content/en/docs/components/feature-store/OWNERS
- content/en/docs/components/feature-store/_index.md
- content/en/docs/components/feature-store/getting-started.md
- content/en/docs/components/feature-store/overview.md
- content/en/docs/reference/version-policy.md
Adds Feast as a component to Kubeflow. This is a first cut of documentation for 1.1
Fixes #1981 
The documentation roughly includes the following sections:
* Feature store concepts and introduction to Feast
* Getting started with Feast
* Reference to Kubernetes installation guide
* How Feast can be used with Kubeflow components
* Links to examples
* Links to other Feast resources
> Add Feast documentation to components

- content/en/docs/reference/version-policy.md
/assign @joeliedtke 
Found a place with outdated kfp version number.
KFP 0.2.5 was used in KF 1.0.2
> docs: Update kfp sdk version

- content/en/docs/about/contributing.md
This PR will address issue: [2006](https://github.com/kubeflow/website/issues/2006)
Added "It is ultimately the PR creator's responsibility to see that the PR gets assigned to appropriate           reviewers and ping reviewers as needed" under "Quirks of the process / Reviewers, and approvers are unresponsive" section.
/assign @jlewi
> update to the PR Owners responsibility

- content/en/docs/gke/deploy/delete-cli.md
- content/en/docs/gke/deploy/delete-ui.md
- content/en/docs/gke/deploy/deploy-cli.md
- content/en/docs/gke/deploy/deploy-ui.md
- content/en/docs/gke/deploy/management-setup.md
Initial docs for blueprints
* Update the CLI instructions to explain how to deploy Kubeflow using
blueprints.
* Add a page for setting up the management cluster
* Add banners to some of the pages that still need to be updated indicating
the docs are out of date.
* Related to kubeflow/website#1960
> Docs for blueprints

- content/en/docs/components/metadata.md
Fixed <img> tags being displayed as raw HTML source instead of displaying the actual image
> Update metadata.md docs to show images

- content/en/docs/pipelines/installation/standalone-deployment.md
Reverts kubeflow/website#2041
/assign @amygdala 
Shall we revert this first before resolving https://github.com/kubeflow/pipelines/issues/4261
> Revert "add namespace warning at top of standalone upgrade section"

- content/en/docs/gke/deploy/management-setup.md
* Instructions should reference the Makefile
* We will now install CNRM in workload identity mode not namespace mode
per kubeflow/gcp-blueprints#13
> Fix management cluster setup instructions

- config.toml
As requested by @jlewi in #1984. 
Followed steps 2 to 4 in [instructions](https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md#updating-version-numbers-etc-for-the-upcoming-release-major-minor-or-patch).
> V1.1 release - Updating version numbers

- content/en/docs/pipelines/installation/overview.md
Reduce confusion in this question on slack: https://kubeflow.slack.com/archives/CE10KS9M4/p1596480791242800
> For instances with managed storage, is it required (or strongly recommended) that we delete the cluster ? Or is it fine to just delete the instance and reinstall into the existing cluster ?
> doc: reduce confusion on reinstall instructions

- content/en/docs/ibm/deploy/install-kubeflow.md
The oidc secret in the IBM multi user doc is not matching with the default oidc secret for the Kubeflow 1.1 release. Thus, updating the doc to have to correct default secret.
Secret reference: https://github.com/kubeflow/manifests/blob/master/stacks/ibm/application/oidc-authservice/kustomization.yaml#L20
> Update oidc auth secret to match the 1.1 release in the IBM multi user doc

- content/en/docs/components/multi-tenancy/getting-started.md
Updated the documentation for the following
1. How to disable self registration
2. Resource quota spec example as part of the create profile sample
3. Add contributors manually
> updated docs for self registration disable, resource quota spec sample, manage contributor manually

- content/en/docs/about/community.md
Also removed link for tf-operator since we will want to start promoting the WG channel instead.
> Add Slack link to WG Trainining channel

- content/en/docs/reference/OWNERS
- content/en/docs/reference/images.md
I added OWNERS file for reference documentation since it contains some info about Training/Katib.
Also I updated Katib images.
/assign @joeliedtke @jlewi
/cc @gaocegege @terrytangyuan @Jeffwan @johnugeorge
> Add OWNERS for reference docs

- content/en/docs/aws/private-access.md
- content/en/docs/other-guides/integrations/data-management.md
- content/en/docs/started/workstation/getting-started-multipass.md
Updated for inclusive language: ~~”Native”~~ → “Built-in”
- Guide: Integrating Kubeflow with Rock guide
- Guide: Microk8s for Kubeflow
- Guide: Creating a private EKS clusters (AWS)
(Source: an a11y presentation by @heyawhite—a Tech Writer at Google)
Thank you
> Update guides on Integrating Kubeflow with Rock, Microk8s on KF, a private EKS (AWS) for inclusive language

- content/en/docs/components/hyperparameter-tuning/env-variables.md
- content/en/docs/components/hyperparameter-tuning/experiment.md
- content/en/docs/components/hyperparameter-tuning/hyperparameter.md
- content/en/docs/components/hyperparameter-tuning/katib-config.md
- content/en/docs/components/hyperparameter-tuning/overview.md
- content/en/docs/reference/katib/v1alpha3/katib.md
All Katib docs should be up to date for 1.1 release from 11th of June, see this: https://github.com/kubeflow/katib/issues/1211.
/cc @gaocegege @johnugeorge @jlewi
> Remove outdated banner for Katib docs

- OWNERS
* Remove jlewi@ as an approver; I will no longer be actively reviewing
miscellaneous doc changes
* Add @Bobgy  as another co-approver
* Add 8bitmp3 and RFMVasconcelos they are reviewing a lot of docs and
working up to becoming approvers
* Prune the reviewers list so that PRs can be better autoassigned. We should
arguably have OWNERs files in all subdirectories and rarely hit root owners
file.
* Alphabetize the reviewers list
> Cleanup the root owners file.

- config.toml
This PR updates Kubeflow docs' `config.toml` so the versions drop down shows the link to the 1.0 docs (v1.1 is the latest) @jlewi . Note that the link points to `https://v1-0-branch.kubeflow.org` (as per https://github.com/kubeflow/website/issues/1984#issuecomment-671375882).
> Add v1.0 to Kubeflow docs config.toml (v1.1 is the latest)

- content/en/docs/gke/OWNERS
I think this better route github reviewers and assignments to related people.
> Create OWNERS for GKE docs

- content/en/docs/gke/deploy/deploy-cli.md
- content/en/docs/gke/deploy/management-setup.md
- content/en/docs/gke/deploy/oauth-setup.md
- content/en/docs/gke/deploy/project-setup.md
/assign @jlewi @joeliedtke 
Fixes https://github.com/kubeflow/website/issues/2123
changes:
* remove mentions of basic authentication
* add missing set-values
* istioctl download doc link update
* add instructions for configuring management cluster context
* `gcloud auth application-default login` is no longer required
* Clarified istioctl should be downloaded from anthos service mesh site
* We should use `kustomize v3.2.1`, later versions have a breaking change
> doc(gcp): fix deploy doc e2e

- content/en/docs/components/hyperparameter-tuning/overview.md
Added particle to change `you need run many training jobs` to `you need **to** run many training jobs`
> Fix typo in overview

- content/en/docs/about/OWNERS
See comment: https://github.com/kubeflow/website/pull/2120#issuecomment-672888785.
@gaocegege @terrytangyuan @johnugeorge @Jeffwan You wouldn't mind to be in the OWNERs file for about section?
/cc @jlewi
> Add OWNERs for about section

- content/en/docs/about/community.md
I added link to AutoML WG Slack channel in community page. 
I think it can be useful.
/assign @joeliedtke @8bitmp3
/cc @jlewi @gaocegege @johnugeorge
> Add link to AutoML WG Slack channel

- content/en/docs/components/hyperparameter-tuning/OWNERS
- content/en/docs/components/hyperparameter-tuning/overview.md
After this PR: https://github.com/kubeflow/katib/pull/1252 we moved SDK for v1alpha3 under `sdk/python/v1alpha3` folder.
I fixed the link on the website to point for correct version.
Also, I added @sperlingxx to the OWNERS for Katib docs since he is helping us with developing.
/assign @sperlingxx @gaocegege @johnugeorge 
/cc @jlewi
> Fix link for v1alpha3 Katib SDK

- content/en/docs/started/k8s/kfctl-istio-dex.md
- content/en/docs/started/k8s/kfctl-k8s-istio.md
- layouts/shortcodes/config-file-istio-dex.html
- layouts/shortcodes/config-file-k8s-istio.html
- layouts/shortcodes/config-uri-istio-dex.html
- layouts/shortcodes/config-uri-k8s-istio.html
Release docs for Kubeflow v1.1: https://github.com/kubeflow/website/issues/1984
> add v1.1 install instructions to vanilla k8s

- content/en/docs/started/OWNERS
This PR adds a second approver in `OWNERS` for the Getting Started section.
Currently, we have 1 approver (@RFMVasconcelos) and no reviewers.
@rmgogogo @joeliedtke @bobgy @animeshsingh - if you would like to volunteer to become, for example, a third approver or a 1st and 2nd reviewer, let us know! Thanks
/assign @rmgogogo @joeliedtke @bobgy @animeshsingh
> Kubeflow Getting Started: add approvers and reviewers to OWNERS

- content/en/docs/ibm/deploy/authentication.md
I went through these steps after the certificate expired, then discovered this fix.
Notice that IBM Cloud will only save renewed certificates stored in `default` namespace, so it will to change the secret name and its namespace when copying it into `istio-system` namespace.
> Fix TLS certificate usage in IBM cloud Kubernetes

- content/en/docs/other-guides/support.md
As Canonical is committed to supporting Kubeflow users, we're enthusiastic about adding our name here to help remove frictions from Kubeflow adoption.
Switched order to be alphabetical, as would be confusing otherwise.
> Adding to Kubeflow support providers

- content/en/docs/started/k8s/overview.md
This PR changes the compatibility status of k8s v1.16 to "compatible". Related issues: https://github.com/kubeflow/website/issues/2178, https://github.com/kubeflow/website/issues/2130, https://github.com/kubeflow/website/issues/2042
@Bobgy We should update the shortcode for incompatible versions (`{{% kubernetes-incompatible-versions %}}`), since it currently says v1.16. 
```
- Kubeflow **does not work** on Kubernetes
{{% kubernetes-incompatible-versions %}}.
```
/assign @Bobgy
> Update Kubernetes v1.16 compatibility status in the Overview of Kubeflow deployment on a k8s cluster guide

- content/en/docs/other-guides/OWNERS
Adding an OWNERS file to Other Guides with @RFMVasconcelos and 8bitmp3 as approvers (the docs people :)), since we don't have an OWNERS file.
Currently, we have the following guides that were mostly created by @jlewi and @sarahmaddox :
- Data management: integrating KF with Rok for data versioning, packaging, and secure sharing: https://github.com/kubeflow/website/blob/master/content/en/docs/other-guides/integrations/data-management.md
- FAQ: https://github.com/kubeflow/website/blob/master/content/en/docs/other-guides/freq-ask-questions.md
- Istio on Kubeflow: https://github.com/kubeflow/website/blob/master/content/en/docs/other-guides/istio-in-kubeflow.md
- Job scheduling: https://github.com/kubeflow/website/blob/master/content/en/docs/other-guides/job-scheduling.md
- Kubeflow on-prem in …
> Kubeflow docs: create an OWNERS file for other guides

- content/en/docs/gke/anthos.md
- content/en/docs/gke/private-clusters.md
* Replace the instructions for private GKE with the instructions from the
repo: https://github.com/kubeflow/gcp-blueprints/blob/master/kubeflow/deploy_private.md
* fix: #1705
> Update the docs for private GKE.

- content/en/docs/ibm/deploy/install-kubeflow.md
For IBM Cloud IKS service, different machines such as classic and VCP have different default storageclass. Also, different Kubernetes version also have different storageclass due to the [recent IKS changes](https://cloud.ibm.com/docs/containers?topic=containers-kube_concepts#default_storageclass). Therefore, we want to parameterize the bash command to create a better user experience
> Parameterize default storageclass for ibm cloud

- content/en/docs/ibm/OWNERS
- content/en/docs/ibm/deploy/OWNERS
This PR adds an OWNERS file with a list of approvers and reviewers for IBM Cloud Kubeflow Deploy docs.
Added by mirroring the OWNERS file in the IBM Cloud folder + adding 8bitmp3:
```
approvers:
- animeshsingh
reviewers:
- adrian555
- animeshsingh
- shawnzhu
- 8bitmp3
```
@Tomcli do you want to be included too?
/assign @animeshsingh 
cc @adrian555 @shawnzhu
> IBM Cloud Kubeflow: Create new OWNERS for Deploy docs, update OWNERS for main docs

- content/en/docs/started/workstation/OWNERS
This PR adds a new separate OWNERS file with approvers and reviewers for Workstation to assist with Issues/PRs in that directory. It's a copy of Getting Started's OWNERS with an addition of @alfsuse .
/assign @RFMVasconcelos
> Create OWNERS for Kubeflow Getting Started Workstation

- content/en/docs/pipelines/sdk/output-viewer.md
This corrects a misleading sentence in the output viewer documentation, where the docs suggest the file name matters, but in reality the artifact name is what matters.
This recreates https://github.com/kubeflow/website/pull/2212 which is experiencing a CI failure that may or may not be an unrelated race condition.
> Correct metadata inaccuracy in the output viewer docs

- content/en/docs/gke/deploy/management-setup.md
Just walked through this - the error has been resolved and doesn't show up anymore and `yq` dependency was missing, copied that from `deploy-cli` page.
> Updated management cluster instructions

- content/en/docs/pipelines/sdk/OWNERS.md
Hi all adding an OWNERS file to the SDK section as suggested by @8bitmp3  in https://github.com/kubeflow/website/pull/2214
Currently proposing as approvers:
- Bobgy
- IronPan
- neuromage
- Ark-kun
- numerology
I can add myself as a reviewer but would prefer someone else with more knowledge on the sdk than me.
> Create OWNERS file for sdk section

- content/en/docs/pipelines/sdk/pipelines-metrics.md
This corrects a misleading sentence in the pipeline metrics documentation, where the docs suggest the file name matters, but in reality the artifact name is what matters. This is similar to https://github.com/kubeflow/website/pull/2212.
Verified on our internal KFP cluster; doc update tested with a local Hugo server:
> Correct requirement inaccuracy in the metrics documentation

- content/en/docs/ibm/existing-cluster.md
- content/en/docs/ibm/iks-e2e.md
Part of efforts to resolve #2177, updated the out-dated links in the documents for Kubeflow running on IBM platforms.
> [IBM] update out-dated links in the docs

- content/en/docs/started/getting-started.md
- content/en/docs/started/kubeflow-overview.md
The entrance for users when they click `Getting started` on Kubeflow.org is the `Installing Kubeflow` page, which appears outdated:
At a first glance, this is more of a gateway, which seems version agnostic. And we're telling ALL users that our main docs page is outdated. It surely has space to improve, but at the current pace, I argue that we should remove the outdated banner and later on create a coordinated effort to update it. 
Same for `Getting Started > Kubeflow Overview`.
@8bitmp3 @jlewi @jbottum what are your thoughts on this?
> Removed "outdated" from version agnostic "Getting started" docs

- content/en/docs/started/k8s/overview.md
This PR updates the _Overview of Deployment on Existing Clusters_ guide (https://www.kubeflow.org/docs/started/k8s/overview/) page by updating the _Minimum system requirements_ section.
It adds a Kubeflow v1.1 column to the Kubernetes compatibility table by replicating the Kubeflow v1.0 column (as per @Bobgy's suggestion).
Tracking issue: https://github.com/kubeflow/website/issues/2264 (and similar)
/assign @Bobgy @joeliedtke @RFMVasconcelos 
Thank you 👍
> Add a Kubeflow v1.1 column to the Kubernetes compatibility table

- content/en/docs/azure/deploy/install-kubeflow.md
- layouts/shortcodes/config-uri-azure.html
- Update azure installation guide to point KFDef manifest for v1.1 for Azure 
[https://github.com/kubeflow/manifests/pull/1487] (url)
CC- @aronchick
> update azure installation guide

- content/en/docs/pipelines/sdk/component-development.md
Updated some phrases in *component-development.md* document to make it more clear pipeline components are language agnostic. 
Based on kubeflow/pipelines#4599 discussion
[Preview Link](https://deploy-preview-2294--competent-brattain-de2d6d.netlify.app/docs/pipelines/sdk/component-development/)
> Make component development doc more language agnostic

- content/en/docs/about/community.md
- Fix broken links for the WG AutoML and WG Training on the community page
- Clean up slack URL for the working group for consistent URL across all slack urls
> Fix broken links for community page topics

- content/en/docs/pipelines/installation/localcluster-deployment.md
Apparently, in the last rework, we deleted the port-forward section that helps folks to be able to use the pipelines UI.
/assign @8bitmp3 /cherry-picking
> [docs:] Fix missing port-foward URL

- content/en/docs/notebooks/OWNERS
This adds the Notebook Working Group Leads as OWNERS for the Notebook docs.
> Add Notebook WG leads to OWNERS

- content/en/docs/gke/custom-domain.md
Recently, I made a PR to change the section about using your own domain. But I realized that I missed a phrase that mentions kfctl, I understood that as a kind of typo. In this PR I'm changing this phrase to remove the old kfctl reference.
> typo - using your own domain section

- content/en/docs/azure/authentication-oidc.md
- Adding steps to verify the redirect url to be the same as specified in the AAD app, otherwise the authentication would complain. 
- Lint the yaml file to be the same as in the autherservice, i.e. edit the json file to better reflect the structure.
> Update Azure OIDC guidance to verify statefulset and also lint the yaml to be the same as the autherservice

- content/en/docs/ibm/deploy/authentication.md
- content/en/docs/ibm/deploy/install-kubeflow.md
Fixes #2182
Notice this PR depends on https://github.com/kubeflow/manifests/pull/1594
> Uses AppID for multi-user installation on IKS

- content/en/docs/pipelines/sdk/install-sdk.md
- content/en/docs/pipelines/sdk/pipelines-with-tekton.md
- content/en/docs/pipelines/sdk/sdk-overview.md
Add documentation about the Kubeflow Pipelines SDK for Tekton. The `kfp-tekton` SDK allows users to run Kubeflow Pipelines on a Tekton backend.
You can find more information about the `kfp-tekton` project on GitHub: https://github.com/kubeflow/kfp-tekton
For more details about the project, including demos, please look at these [slides](https://www.slideshare.net/AnimeshSingh/kubeflow-pipelines-with-tekton-236769976) and the [deep dive presentation](https://www.youtube.com/watch?v=AYIeNtXLT_k).
@animeshsingh
> Document the Kubeflow Pipelines SDK for Tekton

- content/en/docs/ibm/deploy/install-kubeflow.md
- content/en/docs/ibm/iks-e2e.md
- content/en/docs/ibm/pipelines.md
This PR covers:
1. Update the ibm/pipelines.md instructions to cover the end to end experience on how to use kfp-tekton SDK.
2. Update deployment URL to use the stable v1.2.0 release that get cherrypicked earlier today.
3. Remove deprecated workaround on notebook server since it's already fixed.
> Update IBM docs with better KFP instructions

- content/en/docs/components/katib/experiment.md
Fixes: https://github.com/kubeflow/katib/issues/1310.
Blocked by: https://github.com/kubeflow/website/pull/2312.
I added doc about `metricStrategies` in Objective section.
/assign @johnugeorge @gaocegege 
/cc @8bitmp3
> Add Katib metric strategies info

- content/en/docs/components/katib/experiment.md
Fixes: https://github.com/kubeflow/katib/issues/1286.
Blocked by: https://github.com/kubeflow/website/pull/2312.
I added information about default values for `parallelTrialCount` and `maxTrialCount`. Other default values we will explain in a appropriate PRs.
/assign @gaocegege @johnugeorge 
/cc @8bitmp3 @RFMVasconcelos
> Default values for Katib Trials count

- content/en/docs/components/feature-store/getting-started.md
Some of the links have changed to Feast documentation. This PR corrects those broken links.
> Update links to Feast documentation

- content/en/docs/started/k8s/overview.md
Add the DVP requirement (by @swiftdiaries https://github.com/kubeflow/website/pull/2195)
```
- You need a default
[StorageClass](https://kubernetes.io/docs/concepts/storage/storage-classes/)
with a [dynamic volume
provisioner](https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/).
For more information, refer to [this
guide](https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/#before-you-start).
```
+ Minor linting
Thank you 👍
> Add the dynamic volume provisioner requirement to the K8s cluster KF doc overview; minor linting

- content/en/docs/aws/deploy/install-kubeflow.md
Since AWS enabled E2E periodic tests starting from Kubeflow 1.2, creating documentation to keep track compatibility matrix between EKS and Kubeflow versions.
> Add AWS Compatibility Matrix between EKS and Kubeflow versions

- content/en/docs/gke/deploy/deploy-cli.md
Valuable but hidden information. I think the description of the steps should be referred to from the top if not entirely moved there.
> Refer to the section where the deployment steps are described

- content/en/docs/gke/deploy/management-setup.md
Without kubectl the step `make create-context` in the management cluster creation fails.
> Install kubectl using gcloud components

- content/en/docs/gke/deploy/management-setup.md
ERROR: (gcloud.beta.anthos.apply) unrecognized arguments: -f
> Remove -f argument from gcloud beta anthos apply

- content/en/docs/gke/pipelines/authentication-pipelines.md
- content/en/docs/ibm/using-icr.md
- content/en/docs/pipelines/multi-user.md
- content/en/docs/pipelines/reference/sdk.md
- content/en/docs/pipelines/sdk/enviroment_variables.md
- content/en/docs/pipelines/sdk/install-sdk.md
- content/en/docs/pipelines/sdk/manipulate-resources.md
- content/en/docs/pipelines/sdk/parameters.md
- content/en/docs/pipelines/sdk/python-function-components.ipynb
- content/en/docs/pipelines/sdk/python-function-components.md
- content/en/docs/pipelines/sdk/sdk-overview.md
Update docs that still refer to KFP latest SDK reference.
https://github.com/kubeflow/pipelines/issues/4685
> fix(doc): update docs that still refer to KFP latest SDK reference. Fixes kubelow/pipelines#4685

- content/en/docs/ibm/deploy/install-kubeflow.md
We are seeing some users with zero Kubernetes experiment having trouble to access Kubeflow, so we want to add some troubleshooting to improve the user experience.
> [IBM] Add some common troubleshooting on the IBM deployement for non-k8s users

- content/en/docs/aws/deploy/install-kubeflow.md
- content/en/docs/azure/deploy/install-kubeflow.md
- content/en/docs/ibm/deploy/install-kubeflow.md
I have added a note in AWS, AZURE, and IBM kubeflow installation docs regarding the installation of kfctl on windows using WSL as it is available for Linux and macOS users.
> Fixed Documentation regarding installation of kfctl on windows using WSL

- content/en/docs/ibm/deploy/authentication.md
This PR fixes the `kubeflow-gateway` YAML in the IBM authentication doc and removes any trailing whitespace from lines.
Closes: #2393
> [IBM] Fix formatting in HTTPS doc

- content/en/docs/aws/notebook-server.md
Update AWS Notebook Image from tag from `1.1.0` to `1.2.0`
> [AWS] Update AWS Notebook Image to v1.2.0

- content/en/docs/gke/deploy/project-setup.md
The '1. Initialize your project to ready it for Anthos Service Mesh installation' step requires the following steps done:
1. meshconfig.googleapis.com be enabled, thus added in line 45.
2. export the PROJECT_ID variable, added in line 70-72.
Otherwise, will get the following errors:
Without PROJECT_ID defined:
```
<!DOCTYPE html>
<html lang=en>
<meta charset=utf-8>
<meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
<title>Error 404 (Not Found)!!1</title>
<style>
*{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px …
```
> Update project-setup.md solve installation issues

- content/en/_redirects
Blogs have been migrated to https://blog.kubeflow.org/.
> Redirect blog to the new location instead of Medium

- content/en/docs/gke/deploy/management-setup.md
Align the variable names and notes for a better Setting up a management cluster experience.
The `${PROJECT}` variable seems to have the same usage as `${MGMT_PROJECT}`, thus aligned with `${MGMT_PROJECT}`.
Also, combined the description and notes of `${MGMT_NAME}` to line 69-79.
Moved `${LOCATION}` definition to line 87.
> Update management-setup.md in Management cluster setup

- layouts/shortcodes/config-file-istio-dex.html
- layouts/shortcodes/config-file-k8s-istio.html
- layouts/shortcodes/config-uri-istio-dex.html
- layouts/shortcodes/config-uri-k8s-istio.html
Documentation for installation via K8s needs update to v1.2 as all URLs point to 1.1
> Update istio documentation to branch 1.2 for Kubeflow v1.2

- content/en/docs/upgrading/_index.md
Follow up of https://github.com/kubeflow/website/pull/2275
Delete top level upgrade guide
/assign @8bitmp3 
Fixes https://github.com/kubeflow/website/issues/2429
> docs: delete upgrading/_index.md

- content/en/docs/gke/deploy/deploy-cli.md
Replace 'management' with 'kubeflow' to describe KF_DIR env. variable, as correctly described just above there.
> Fix KF_DIR env. var. description

- content/en/docs/gke/deploy/deploy-cli.md
- content/en/docs/gke/deploy/management-setup.md
Adding yq version `3.3.0` that worked while following the installation steps as opposed to 4.x which had made a lot of changes which were incompatible
Reason: `yq `version 4.2.1 getting an error that is `Error: unknown command "r" for "yq"`
Fixed after switching to 3.x (see discussion of other people repro below)
---
Below is outdated
`KF_DIR` refers to the Kubeflow directory, which is also confirmed in the docs a few paragraphs after this, and is different from the "management cluster directory" which the current wording on the doc says it is.
> Add yq version in docs

- content/en/docs/notebooks/_index.md
> Rename "Jupyter Notebooks" to "Notebook Servers"

- content/en/docs/about/community.md
The old Join Slack link has expired, updated with fresh link
> Update join Slack link

- content/en/docs/ibm/create-cluster.md
- content/en/docs/ibm/deploy/authentication.md
- content/en/docs/ibm/deploy/deployment-process.md
- content/en/docs/ibm/deploy/install-kubeflow-on-IBM-openshift.md
- content/en/docs/ibm/deploy/install-kubeflow-on-iks.md
- content/en/docs/ibm/deploy/uninstall-kubeflow.md
- Update kubeflow installtion docs for ibm openshift
- reorganize kfctl installation and deployment process to a separate file to remove duplication
- move `uninstall-kubeflow` instruction from installation steps to remove redundancy
- change link that pointed to uninstalling step on kubeflow install step to point to `uninstall-kubeflow` page
- fix a markdown formatting issue in `ibm/create-cluster.md` file
> [IBM] update ibm docs for openshift

- content/en/docs/aws/aws-e2e.md
Updated kfserving to the latest stable version to avoid the following error: failed calling webhook "inferenceservice.kfserving-webhook-server.defaulter": x509: certificate signed by unknown authority.
Updated paths to model yaml files to avoid 404s
> Update aws-e2e.md to resolve 404s on model yaml files and update kfserving version to resolve x509 error

- scripts/add_outdated_banner.py
Checks that there is actual content after front matter section when adding outdated banner to docs. Treats docs with only "strippable" characters after the front matter section as having no content.
> Add more robust check for empty doc pages

- content/en/docs/openshift/install-kubeflow.md
The link for "See how to upgrade Kubeflow" in 
https://www.kubeflow.org/docs/openshift/install-kubeflow/ is invalid.
As the link was removed by 93dd06a4985828f669c322f807a59bf6f295db57
this patch removes the link as well.
> Remove deprecated link for upgrading/upgrade/

- content/en/docs/components/multi-tenancy/getting-started.md
`nvidia.com/gpu: "1"` actually doesn't work.
`requests.nvidia.com/gpu: "1"` works well.
https://kubernetes.io/docs/concepts/policy/resource-quotas/#resource-quota-for-extended-resources
> Fix resourceQuotaSpec with GPU

- content/en/docs/gke/deploy/oauth-setup.md
The GCP IAP instructions don't clearly specify that the IAP-secured Web App User IAM role must be granted to intended users of the Kubeflow console. Added a link to 'Next steps' on the GCP IAP docs page to make this clear.
> Add link on user IAM changes to IAP on GCP docs.

- content/en/docs/started/k8s/overview.md
This PR adds Kubernetes 1.19 and 1.20 to the table. This PR does create 2 new issues:
1. The recommended version of Kubernetes is still stated as 1.14, even though the bundled cert-manager is not compatible and it is old. 
2. What is the process to verify 1.17 to 1.20 so that they can be listed as compatible?
/cc @yanniszark
> Add newer k8s versions, cert-manager incompatibility <1.16

- content/en/docs/azure/deploy/install-kubeflow.md
The Azure stack does not add functionality needed for deployment to Azure in the single user use case. To avoid duplication in documentation and to ensure faster updates we will refer to the standard / vanilla kubernetes deployment files for the single user use case.
> Azure: Update single-user deployment

- content/en/_redirects
Fixes issue where the `/docs/pipelines/concepts/*` redirect rule was not applied because these redirects were caught by the `/docs/pipelines/*` rule.
> Small update to pipelines redirects

- content/en/_redirects
We removed the page in #2527, the redirect is no longer needed.
cc @DavidSpek
> Remove unnecessary redirect

- content/en/docs/ibm/create-cluster.md
- content/en/docs/ibm/deploy/install-kubeflow-on-iks.md
The IKS with classic VM is getting group ID support for the file storage on Kubernetes 1.17+. Since file storage will continue to be the default for classic VM, we will change the recommended classic VM storage to `ibmc-file-gold-gid` to minimize maintenance support.
For OpenShift and other types of VM, block storage is the default and we don't need any extra instructions to configure it.
> Update IBM storage config

- content/en/docs/components/katib/katib-config.md
Fixes: https://github.com/kubeflow/katib/issues/1398.
I added info about `waitAllProcesses` flag to the doc.
/cc @robbertvdg @gaocegege @johnugeorge @RFMVasconcelos
> Add waitAllProcesses flag to Katib config

- content/en/docs/reference/images.md
Blocked by: https://github.com/kubeflow/katib/pull/1457.
I fixed links for the recent Katib images.
/cc @gaocegege @johnugeorge @RFMVasconcelos
> Modify Katib links for cert-generator and pytorch-mnist image

- content/en/docs/components/katib/env-variables.md
- content/en/docs/components/katib/hyperparameter.md
- content/en/docs/components/katib/katib-config.md
- content/en/docs/components/katib/trial-template.md
Blocked by: https://github.com/kubeflow/katib/pull/1464.
We changed our Katib manifest structure, I made appropriate changes in the links.
> Modify links for the Katib manifests

- content/en/docs/components/katib/katib-config.md
Related to: https://github.com/kubeflow/katib/blob/master/pkg/util/v1beta1/katibconfig/config.go#L130.
I added info about `persistentVolumeReclaimPolicy` for the Suggestion's PV.
/cc @gaocegege @johnugeorge @RFMVasconcelos
> Add Katib config PV reclaim policy

- OWNERS
I would like to nominate @RFMVasconcelos as an approver for `kubeflow/website` in recognition of his significant contributions, and with him being the most active committer to the docs.
NOTE: the other diffs are removing some random spaces at the end of the lines
> Add RFMVasconcelos to OWNERS/approvers

- content/en/docs/components/pipelines/sdk/pipelines-with-tekton.md
The link https://github.com/kubeflow/kfp-tekton/sdk is 404 for me believe it should be  https://github.com/kubeflow/kfp-tekton/tree/master/sdk
> update broken link

- content/en/docs/gke/gcp-e2e.md
- content/en/docs/ibm/iks-e2e.md
- content/en/serving.svg
The links to https://www.tensorflow.org/serving/ gives me a 404 believe it should be https://www.tensorflow.org/tfx/guide/serving.
> UPDATE fix broken links to tensoflorw serving

- content/en/docs/distributions/kfctl/_index.md
Looking at the current distributions list, I believe that kfctl should always be the first on the list, as it is the community endorsed method.
> Make kfctl first distribution

- content/en/docs/distributions/aws/_index.md
- content/en/docs/distributions/azure/_index.md
- content/en/docs/distributions/charmed/OWNERS
- content/en/docs/distributions/charmed/_index.md
- content/en/docs/distributions/charmed/install-kubeflow.md
- content/en/docs/distributions/gke/_index.md
- content/en/docs/distributions/ibm/_index.md
As we organize the list of [available distributions of Kubeflow](https://master.kubeflow.org/docs/distributions/), on Canonical's side, we're happy to list the work we've been doing to provide an open-source day-2 story for Kubeflow and hence solve some of the known issues with operating Kubeflow with `kfctl` or alternative tooling.
Thank you @knkski for all the great work that has allowed this contribution to happen :tada: 
With this listing, we aim at solving the problem of many users expressed in the community slack, in a way that is respectful to other members of the community with alternative tooling.
> Add Charmed Kubeflow Operators to list of available Kubeflow distributions

- content/en/docs/distributions/ibm/pipelines.md
Made the following changes to the instructions for setting
up the pipelines SDK for single-user.
* append '/pipeline' to the host string
* add client.list_experiments to make sure the setup is working,
consistent with the multi-user example in section 2
* add a note about KUBEFLOW_PUBLIC_ENDPOINT_URL since the user
may or may not have exposed the endpoint as a LoadBalancer
Signed-off-by: Chin Huang <chhuang@us.ibm.com>
> IBM Cloud docs: update pipelines SDK setup for single-user

- content/en/docs/components/training/mpi.md
- content/en/docs/components/training/mxnet.md
@andreyvelich this tackles your [comment](https://github.com/kubeflow/website/pull/2584#pullrequestreview-627989055).
> Remove "outdated" banners from MPI + MXnet operators

- content/en/docs/components/pipelines/overview/concepts/run.md
Current link is broken: https://www.kubeflow.org/docs/components/pipelines/concepts/run-trigger/
Updated link: https://www.kubeflow.org/docs/components/pipelines/overview/concepts/run-trigger/
> Fix broken url link

- content/en/docs/started/getting-started.md
Canonical is standardizing Charmed Operators naming across industries and projects for simplicity.
@knkski could you PTAL
> Updating naming to fit latest naming convention

- content/en/docs/about/kubeflow.md
This is an effort to fix #2618  The only place the expression "An error occurred." occurs on the page is inside the <noscript> tag for the embedded video. 
My theory is that either:
1. Google is attempting to find a better title for this page than a title that is exactly the same as the domain name (the current title) and ended up using the `<h1>An error occurred.</h1>` inside the <noscript> tag. 
2. There was a transient error when Google crawled the page.
In either case, I think these changes slightly improve the page and should encourage Google to reindex the page.
We should also directly request a re-index from the Google Search Console.
cc: @RFMVasconcelos
> change title of page and video to Introduction to Kubeflow

- content/en/docs/components/katib/experiment.md
In https://github.com/kubeflow/katib/pull/1519, I added two options for CMA-ES suggestion service.
I will make this ready for review after https://github.com/kubeflow/katib/pull/1519 is merged.
cc: @andreyvelich
> Update Katib doc for restarting strategies of CMA-ES

- content/en/docs/components/pipelines/sdk/component-development.md
Revises the guide to building reusable components:
- Updates wording to clarify that this is how to build Kubeflow Pipeline Components (instead of a type of reusable pipeline component).
- Updates the guide to use a single example throughout the doc
- Updates the wording in general.
> KFP - Updates guide to building components

- content/en/docs/distributions/ibm/deploy/install-kubeflow-on-iks.md
This PR fixes broken HREFs to section "Expose the Kubeflow endpoint as a LoadBalancer".
> Fix in-document load balancer HREFs

- content/en/_index.html
The link to Nuclio on index.html is broken, so this PR points it to the right location.
> Fix Nuclio link

- content/en/docs/external-add-ons/feature-store/getting-started.md
current link is dead. I Propose adding this link for getting Feast installed on Kubernetes: https://docs.feast.dev/v/v0.6-branch/getting-started/deploying-feast/kubernetes
> Fixing dead link

- content/en/docs/distributions/charmed/install-kubeflow.md
The documented patch was only required in v1.2, we can now remove it from this docs page. 
@DomFleischmann can you ptal?
> Patch no longer needed in v1.3

- content/en/docs/distributions/gke/deploy/management-setup.md
The file directory changed in [`kubeflow/gcp-blueprints`](https://github.com/kubeflow/gcp-blueprints/tree/master/management/managed-project)
https://github.com/kubeflow/gcp-blueprints/tree/master/management/managed-project
> FIX: minor link fix for managed project

- content/en/docs/components/pipelines/sdk/sdk-overview.md
This update removes references to old ways of building components and pipeline steps, and replaces it with a short summary that links to the docs on building pipelines and components.
> Updates the KFP SDK overview

- content/en/docs/distributions/gke/pipelines/authentication-pipelines.md
I accidentally made a cluster called `cluster-name` due to copy-paste, oops!
> Make changeable name more obvious

- content/en/docs/components/pipelines/sdk/v2/build-pipeline.md
Fix a typo on sample code for Kubeflow Pipelines.
> Fix typo: vs ==> v2

- content/en/docs/components/pipelines/sdk/v2/v2-compatibility.md
Fixes https://github.com/kubeflow/pipelines/issues/5691
Preview: https://deploy-preview-2730--competent-brattain-de2d6d.netlify.app/docs/components/pipelines/sdk/v2/v2-compatibility/#current-caveats
> doc(kfp): introduce v2 compatible mode current caveats and requirements

- content/en/docs/external-add-ons/feature-store/getting-started.md
* This is a fix for issue: https://github.com/kubeflow/website/issues/2718.
* Updated all broken links with most recent links from Feast.
* Examples link is still broken on Feast website (https://github.com/feast-dev/feast/tree/master/examples), so haven't updated it.
> PR for #2718: Update Feast related broken links on Kubeflow External Add-ons page

- content/en/docs/components/pipelines/sdk/v2/component-development.md
- After https://github.com/kubeflow/pipelines/pull/5665, we now treat `bool`, `dict`, and `list` as parameters as well.
> Update component-development.md for which types are treated as parameters instead of artifacts

- content/en/docs/components/pipelines/sdk/install-sdk.md
Updated a link in the install Pipeline SDK page to create components and pipeline from Kubeflow Pipelines SDK.
#2780
> Resolved broken link issue for pipeline sdk

- content/en/docs/components/pipelines/sdk/output-viewer.md
The link to table visualization image was not correct before.
> fix(pipelines): image reference path correction

- content/en/docs/components/katib/katib-config.md
Fixes: https://github.com/kubeflow/katib/issues/1565.
Blocked by: https://github.com/kubeflow/katib/pull/1564.
User can disable container CPU and Memory from the Katib config.
/cc @gaocegege @johnugeorge @sravi999 @RFMVasconcelos
> Update empty resources in Katib config

- content/en/docs/started/installing-kubeflow.md
IBM Cloud Kubeflow docs has been on 1.3 since release. This is just to update the getting started page to the correct version.
> [IBM] update kubeflow version to 1.3 in getting started

- content/en/docs/components/katib/experiment.md
Update Katib documentation for Sobol's quasirandom sequence support (refs https://github.com/kubeflow/katib/pull/1523).
cc: @andreyvelich
> Update Katib doc for Sobol's quasirandom sequence support

- content/en/docs/distributions/ibm/deploy/deployment-process.md
kfctl does not have a release for 1.3 (there has not been any changes since 1.2 release). In IBM Docs we were pointing to kf-latest-version which now returns 404. Hardcoding to 1.2 so the link is not broken.
> [IBM] fix kfctl url in ibm docs

- content/en/_redirects
The Kubeflow Pipelines UI has a link to `/docs/pipelines/sdk/build-component`. This URL has been changed to `/docs/components/pipelines/sdk/build-pipeline`. This change adds redirects to fix links to this doc.
> Adds redirect for pipelines/sdk/build-component

- content/en/docs/components/katib/experiment.md
- content/en/docs/components/katib/overview.md
- content/en/docs/components/katib/trial-template.md
Fixes: https://github.com/kubeflow/katib/issues/1604.
Blocked by: https://github.com/kubeflow/katib/pull/1605.
We recently added support for XGBoostJob and Argo Workflows in Katib.
I updated corresponding docs.
/assign @RFMVasconcelos @gaocegege @johnugeorge
> Add Support for Argo and XGBoostJob in Katib

- content/en/docs/components/central-dash/_index.md
- content/en/docs/reference/version-policy.md
I got the following error using hugo v0.87.0 to compile the website
> Error: Error building site: "/home/gongyuan_kubeflow_org/github/kf/website/content/en/docs/components/central-dash/_index.md:4:11": unmarshal failed: toml: expected newline but got U+0035 '5'
with this PR, they are fixed
> fix: compatibility with hugo v0.87.0

- content/en/docs/components/pipelines/installation/choose-executor.md
- content/en/docs/components/pipelines/installation/standalone-deployment.md
Part of https://github.com/kubeflow/pipelines/issues/5718
Preview page: https://deploy-preview-2857--competent-brattain-de2d6d.netlify.app/docs/components/pipelines/installation/choose-executor/
> docs(kfp): choose a workflow executor. Part of kubeflow/pipelines#5718

- content/en/docs/components/katib/trial-template.md
Fixes: https://github.com/kubeflow/katib/issues/1612.
We changed our Trial template label.
/assign @kubeflow/wg-automl-leads @RFMVasconcelos
> Modify Katib Trial templates label

- content/en/docs/distributions/gke/deploy/deploy-cli.md
I've tested that Kustomize 4.2.0 (the latest that the installation script pulls) works with Kubeflow 1.3.1. However, it is possible that not all paths would work. For example, some of the scripts use `--load_restrictor` instead of `--load-restrictor`. For the outlined steps Kustomize 4.2.0 works fine, though this is not mentioned anywhere. (The impression is that the user should use Kustomize 3.2.0 which didn't work for me)
> Add specific version of Kustomize that works

- content/en/docs/components/pipelines/installation/standalone-deployment.md
The file itself moved from `manifests/kustomize/base/kustomization.yaml` to `manifests/kustomize/base/installs/generic/kustomization.yaml` but also the `inverse-proxy` component moved from base to gcp in 91c323900435cd3013549894e4afd8ed14523407.
> Fix broken kustomization.yaml link

- content/en/docs/components/training/mpi.md
- content/en/docs/components/training/mxnet.md
- content/en/docs/components/training/pytorch.md
- content/en/docs/components/training/tftraining.md
I fixed some problems mentioned in these PRs: https://github.com/kubeflow/website/pull/2918, https://github.com/kubeflow/website/pull/2917.
Also, I modified docs to be consistent across Training Operators.
I used direct link for the examples, so users don't need to clone the repo.
Please take a look @kubeflow/wg-training-leads @RFMVasconcelos
> Fix docs for Training Operators 1.3

- content/en/docs/distributions/microk8s/kubeflow-on-microk8s.md
Update MicroK8s install instructions, as current 'latest' version( 1.22) of Kubernetes  is not supported by Kubeflow
> Add versions to MicroK8s install

- content/en/docs/external-add-ons/feature-store/getting-started.md
This PR fixes the broken links on the Feast / Feature Store getting-started page, and updates the installation guide.
> Update feast documentation and links

- content/en/docs/components/training/xgboost.md
1. Add the name of 'XGBoost' crd in title
2. Add command to fetch pods explicitly in 'kubeflow' namespace
These changes are aimed to improve the readability of the XGBoost page
and also to catch up with latest doc changes of others like MXNet,
pytorch
> Update docs for XGBoost

- content/en/docs/components/training/mxnet.md
page - https://www.kubeflow.org/docs/components/training/mxnet/
> fix typo in the MXNET training operator page

- content/en/docs/components/katib/hyperparameter.md
- content/en/docs/components/katib/overview.md
- content/en/docs/reference/images.md
Fixes: https://github.com/kubeflow/katib/issues/1668.
This PR: https://github.com/kubeflow/katib/pull/1667 removes components guide from the README, we should add it in the Kubeflow guides.
@tenzen-y I am not sure that we need to mention `kustomize` in the installation guides, as we discussed here: https://github.com/kubeflow/katib/pull/1667#issuecomment-921109438.
I noticed that Kubeflow Pipelines also uses `kubectl apply -k`: https://www.kubeflow.org/docs/components/pipelines/installation/standalone-deployment/#deploying-kubeflow-pipelines.
More advance users can always clone the Katib repo and use `kustomize` to modify our manifests before installation, we can explain it in the [developer guide](https://github.com/kubeflow/katib/blob/master/docs/developer-guide.md).
What do you think …
> Katib: Add components guide

- content/en/docs/distributions/ibm/OWNERS
- content/en/docs/distributions/ibm/deploy/OWNERS
@yhwang will be the new IBM doc reviewer to replace Moficodes
> Add yhwang as the IBM doc reviewer

- content/en/docs/components/katib/early-stopping.md
- content/en/docs/components/katib/experiment.md
- content/en/docs/components/katib/hyperparameter.md
- content/en/docs/components/katib/overview.md
- content/en/docs/components/katib/resume-experiment.md
- content/en/docs/components/katib/trial-template.md
This PR: https://github.com/kubeflow/katib/pull/1691 introduces the new structure for Katib examples.
I made the appropriate doc changes.
/assign @gaocegege @johnugeorge @shannonbradshaw @kimwnasptd
> Katib: Fix links for all examples

- content/en/docs/components/pipelines/sdk/connect-api.md
To address the comments in https://github.com/kubeflow/website/pull/2905:
* Process about process of AuthN and AuthZ
* Cross-namespace section title
* ServiceAccountToken explanation.
* Overall doc structure.
cc @bartgras @shuesc1
> pipelines: Follow up on connecting to KFP in multi-user mode.

- content/en/docs/distributions/aws/customizing-aws/rds.md
Existing command was wrong
```
$ aws ec2 describe-vpcs \
>     --filters Name=tag:alpha.eksctl.io/cluster-name,Values=$AWS_CLUSTER_NAME \
>     | jq -r '.Vpcs[].VpcIdaws ec2 describe-vpcs \
>     --filters Name=tag:alpha.eksctl.io/cluster-name,Values=$AWS_CLUSTER_NAME \
>     | jq -r '.Vpcs[].VpcId''
jq: error: syntax error, unexpected IDENT, expecting $end (Unix shell quoting issues?) at <top-level>, line 1:
.Vpcs[].VpcIdaws ec2 describe-vpcs \                 
jq: 1 compile error
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
```
New command
```
$ aws ec2 describe-vpcs \
>     --filters Name=tag:alpha.eksctl.io/cluster-name,Values=$AWS_CLUSTER_NAME \
> | jq -r '.Vpcs[].VpcId'
vpc-0xxxxxxxxxxxxxx
```
> Fixing the VPC Id retrieval command

- config.toml
- layouts/partials/head.html
- layouts/partials/navbar.html
- layouts/partials/sidebar-tree.html
__This PR improves the header navigation bar:__
- adds icons beside the links (for example, the GitHub logo beside the GitHub link)
- the text for the version selector dropdown now says "Website Version" when you have not picked a specific version
- orders the "Website Version" in descending order (so the newest ones are at the top)
- removes the "What is Kubeflow?" link, for two reasons:
1. The page it links to is extremely out of date (and doesn't really answer the question)
2. Its presence significantly increases the size of the header (making it look bad on mobile)
> improve navigation bar

- content/en/docs/components/pipelines/overview/pipelines-overview.md
- content/en/docs/components/pipelines/sdk/manipulate-resources.md
`argo workflow` repo got renamed from `argo` to `argo-workflows` earlier this year.
This PR fixes the remaining link that pointed to the old URL
> fix: update argo-workflow links

- content/en/docs/components/pipelines/installation/standalone-deployment.md
N1 machine is costly and about to be deprecated. We are recommending to use new machine type.
Reference: https://cloud.google.com/compute/docs/general-purpose-machines#e2_machine_types
> pipelines: update image to use for standalone

- content/en/docs/started/kubeflow-examples.md
Before we clean up the examples repository, make sure we deliver the right message to users that there are out-of-date examples in this repo.
> examples: Put on warning for out-of-date examples

- content/en/docs/components/multi-tenancy/getting-started.md
This reverts commit af22175be74938e6290d2fb2abf24c7150e71951.
This is because #2934 renames `AuthorizationPolicy` to `AuthenticationPolicy`, which is obviously not correct, as a `AuthenticationPolicy` resource kind does not exist.
> Revert "Update getting-started.md (#2934)"

- content/en/docs/components/katib/experiment.md
Related: https://github.com/kubeflow/katib/pull/1755.
This fixes Metrics Collector regex.
/assign @kubeflow/wg-automl-leads @anencore94
> Katib: Fix the default format for Metrics Collector

- content/en/docs/components/pipelines/installation/overview.md
Update documentation to mention that AI Platform Pipelines 
work with private GKE clusters.
Kubeflow has many components and currently the
full deployment does not work on private GKE clusters.
However, the managed version of the component "Pipelines"
on GCP named "AI Platform Pipelines" does work with
private GKE cluster. This change makes it clear in the
documentation, in hopes to save time for developers
looking for the answer.
> AI Platform Pipelines work with private GKE clusters

- netlify.toml
As raised in https://github.com/kubeflow/website/issues/3109, the Netlify pre-submit tests are failing because they can't see `../vendor/bootstrap/scss/bootstrap`.
Docsy itself has bootstrap as a submodule, and for some reason `git submodule update --init --recursive` is not actually recursively downloading the submodules from the `./themes/docsy` folder.
The command [recomended by the docsy docs](https://www.docsy.dev/docs/deployment/#deployment-with-netlify) is `cd themes/docsy && git submodule update -f --init && cd ../.. && hugo`, so I have used that, but have also kept the production flags `--gc --minify` to improve site performance.
> fix netlify build command

- content/en/docs/components/pipelines/installation/choose-executor.md
- content/en/docs/components/pipelines/installation/standalone-deployment.md
- netlify.toml
Considering the Kubeflow 1.5 release timeline: Feb 24. We will be able to announce this change 30 days ahead of time: https://github.com/kubeflow/community/pull/538.
> pipelines: Announce the Emissary Executor being default starting KFP 1.8

- assets/scss/_styles_project.scss
https://github.com/kubeflow/website/issues/3094
> fix nav menu on hover

- content/en/docs/distributions/aws/OWNERS
Adding folks currently part of https://github.com/orgs/kubeflow/teams/aws/members and working on this project.
Need access to merge PRs like #3121 #2958.
https://github.com/kubeflow/website/pull/3028 is taking longer than expected and we has fewer folks which will become a bottleneck.
> Update AWS distro docs owners

- content/en/docs/releases/kubeflow-1.4.md
Signed-off-by: Anna Jung (VMware) <antheaj@vmware.com>
- Add 1.4.1 release information
- Based on [1.4.1 tracking issue](https://github.com/kubeflow/manifests/issues/2084), versions of the components stay the same for 1.4.1. The only change made for 1.4.1 is https://github.com/kubeflow/manifests/pull/2092
- Update Kserve version for 1.4
- Kserve version used for 1.4 release is [0.6.1](https://github.com/kubeflow/manifests/tree/v1.4.0#kubeflow-components-versions)
cc @kubeflow/release-team
> Add 1.4.1 release

- content/en/docs/distributions/gke/deploy/delete-cli.md
- content/en/docs/distributions/gke/deploy/deploy-cli.md
- content/en/docs/distributions/gke/deploy/management-setup.md
- content/en/docs/distributions/gke/deploy/project-setup.md
- content/en/docs/distributions/gke/deploy/upgrade.md
Corresponding Config Controller change: https://github.com/kubeflow/gcp-blueprints/pull/347.
Partial: https://github.com/kubeflow/gcp-blueprints/issues/341
With the migration to Config Controller, user doesn't need to manually manage or upgrade their Management cluster. This is one-time cost for setting up Management cluster. The integration with Kubeflow project is also simplified.
> gke: Documentation for Config Controller

- content/en/docs/components/pipelines/installation/standalone-deployment.md
https://github.com/kubeflow/pipelines/blob/master/manifests/kustomize/env/gcp/params.env has some default dummy values that need to be updated before one can run the apply command. But this is not mentioned in the doc, and it may not be something very obvious to new users.
> Update KFP standalone-deployment.md on applying GCP Cloud SQL config

- content/en/docs/distributions/aws/_index.md
Added missing index page so that AWS docs show up on 1.3 branch for Kubeflow website.
> Added missing index page

- content/en/docs/distributions/aws/_index.md
Added missing index file so AWS docs show up on 1.4 branch.
> Added missing index file

- content/en/docs/distributions/ibm/deploy/authentication.md
- content/en/docs/distributions/ibm/deploy/iks-compatibility.md
- content/en/docs/distributions/ibm/deploy/install-kubeflow-on-iks.md
- content/en/docs/distributions/ibm/deploy/uninstall-kubeflow.md
Update the instructions to point to the manifests repo
which is used to deploy kubeflow v1.5 on IBM IKS cluster
> Update IKS doc for kubeflow v1.5

- content/en/docs/distributions/charmed/install-kubeflow.md
This PR updates the command for creating a controller. It is necessary to specify the agent version as newer ones are not supported. This is an important step that shouldn't be missed as some critical issues could be raised.
> charmed kubeflow: updates command for creating controller

- content/en/docs/components/pipelines/sdk-v2/build-pipeline.ipynb
in the line 
web_downloader_op = kfp.components.load_component_from_url(
'https://raw.githubusercontent.com/kubeflow/pipelines/master/components/contrib/web/Download/component-sdk-v2.yaml')
the yaml link has changed from "https://raw.githubusercontent.com/kubeflow/pipelines/master/components/web/Download/component-sdk-v2.yaml" to  the correct link "https://raw.githubusercontent.com/kubeflow/pipelines/master/components/contrib/web/Download/component-sdk-v2.yaml"
> updated path to component-sdk-v2.yaml

- content/en/docs/components/multi-tenancy/getting-started.md
- content/en/docs/distributions/gke/deploy/deploy-cli.md
Default is set to `false` - https://github.com/kubeflow/manifests/blob/master/apps/centraldashboard/upstream/base/params.env#L4
> doc: update profile creation defaults to match current manifests

- content/en/_redirects
PR https://github.com/kubeflow/website/pull/3063 incorrectly redirected the pipelines overview page:
- INCORRECT: `/docs/components/pipelines/pipelines-overview` -> `/docs/components/pipelines/introduction`
- CORRECT: `/docs/components/pipelines/overview/pipelines-overview` -> `/docs/components/pipelines/introduction`
This has caused pages that link to Kubeflow Pipelines hit 404, for example: 
- https://www.tensorflow.org/tfx/guide/kubeflow
> fix incorrect redirect for pipelines introduction

- content/en/docs/distributions/charmed/install-kubeflow.md
Remove the workaround introduced in #3179 which bootstrapped an older version of a juju controller due to 2.9.25 not working correctly with charmed kubeflow. With 2.9.26 this is now fixed and the workaround is not needed anymore.
> Charmed Kubeflow: Remove workaround option for creating controller

- content/en/docs/about/community.md
Fix https://github.com/kubeflow/website/issues/3204
One link is valid for 2000 new members.
> slack: Update slack invite link. Fix #3204

- content/en/docs/components/katib/experiment.md
Update documentation for file-metrics-collector.
Ref: https://github.com/kubeflow/katib/pull/1765
/assign @andreyvelich @gaocegege @johnugeorge
> Add documentation on Katib's JSON format logs

- content/en/docs/distributions/aws/component-guides/pipeline.md
Removed section "Configure containers to use AWS credentials" on AWS Kubeflow Pipelines page as per dev team request.
> Removed configuration with AWS credentials section

- content/en/docs/about/community.md
Last invite was expired after 30 days.
cc @james-jwu
> slack: Update slack invite link. Fix #3226

- content/en/docs/distributions/ibm/create-cluster.md
The command line instructions now recommend to specify the `PUBLIC_VLAN_ID` and `PRIVATE_VLAN_ID` since iks 1.21+ version. Hence we need to update the instructions to avoid errors.
> [IKS] Update cluster creation instructions

- content/en/docs/external-add-ons/elyra/_index.md
- content/en/docs/external-add-ons/kserve/kserve.md
- content/en/docs/external-add-ons/kserve/webapp.md
Fix broken image link on webpage due to a relative path used.
> Fix: fix broken images by using consistent path. Fixes #3250

- content/en/docs/about/community.md
Resolves https://github.com/kubeflow/website/issues/3252
This PR updates the slack invite link to use the https://invite.playplay.io/ invite bot.
This should remove the need to update the link in the future, as the following link will not expire:
- https://invite.playplay.io/invite?team_id=T7QLHSH6U
> fix slack invite link

- content/en/_redirects
Redirect all AWS subpages to https://www.kubeflow.org/docs/distributions/aws/
As we now have a new website : https://awslabs.github.io/kubeflow-manifests/
> Redirect to AWS landing page

- content/en/docs/distributions/gke/deploy/overview.md
link took users to a 404 page
At the bottom of the [KubeFlow Overview](https://www.kubeflow.org/docs/distributions/gke/deploy/overview/) page, under "Next Steps," there is a hyperlink titled: [end-to-end-MNIST tutorial](https://www.kubeflow.org/docs/distributions/ibm/iks-e2e/#run-the-mnist-tutorial-on-iks). Updated with the correct link
> 404 page not found - link fix

- content/en/docs/releases/kubeflow-0.6.md
- content/en/docs/releases/kubeflow-0.7.md
- content/en/docs/releases/kubeflow-1.0.md
- content/en/docs/releases/kubeflow-1.1.md
- content/en/docs/releases/kubeflow-1.2.md
- content/en/docs/releases/kubeflow-1.3.md
- content/en/docs/releases/kubeflow-1.4.md
- content/en/docs/releases/kubeflow-1.5.md
- Adds release info for Kubeflow 1.5.1 (replaces PR https://github.com/kubeflow/website/pull/3298)
- Adds a "media" section to the table which contains links to media about the release, for example:
- Our official release blogs
- Our official video overview
- Our official roadmap _(I also fixed the roadmap links, which were not pointing to the correct headers, because the names had changed)_
- Fixes the 1.5.0 table to not include "mpi-operator" (as this is not part of Kubeflow 1.5)
> update release info

- content/en/docs/releases/kubeflow-1.5.md
There was a link conflict for the Kubeflow 1.5.1 blog post, after PR https://github.com/kubeflow/blog/pull/122, we now have separate links for the 1.5 and 1.5.1 blog posts.
This PR updates the link to the 1.5.1 blog post in the releases page.
> fix 1.5.1 blog link

- content/en/docs/components/pipelines/community-and-support.md
> add kfp v2 community and support

- content/en/docs/components/pipelines/cli.md
- content/en/docs/components/pipelines/cli/_index.md
> add kfp v2 cli

- content/en/docs/releases/kubeflow-1.6.md
Signed-off-by: Anna Jung (VMware) <antheaj@vmware.com>
- Add 1.6 release page
- Some links are not available yet 
- 1.6 blog (pr not open yet, should be open before Aug 31st)
- Updated roadmap (open pr: https://github.com/kubeflow/kubeflow/pull/6508)
- Final kubeflow 1.6 release tag (available on Sept 7th - release day)
- Final notebook 1.6 release tag (available before Aug 31st)
cc @kubeflow/release-team 
/hold until docs deadline Aug 31st
> Add kubeflow 1.6 release page

- config.toml
As noted in step 3 of the "[Creating and publishing a website branch](https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md#creating-and-publishing-a-website-branch-for-vxy)", update the `config.toml` to point to v1.6 for the kubeflow/website v1.6-branch
Once this PR is merged, @zijianjoy will need to deploy the new branch to netlify to make it available
cc @kubeflow/release-team @zijianjoy
> Update config to v1.6

- content/en/docs/components/pipelines/author-a-pipeline/pipelines.md
> add kfp v2 authoring/pipelines documentation

- content/en/docs/releases/kubeflow-1.6.md
Signed-off-by: Anna Jung (VMware) <antheaj@vmware.com>
- Add a link to the 1.6 release video
cc @kubeflow/release-team 
This will need to be cherry-picked to the v1.6-branch as well
> Add link to release video

- content/en/docs/releases/kubeflow-0.6.md
- content/en/docs/releases/kubeflow-0.7.md
- content/en/docs/releases/kubeflow-1.0.md
- content/en/docs/releases/kubeflow-1.1.md
- content/en/docs/releases/kubeflow-1.2.md
- content/en/docs/releases/kubeflow-1.3.md
- content/en/docs/releases/kubeflow-1.4.md
- content/en/docs/releases/kubeflow-1.5.md
- content/en/docs/releases/kubeflow-1.6.md
This PR resolves the following issues:
- Previously it was not clear what the dependencies on the release pages actually referred to. They are now explicitly stated as being ONLY related to the `kubeflow/manifests`.
- Previously it was not clear that the dependencies on the release pages were not necessarily "hard" requirements (see [this `kubeflow-discuss` thread with a confused user](https://groups.google.com/g/kubeflow-discuss/c/NaFNdy3UixE/m/YsBav1K2BwAJ)). There is now a disclaimer that other versions might work, but are not validated by the Manifests WG. 
- Previously, the headers for each release version were slightly confusing.
- Dependencies were not listed for Kubeflow 1.5
> update release docs (dependency table + headings)

- README.md
This is to give a way for everyone to see the CI status and report when the issues arise.
> Add Netlify deploy status badge

- content/en/docs/components/training/mpi.md
The APIs are beta.
Not sure if this was an oversight.
> Mark MPI-operator as beta

- config.toml
- content/en/_redirects
- content/en/docs/distributions/gke/_index.md
- content/en/docs/started/installing-kubeflow.md
- Added a link to the external website
- Added ignoreFiles with the list of migrated docs 
- Updated description for the landing page of Kubeflow of Google Cloud
> Migrate GKE docs

- content/en/docs/components/katib/experiment.md
- content/en/docs/components/katib/katib-config.md
I updated documentation for suggestion algorithms.
1. Add Optuna to the documentation for the grid search algorithm
2. Remove Chocolate from all documentation
Part-of: https://github.com/kubeflow/katib/issues/2058
/hold for https://github.com/kubeflow/katib/pull/2071
/assign @kubeflow/wg-automl-leads
> [Katib] Update documentation for suggestion algorithms

- content/en/docs/components/katib/experiment.md
- content/en/docs/components/katib/hyperparameter.md
- content/en/docs/components/katib/resume-experiment.md
- content/en/docs/components/katib/trial-template.md
Related: https://github.com/kubeflow/katib/pull/2102.
We changed the default resume policy to `Never` for Katib Experiments.
Also, I used commit for APIs links so we always have correct reference.
/assign @johnugeorge @tenzen-y
> [Katib] Change the Default Resume Policy

- content/en/docs/components/katib/trial-template.md
After this PR: https://github.com/kubeflow/katib/pull/2091, we use scoped verbs while adding a new CRD to the Katib Controller RBAC.
/assign @johnugeorge @tenzen-y
> [Katib] Limit verbs when use a new CRD in Trials

- content/en/docs/started/installing-kubeflow.md
*This PR replaces the previous https://github.com/kubeflow/website/pull/3381 PR which had a lot of around removing the "Kubeflow Version" from the table.*
The goal of this PR is to improve the experience of new users by improving the `Getting Started / Installing Kubeflow` page. We need this change because people are often overwhelmed by the current page's structure, or are confused when they see an inactive distribution for their chosen platform (and so think Kubeflow is not supported on their platform).
1. __Updated the section headings (for clarity):__
- Added `How to install Kubeflow?` heading
- Renamed `Install a packaged Kubeflow distribution` to `Packaged Distributions of Kubeflow`
- Renamed `Install the Kubeflow Manifests manually` to `Raw Kubeflow Manifests`
2. __Splits the …
> improve installing kubeflow page

- content/en/docs/components/pipelines/v2/author-a-pipeline/pipelines.md
- content/en/docs/components/pipelines/v2/author-a-pipeline/tasks.md
Add documentation for the newly implemented `ignore_upstream_failure` method for pipeline tasks. If this feature is called the pipeline task will run when any specified upstream tasks complete, even if unsuccessful. This method effectively turns the caller task into an exit task if the caller task has upstream dependencies.
Sample:
```
@dsl.pipeline()
def my_pipeline(text: str = 'message'):
task = fail_op(message=text)
clean_up_task = print_op(
message=task.output).ignore_upstream_failure()
```
> add docs for ignore_upstream_failure

- content/en/docs/components/notebooks/quickstart-guide.md
* "exit" -> "exist" in configurations step
> Fix typo on kubeflow notebook quickstart guide

- content/en/docs/components/pipelines/v1/installation/upgrade.md
After deprecating the run metrics column in run list page, we provide another reference here for users to get the same result.
> Add notice for deprecating run metrics

- content/en/docs/started/installing-kubeflow.md
- Bumped GKE version to 1.7.0
- Hold until we merge GoogleCloudPlatform/kubeflow-gke-docs#7
> Release 1.7.0 on GKE

- content/en/docs/components/pipelines/v2/components/container-components.md
- content/en/docs/components/pipelines/v2/pipelines/pipeline-basics.md
These docs were lost in https://github.com/kubeflow/website/pull/3472. This PR re-adds them with some minimal refresh/cleanup.
> re-add placeholder and special input value content to v2 KFP docs

- content/en/docs/started/installing-kubeflow.md
Update Canonical's Charmed Kubeflow supported version.
cc: @DomFleischmann
> docs: bump Charmed Kubeflow supported version 1.6.1->1.7.0

- content/en/docs/components/training/job-scheduling.md
- content/en/docs/components/training/mpi.md
Since https://github.com/kubeflow/mpi-operator/pull/520, we introduce the schedulingPolicy to mpi-operator.
So I added docs for that.
/assign @alculquicondor 
/hold for https://github.com/kubeflow/mpi-operator/pull/520.
> MPI-Operator: Add docs for the schedulingPolicy

- content/en/docs/components/pipelines/v1/installation/choose-executor.md
Emissary executor has been the default executor since KFP 1.8, and appears to be quite stable.
> kfp: Update choose-executor.md

- content/en/docs/components/pipelines/v1/sdk/pipelines-with-tekton.md
update the broken link to current kfp-tekton user guide.
> fix broken link for kfp-tekton

- content/en/docs/started/installing-kubeflow.md
This PR adds deployKF, to the list of distributions:
- https://www.deploykf.org/
- https://github.com/deployKF/deployKF
I have positioned it alphabetically in this list (after the top section of major cloud providers).
> add deployKF to list of distributions

- content/en/docs/distributions/kfaas/_index.md
- content/en/docs/started/installing-kubeflow.md
As raised in https://github.com/kubeflow/website/issues/3519, it seems like `"Arrikto Kubeflow as a Service"` no longer exists.
The following links which were provided in the docs are dead:
- https://kubeflow.arrikto.com/
- https://www.arrikto.com/kubeflow-as-a-service/
Therefore, I vote we should remove them from the website.
__NOTE:__ I have left `"Arrikto Enterprise Kubeflow"` up, but I suspect it no longer meets the definition of "active" given its [last release was Kubeflow 1.5, and happened in March 2023](https://docs.arrikto.com/NEWS.html#version-2-0-2-aurora)
> remove arrikto kubeflow as a service (dead link)

- content/en/docs/external-add-ons/kale/_index.md
The kale project has not been updated since [`Oct 20, 2021`](https://github.com/kubeflow-kale/kale/commits/master), therefore I think we can treat it as abandoned and remove it from the Kubeflow website.
Also, there are many issues on the `kubeflow-kale/kale` repo discussing that the project is no longer maintained:
- https://github.com/kubeflow-kale/kale/issues/436
- https://github.com/kubeflow-kale/kale/issues/395
> remove kale docs (project is abandoned)

- content/en/docs/components/pipelines/v2/installation/quickstart.md
I originally met this issue and asked in the Stack Overflow: https://stackoverflow.com/questions/76601980/got-errorrootfailed-to-get-healthz-info-attempt-1-of-5-when-deploy-pipeline
It turns out the document is out-of-date. So just bump the version 😃
> docs: update kubeflow version in the quickstart

- content/en/docs/about/community.md
This PR updates the "about" / "community" page to reflect the current calendar situation.
Namely that most of the working group-specific calendars are no longer a thing, and most events have moved back into the shared "kubeflow community calendar".
It also improves the javascript which generates the aggregated calendar view, to make it easier to change which Google Calendars are included.
> update calenders and links

- content/en/docs/components/pipelines/v2/data-types/parameters.md
- content/en/docs/components/pipelines/v2/pipelines/pipeline-basics.md
.output['<output-key>'] should be .outputs['<output-key>'] (plural) instead in case of multiple outputs.
> fix(pipelines): Update .output['output-key'] to plural

- content/en/docs/started/installing-kubeflow.md
This PR moves "Arrikto Enterprise Kubeflow" to the legacy distributions section.
While it has not technically been 6 months of inactivity (only about 4, since the [last release on `2023-03-31`](https://docs.arrikto.com/Changelog.html#version-2-0-2-aurora)), as the most recent version only included Kubeflow 1.5.0 (which was released on `2022-06-15`), I think its fair to say this distribution is no longer active.
I am sad to have to do this.
> move "Arrikto Enterprise Kubeflow" to legacy distributions

- content/en/docs/started/installing-kubeflow.md
This PR rewords "All Conformant Kubernetes" to "All Certified Kubernetes Distributions".
This is a subtle but important change for inclusivity, as I have seen many users not understanding what "Conformant" means (especially people for whom English is not their first language).
> reword "All Conformant Kubernetes" to "All Certified Kubernetes Distributions"

- content/en/docs/about/community.md
Related: https://github.com/kubeflow/community/pull/652.
We moved AutoML and Training WG event to Kubeflow calendar.
I also added AutoML and Training Slack channels.
cc @kubeflow/wg-training-leads @tenzen-y @thesuperzapper
> Remove AutoML Calendar

- content/en/_redirects
- content/en/docs/components/multi-tenancy/istio.md
- content/en/docs/external-add-ons/istio/OWNERS
- content/en/docs/external-add-ons/istio/_index.md
This PR moves the `istio` docs from `external-addons` to the `multi-tenancy` component section.
This is a better location for these docs as istio is clearly not an external addon for Kubeflow, but is part of the multi-user feature.
> move istio docs from `external-addons` to `multi-tenancy` component

- content/en/docs/releases/kubeflow-1.8.md
Adding draft of the release page for the website
> Add Kubeflow 1.8 Release Page

- content/en/docs/started/installing-kubeflow.md
Follow up on https://github.com/kubeflow/website/pull/3619#issuecomment-1804605803
> Update GCP deployment version to v1.8 in Installing Kubeflow page 

- config.toml
- Fixes broken doc page meta (GitHub) links
- Fixes https://github.com/google/docsy/issues/138, which reported the issue originally
---
- On desktop, visit https://www.kubeflow.org/docs/
- Click on **View page source**
- You'll be sent to https://github.com/kubeflow/website/tree/main/content/en/docs/_index.md, which is a 404 because the default branch isn't `main`
- On desktop, visit https://deploy-preview-3625--competent-brattain-de2d6d.netlify.app/docs/
- Click on **View page source**
- You'll be sent to https://github.com/kubeflow/website/tree/master/content/en/docs/_index.md, which is a valid page
/cc @sarahmaddox @LisaFC
> Fix broken page-meta links

- content/en/docs/releases/kubeflow-1.8.md
This just updates the release page to the video,
I would like to ask if they can rebase the tag v1.8-release branch to this commit, and recreate the tag release, so we can have a new page.
> Updated link to Kubeflow 1.8 Release Overview video

- content/en/docs/components/pipelines/v1/sdk/output-viewer.md
Python based visualizations were deprecated in b2483a1. Yet there was language left over that referred to them as the "new" way to do visualizations. This was highly confusing.
Fix some typos too.
> remove reference to now-deprecated "Python based visualizations"

- content/en/docs/components/katib/env-variables.md
This follow-up PR reflects a change from https://github.com/kubeflow/katib/pull/2245, which introduced a new environment variable option to skip DB initialization when Katib DB manager is run.
It updates **Katib DB Manager** part of [Environment Variables for Katib Components](https://www.kubeflow.org/docs/components/katib/env-variables/#katib-db-manager).
Closes #3656
> Katib: Add SKIP_DB_INITIALIZATION variable of Katib DB Manager

- content/en/docs/started/installing-kubeflow.md
Update the docs so that Charmed Kubeflow is updated for 1.8
cc @DnPlas
> Update CKF to 1.8

- config.toml
Adding "events" page to top nav and also replacing Kubeflow Summit with GSoC reference.
> Adding link to events page from top nav

- content/en/docs/components/pipelines/v2/administration/server-config.md
This PR fixes `typos in content/en/docs/components/pipelines/v2/administration/server-config.md`.
> Fixed typos in server-config.md

- content/en/docs/components/notebooks/container-images.md
align link to example-notebook-servers,
this align the now fixed link, analogously to already existing (working) link:
https://github.com/kubeflow/website/blob/60dc9625afd09803eeeabf00117378633a8650b1/content/en/docs/components/notebooks/container-images.md?plain=1#L137
> Fix broken link container-images.md

- content/en/docs/about/community.md
To support [#3639](https://github.com/kubeflow/website/issues/3639) adding the social networking sites to the community webpage. Links to Kubeflow's YouTube, LinkedIn, and Twitter (X) were added.
> Adding social networking websites to the community page

- content/en/docs/components/training/mpi.md
- content/en/docs/components/training/mxnet.md
- content/en/docs/components/training/paddlepaddle.md
- content/en/docs/components/training/pytorch.md
- content/en/docs/components/training/xgboost.md
Based on the discussion on the PR https://github.com/kubeflow/training-operator/pull/2004 , I updated the documentation website pages for the different `*Job` CRs to include a comment about having to disable automatic sidecar injection in some cases, and how to do that.
> Updated CRs documentation to include comment about istio annotation

- content/en/docs/components/pipelines/v1/sdk/build-pipeline.md
- content/en/docs/components/pipelines/v1/sdk/python-function-components.md
Fix `Run in Google Colab` and `View source on GitHub` buttons for listed v1 Pipelines SDK pages.
Top page buttons only for `build-pipeline.md` page were already working, likely as part of previous doc migration when v2.
> fix buttons for v1 Pipelines SDK

- content/en/events/gsoc-2024.md
This updates page after the selection Kubeflow into GSoc mainly highlighting
- how to participate in kubeflow's gsoc
- how to reach out to mentors
- how to reach out to mentors in community calls
- what to do if student did not get selected in gsoc program
> updates to GSoC Page after selection into the program

- content/en/docs/about/contributing.md
This PR depends on https://github.com/kubeflow/community/pull/703.
The Legal text is based on [Argo Project](https://github.com/argoproj/argoproj/blob/main/community/CONTRIBUTING.md#legal).
> Updated legal info due to migration from CLA to DCO

- content/en/docs/components/katib/env-variables.md
This follow-up PR reflects a change from https://github.com/kubeflow/katib/pull/2266, which introduced a new environment variable option to allow users to specify the value of Postgres sslmode.
It updates Katib DB Manager part of [Environment Variables for Katib Components](https://www.kubeflow.org/docs/components/katib/env-variables/#katib-db-manager).
> Katib: Add KATIB_POSTGRESQL_SSL_MODE variable of Katib DB Manager

- content/en/docs/about/community.md
This PR updates our Kubeflow Slack inviter link to use the same system as CNCF Slack, the current bot is struggling under the large number of people joining for GSoC.
__See these related user issues:__
- https://github.com/kubeflow/community/issues/706
- https://groups.google.com/g/kubeflow-discuss/c/ncc_piQY2O8
__The link is changing from:__
- __OLD:__ https://invite.playplay.io/invite?team_id=T7QLHSH6U
- __NEW:__ https://communityinviter.com/apps/kubeflow/slack
---
__NOTE:__ The new link still invites users to the `Kubeflow` slack, not the `CNCF` one. We are still planning on how to migrate to CNCF slack so we can minimize disruption.
> update slack inviter link

- content/en/docs/components/katib/early-stopping.md
- content/en/docs/components/katib/hyperparameter.md
fix the source code reference about mxnet.
The mxnet example has been removed in https://github.com/kubeflow/katib/pull/2267 and no longer available, we use pytorch example instead.
> Katib: fix the source code reference about mxnet

- content/en/docs/components/training/mxnet.md
Related: https://github.com/kubeflow/training-operator/issues/1996.
I added MXJob deprecation notice to the Kubeflow Website.
/assign @kubeflow/wg-training-leads
> Training: Add MXJob deprecation notice

- content/en/docs/about/contributing.md
This PR updates the contributors table link.
Fixes https://github.com/kubeflow/website/issues/3732.
> Updated contributors table link

- content/en/_redirects
I fixed redirect to Katib getting started guide.
/assign @kubeflow/wg-training-leads @thesuperzapper
> Katib: Fix getting started redirect

- content/en/docs/external-add-ons/feature-store/OWNERS
I am one of the [maintainers of Feast](https://github.com/feast-dev/feast/blob/311efc5005b24d1fc9bc389ee7579e102e2cd4ea/community/maintainers.md) and I'd like to update the documentation here. 
So I have proposed to add myself as an OWNER for the Feature Store documentation.
> feat: Add Francisco as OWNER for Feature Store documentation

- content/en/docs/components/katib/user-guides/hp-tuning/configure-experiment.md
add missing annotation value in yaml example otherwise the apply of the experiment will fail as invalid:
```
Error from server: error when creating "random.yaml": admission webhook "validator.experiment.katib.kubeflow.org" denied the request: invalid spec.trialTemplate: unable to convert: /spec/template/metadata/sidecar.istio.io~1inject - false to Job, converted template: {"kind":"Job","apiVersion":"batch/v1","metadata":{"creationTimestamp":null},"spec":{"template":{"metadata":{"creationTimestamp":null},"spec":{"containers":[{"name":"training-container","image":"docker.io/kubeflowkatib/pytorch-mnist-cpu:latest","command":["python3","/opt/pytorch-mnist/mnist.py","--epochs=1","--batch-size=16","--lr=test-value","--momentum=test-value"],"resources":{"limits":{"cpu":"500m","memory":"1Gi"}}}]," …
```
> configure-experiment.md - missing annotation value in yaml example

- content/en/docs/external-add-ons/feature-store/getting-started.md
- Update the obsoleted links
- Remove one line about upgrading Feast from 0.9 to 0.12.  The version numbers are too old. The latest version is 0.37.1.
> doc: Update the document of Feast feature store.

- content/en/docs/components/pipelines/v1/installation/localcluster-deployment.md
Looks like `platform-agnostic-pns` folder seems to be removed in [this](https://github.com/kubeflow/pipelines/commit/809d5766fc9ec436ff05c083e9a2ae65ad2667b7) commit
I hope `platform-agnostic` is the new one to use. 
Also, there was an error with `workflow-controller` and `metadata-envoy-deployment` using the same port causing crash loop. I modified the `workflow-controller` deployment to change the to a non conflicting port.
> Removed reference to non existing path

- content/en/docs/started/installing-kubeflow.md
- content/en/docs/started/introduction.md
As we discussed multiple times before, we want to explain our users that Kubeflow components can be deployed:
- in **Standalone** mode.
- in **Kubeflow Platform** for end-to-end AI/ML experience.
In this PR I made changes to the installation section:
I removed  `What is Kubeflow?` section from this page since we already have this section here: https://www.kubeflow.org/docs/started/introduction/#what-is-kubeflow, we can update it if you think it is out-of-date.
I made these sections:
- Install Kubeflow Components Standalone 
- Install Kubeflow Platform from Raw Manifests 
- Install Kubeflow Platform from Packaged Distributions
From my point of view this is logically correct, for users to learn about Kubeflow ecosystem. Firstly, users will explore the value of individual Kubeflow …
> Update Kubeflow Installation with Standalone Mode

- content/en/docs/components/notebooks/overview.md
Make RStudio link point to https://github.com/rstudio/rstudio (instead of https://github.com/jupyterlab/jupyterlab) for consistency with:
https://github.com/kubeflow/website/blob/f88fcc0ac728873b561fa510c8d80b7d8a87b48d/content/en/docs/components/notebooks/container-images.md?plain=1#L7
> Link to RStudio

- content/en/docs/about/community.md
I added MPI Operator to the Slack channels.
/assign @kubeflow/wg-training-leads
> Add Slack channel for MPI Operator

- content/en/docs/components/central-dash/access.md
- content/en/docs/distributions/list.md
After https://github.com/kubeflow/website/pull/3724, some of the links to the Packaged Distributions section were incorrect (after the heading changed).
> Fix links to packaged distributions section

- content/en/docs/components/model-registry/OWNERS
- content/en/docs/components/model-registry/installation.md
implements suggestions from KF community meeting 2024-05-22
for your kind review
/assign @andreyvelich @thesuperzapper 
please?
> model registry: pin tag and standalone instructions

- content/en/docs/components/katib/getting-started.md
We discussed that we want to keep `kubeflow` namespace in Getting Started example, so users don't see errors who install Katib standalone.
/assign @tenzen-y @helenxie-bit @johnugeorge
> Katib: Update namespace in getting started guide

- content/en/docs/components/training/user-guides/pytorch.md
This PR fixes invalid label names and broken links on [PyTorch Training (PyTorchJob)](https://www.kubeflow.org/docs/components/training/user-guides/pytorch/).
PS:
Now labels on derived Pods by Training Operator all with `training.kubeflow.org` prefix, like:
```yaml
apiVersion: v1
kind: Pod
metadata:
labels:
training.kubeflow.org/job-name: pytorch-simple
training.kubeflow.org/job-role: master
training.kubeflow.org/operator-name: pytorchjob-controller
training.kubeflow.org/replica-index: "0"
training.kubeflow.org/replica-type: master
name: pytorch-simple-master-0
namespace: kubeflow
```
> Fix invalid labels and broken links on PyTorch Training page

- content/en/docs/components/katib/getting-started.md
- content/en/docs/components/katib/installation.md
- content/en/docs/components/training/installation.md
I fixed the Katib getting started example.
Also, I added the command to install SDK from the `master` branch and from the commit.
/assign @tenzen-y @johnugeorge @helenxie-bit
> Katib: Fix getting started example

- content/en/docs/started/installing-kubeflow.md
@andreyvelich this PR adds the 1.8.1 release and clarifies the support level of kubeflow/manifests for users.
Follow up of https://github.com/kubeflow/website/pull/3724#discussion_r1609404651
and https://github.com/kubeflow/website/pull/3724#issuecomment-2136820612
> Update manifests warning

- content/en/docs/components/pipelines/user-guides/data-handling/artifacts.md
Resolves https://github.com/kubeflow/website/issues/3760.
cc @rimolive @chensun
> Removed obsolete warning from Pipelines artifacts.md

- content/en/docs/components/pipelines/getting-started.md
Partially Reverts kubeflow/website#3787
That PR should not have been merged, it created a bunch of dead links in the page by removing the `[XXX]` anchors at the bottom of the page.
> Partial Revert of #3787

- content/en/docs/components/pipelines/reference/component-spec.md
the search URL in the docs does not currently work
> fix: broken github url in component-spec.md

- content/en/docs/components/pipelines/concepts/pipeline-root.md
- content/en/docs/components/pipelines/operator-guides/installation/_index.md
- content/en/docs/components/pipelines/user-guides/core-functions/connect-api.md
Resolves https://github.com/kubeflow/website/issues/3714.
This PR aims to add minimal information to install KFP standalone.
Further improvements will be added later.
> Added instructions for installing Pipelines.

- netlify.toml
- package-lock.json
- package.json
This PR adds the [Checklinks](https://www.netlify.com/integrations/community-built/checklinks-build-plugin/) Netlify plugin for checking broken links during the CI.
I mentioned that in the [Kubeflow Community Meeting on 2024-06-18](https://docs.google.com/document/d/1Wdxt1xedAj7qF_Rjmxy1R0NRdfv7UWs-r2PItewxHpE/edit#heading=h.aba10q1p5i5r).
Checklinks fails the Netlify build when broken links are detected.
To avoid breaking the build due to the existing broken links, I added them to a TODO list so we can fix them later.
See a [screencast](https://github.com/kubeflow/website/assets/11776454/01cf5cf0-3d8a-49dd-b32e-89506c4a71d9) of the plugin in action.
cc @jbottum @andreyvelich
> Enabled the Checklinks Netlify plugin

- config.toml
- layouts/partials/head.html
- layouts/partials/seo_schema.html
- layouts/partials/social_image_generator.html
- netlify.toml
This PR is a follow up to https://github.com/kubeflow/website/pull/3818
It seems like [Twitter wants full URLs](https://devcommunity.x.com/t/card-error-unable-to-render-or-no-image-read-this-first/62736)  in the `<meta name="twitter:image" content=".......">` tags, that is, including the `https://DOMAIN/` prefix. While this is what the [`PAGE.Permalink`](https://gohugo.io/methods/page/permalink/) template in Hugo is meant to do, this only works if the Hugo [`baseURL`](https://gohugo.io/methods/site/baseurl/) config is set.
This PR will set `baseURL` for:
- production deployments to `https://www.kubeflow.org/`
- deploy previews (like this PR) to [`DEPLOY_PRIME_URL`](https://docs.netlify.com/configure-builds/environment-variables/#deploy-urls-and-metadata), an environment variable provided …
> Fix baseURL in Netlify deployments (needed to fix `twitter:image`)

- content/en/docs/about/contributing.md
The contributing.md file links to a now archived channel in the old kubeflow slack. This commit removes that link unitl we have created a new #community channel in the CNCF slack
> Remove dead link to kubeflow community slack

- content/en/docs/components/training/installation.md
We should use quotes when we install Training SDK with HuggingFace dependencies.
/assign @kubeflow/wg-training-leads
> Training: Fix SDK install for LLMs Fine-Tuning API

- content/en/_index.html
- content/en/docs/started/introduction.md
Followup on @thesuperzapper comment here: https://github.com/kubeflow/website/pull/3728#discussion_r1628261603
I updated Kubeflow index page in this PR. Please let me know what do you think about this statement ?
For inspiration I checked one of the first Kubeflow videos that @aronchick presented before:
https://youtu.be/R3dVF5wWz-g?t=875
/assign @thesuperzapper @kubeflow/kubeflow-steering-committee @StefanoFioravanzo @hbelmiro @franciscojavierarceo 
/hold for review
> Update Kubeflow Index Page

- content/en/docs/releases/kubeflow-1.9.md
In the interest of fixing the incorrect date while we wait for https://github.com/kubeflow/website/pull/3835 to be ready (we need to upload the video to the `Kubeflow` channel before we publish), I am raising a separate PR to only fix the date.
> Fix Kubeflow 1.9 release date

- content/en/docs/started/installing-kubeflow.md
This PR updates the "Kubeflow Manifests" section from page "Installing Kubeflow" with the new version and removes the 1.7 one to keep the same number of releases.
1. added links to kubeflow 1.9 manifests
2. removed links to kubeflow 1.7 manifests
> chore: add links to kubeflow 1.9 manifests

- content/en/docs/components/katib/user-guides/katib-config.md
- content/en/docs/components/pipelines/legacy-v1/tutorials/api-pipelines.md
- content/en/docs/components/pipelines/operator-guides/multi-user.md
- content/en/docs/components/pipelines/user-guides/components/_index.md
- content/en/docs/components/pipelines/user-guides/core-functions/_index.md
- content/en/docs/components/pipelines/user-guides/core-functions/build-advanced-pipeline.md
- content/en/docs/components/pipelines/user-guides/core-functions/caching.md
- content/en/docs/components/pipelines/user-guides/core-functions/cli.md
- content/en/docs/components/pipelines/user-guides/core-functions/compile-a-pipeline.md
- content/en/docs/components/pipelines/user-guides/core-functions/connect-api.md
- content/en/docs/components/pipelines/user-guides/core-functions/control-flow.md
- content/en/docs/components/pipelines/user-guides/core-functions/execute-kfp-pipelines-locally.md
- content/en/docs/components/pipelines/user-guides/core-functions/platform-specific-features.md
- content/en/docs/components/pipelines/user-guides/core-functions/run-a-pipeline.md
- content/en/docs/components/pipelines/user-guides/data-handling/_index.md
- content/en/docs/components/pipelines/user-guides/data-handling/artifacts.md
- content/en/docs/components/pipelines/user-guides/migration.md
This PR makes significant formatting updates and rewording to the `Kubeflow Pipelines` / `User Guides` / `Core Functions`, and `Migrate to Kubeflow Pipelines v2` guides.
For the most part this is a formatting update, but I draw reviwers attention to a content change I made on the `Connect the SDK to the API` page. I have updated the Python script given as an example for connecting the KFP SDK with Dex. I have used the same [reference example as in the deployKF docs](https://www.deploykf.org/user-guides/access-kubeflow-pipelines-api/#dex-static-credentials). (Note, it will work for all other distributions, including manifests, as long as they use Dex).
The most important changes in this PR are:
- Re-naming the `Core Functions` pages to have shorter titles to be more clear
- Re-ordering the …
> Improve the KFP / User Guides / Core Functions docs

- netlify.toml
- themes/kf/layouts/_default/baseof.html
This PR adds the [`<meta name="robots" content="noindex">` meta tag](https://developers.google.com/search/docs/crawling-indexing/block-indexing) to tell Google to stop indexing the pages from the `v0.2-branch` branch.
> Block web crawlers on `v0.2-branch`

- netlify.toml
- themes/kf/layouts/_default/baseof.html
This PR adds the [`<meta name="robots" content="noindex">` meta tag](https://developers.google.com/search/docs/crawling-indexing/block-indexing) to tell Google to stop indexing the pages from the `v0.3-branch` branch.
> Block web crawlers on `v0.3-branch`

- config.toml
- layouts/partials/navbar-version-selector.html
- netlify.toml
- package.json
- themes/docsy/layouts/partials/head.html
This PR adds the [`<meta name="robots" content="noindex">` meta tag](https://developers.google.com/search/docs/crawling-indexing/block-indexing) to tell Google to stop indexing the pages from the `v0.4-branch` branch.
---
> Block web crawlers on `v0.4-branch`

- netlify.toml
This is a follow up to https://github.com/kubeflow/website/pull/3847, and is similar to https://github.com/kubeflow/website/pull/3864, except for the `v0.3-branch`.
Unlike the `v0.2-branch` the `v0.3-branch` did sucessfully deploy, but I think it was a fluke, and also needs to have Hugo updated to ensure it works successfully in the future, see the build logs:
- https://app.netlify.com/sites/competent-brattain-de2d6d/deploys/66d9af5ef5f8e600085b1753
This PR updates Hugo/NodeJS to a version that Netlify can actually install.
> Update `v0.3-branch` Hugo (fix deploy)

- netlify.toml
The updates from https://github.com/kubeflow/website/pull/3848 being merged don't seem to have succeeded to deploy, see the build logs: 
- https://app.netlify.com/sites/competent-brattain-de2d6d/deploys/66d9af5ed1fb2d0008676d2b
I am pretty sure it's because that extremely old version of Hugo (from before semantic versioning) can't be installed, so I am updating it to version `0.81.0`, the same as the one used on the `v0.4-branch` which should fix it.
> Update `v0.2-branch` Hugo (fix deploy)

- content/en/docs/releases/kubeflow-1.9.md
1. fix the release date,
ref: https://github.com/kubeflow/manifests/releases/tag/v1.9.0
as noticed by @thesuperzapper 
2. link to Kubeflow 1.9 Release Update youtube video
👉 if the PR is approved, I will update the video from Unlisted -> Published
@kubeflow/release-team @rimolive @StefanoFioravanzo @andreyvelich @hbelmiro @jbottum @juliusvonkohout
> KF 1.9 release: fix date and link to video

- OWNERS
- themes/kf/layouts/partials/version-banner.html
This is a follow up to https://github.com/kubeflow/website/pull/3848
This PR makes the following changes:
1. Uses the same "archived_version" banner styling as the newer branches
1. Updates the OWNERS file of this very old branch to align with [the current `OWNERS` in `master`](https://github.com/kubeflow/website/blob/89d8f792625e6c95fad4774570358ecd773830e7/OWNERS) to make it easier to approve PRs in the future without GitHub admin overrides.
> Improve `archived_version` banner for `v0.2-branch`

- OWNERS
- themes/kf/layouts/partials/version-banner.html
This is a follow up to https://github.com/kubeflow/website/pull/3847
This PR makes the following changes:
1. Uses the same "archived_version" banner styling as the newer branches
1. Updates the OWNERS file of this very old branch to align with [the current `OWNERS` in `master`](https://github.com/kubeflow/website/blob/89d8f792625e6c95fad4774570358ecd773830e7/OWNERS) to make it easier to approve PRs in the future without GitHub admin overrides.
> Improve `archived_version` banner for `v0.3-branch`

- OWNERS
- config.toml
- layouts/partials/head.html
- layouts/partials/version-banner.html
- netlify.toml
- package.json
This PR adds the [`<meta name="robots" content="noindex">` meta tag](https://developers.google.com/search/docs/crawling-indexing/block-indexing) to tell Google to stop indexing the pages from the `v1.0-branch` branch.
--- …
> Block web crawlers on `v1.0-branch`

- OWNERS
- config.toml
- layouts/partials/head.html
- layouts/partials/version-banner.html
- netlify.toml
- package.json
This PR adds the [`<meta name="robots" content="noindex">` meta tag](https://developers.google.com/search/docs/crawling-indexing/block-indexing) to tell Google to stop indexing the pages from the `v1.1-branch` branch.
--- …
> Block web crawlers on `v1.1-branch`

- content/en/docs/components/pipelines/user-guides/core-functions/control-flow.md
This is an unsupported field in kfp, and should be indicated as such. More Context [here](https://github.com/kubeflow/pipelines/issues/10917#issuecomment-2289974966)
> add unsupported notice for PipelineTaskFinalStatus

- OWNERS
- config.toml
- layouts/partials/head.html
- layouts/partials/version-banner.html
- netlify.toml
- package-lock.json
- package.json
This PR adds the [`<meta name="robots" content="noindex">` meta tag](https://developers.google.com/search/docs/crawling-indexing/block-indexing) to tell Google to stop indexing the pages from the `v1.3-branch` branch.
--- …
> Block web crawlers on `v1.3-branch`

- OWNERS
- config.toml
- layouts/partials/head.html
- layouts/partials/version-banner.html
- netlify.toml
- package.json
This PR adds the [`<meta name="robots" content="noindex">` meta tag](https://developers.google.com/search/docs/crawling-indexing/block-indexing) to tell Google to stop indexing the pages from the `v1.2-branch` branch.
--- …
> Block web crawlers on `v1.2-branch`

- OWNERS
- config.toml
- layouts/partials/head.html
- layouts/partials/version-banner.html
- netlify.toml
- package-lock.json
- package.json
This PR adds the [`<meta name="robots" content="noindex">` meta tag](https://developers.google.com/search/docs/crawling-indexing/block-indexing) to tell Google to stop indexing the pages from the `v1.4-branch` branch.
--- …
> Block web crawlers on `v1.4-branch`

- OWNERS
- config.toml
- layouts/partials/head.html
- layouts/partials/version-banner.html
This PR adds the [`<meta name="robots" content="noindex">` meta tag](https://developers.google.com/search/docs/crawling-indexing/block-indexing) to tell Google to stop indexing the pages from the `v1.5-branch` branch.
--- …
> Block web crawlers on `v1.5-branch`

- OWNERS
- config.toml
- layouts/partials/head.html
- layouts/partials/version-banner.html
This PR adds the [`<meta name="robots" content="noindex">` meta tag](https://developers.google.com/search/docs/crawling-indexing/block-indexing) to tell Google to stop indexing the pages from the `v1.6-branch` branch.
--- …
> Block web crawlers on `v1.6-branch`

- OWNERS
- config.toml
- layouts/partials/head.html
- layouts/partials/version-banner.html
This PR adds the [`<meta name="robots" content="noindex">` meta tag](https://developers.google.com/search/docs/crawling-indexing/block-indexing) to tell Google to stop indexing the pages from the `v1.7-branch` branch.
--- …
> Block web crawlers on `v1.7-branch`

- OWNERS
- config.toml
- layouts/partials/head.html
- layouts/partials/version-banner.html
This PR adds the [`<meta name="robots" content="noindex">` meta tag](https://developers.google.com/search/docs/crawling-indexing/block-indexing) to tell Google to stop indexing the pages from the `v1.8-branch` branch.
--- …
> Block web crawlers on `v1.8-branch`

- content/en/docs/components/pipelines/user-guides/components/containerized-python-components.md
This PR fixes the documentation for containerized Python components. The current documentation doesn't work and errors out as described in #3871 
- Move the import into the component
- Update base_image to Python 3.11
- Import the component in `pipeline.py`
> Fix: Update containerized-python-components.md. fixes #3871

- content/en/docs/components/spark-operator/user-guide/yunikorn-integration.md
Add a user guide page to the Spark operator on Yunikorn gang scheduling support that is upcoming in the 2.0.0 release.
https://github.com/kubeflow/spark-operator/issues/2098
> Add page for Spark operator/Yunikorn integration

- content/en/docs/components/central-dash/overview.md
- netlify.toml
Resolves https://github.com/kubeflow/website/issues/3809
> Fixed broken link in central dashboard

- content/en/docs/components/pipelines/user-guides/core-functions/caching.md
Ref: https://github.com/kubeflow/pipelines/pull/11222
> [Pipelines] Add doc on disabling default caching flag and env var

- content/en/docs/components/pipelines/user-guides/core-functions/caching.md
As the changes introduced in https://github.com/kubeflow/pipelines/pull/11222 are in master but not in KFP 2.9.0 SDK, modify the _Use Caching_ page to specify when then new caching flag will be available
> [Pipelines] Specify KFP SDK version where new caching flag will be available

- README.md
- content/en/docs/about/community.md
- content/en/docs/about/contributing.md
- content/en/docs/about/membership.md
- layouts/shortcodes/note.html
This PR adds guidelines around the kubeflow community membership.
This set of guidelines is heavily inspired by the Kubernetes guidelines at https://github.com/kubernetes/community/blob/master/community-membership.md?plain=1#community-membership
cc @kubeflow/kubeflow-steering-committee
> Make basic community membership guidelines clearer

- content/en/docs/components/katib/reference/nas-algorithms.md
fix link in section Efficient Neural Architecture Search (ENAS) - related to #3811 . Discussed with @hbelmiro 
To resolve this problem:
> fix link in section Efficient Neural Architecture Search (ENAS)

- content/en/docs/components/katib/installation.md
- content/en/docs/components/training/getting-started.md
- content/en/docs/components/training/installation.md
I updated PyTorchJob getting started example to make it run with `torchrun.
/assign @kubeflow/wg-training-leads @kuizhiqing 
/hold until this merged https://github.com/kubeflow/training-operator/pull/2276
> Training: Update example to run PyTorchJob with torchrun

- content/en/docs/components/spark-operator/getting-started.md
This PR is to correct the typo in documentation where the property for spark-operator pod to monitor multiple namespaces was incorrectly specified in documentation as `sparkjoNamespaces` insted of `spark.jobNamespaces`
closes kubeflow/spark-operator#2103
> changed sparkJobNamespaces to spark.JobNamespaces

- content/en/docs/components/training/installation.md
Latest version of the training operator will require to use server side apply to install its CRDs, as their sizes have increased beyond what client-side apply can handled.
See https://github.com/kubeflow/training-operator/pull/2332#discussion_r1860620021 for more details.
/cc @tenzen-y @andreyvelich
> Update training operator installation to use SSA

- content/en/docs/started/introduction.md
As a newcomer interested in this community, I never noticed in the Kubeflow logo had "K" and "F" 😅 
To me, it looked like a https://en.wikipedia.org/wiki/Diamond_cut
Until today, another variation made me notice those letters.
You know, like those https://en.wikipedia.org/wiki/Rabbit%E2%80%93duck_illusion effect
With this PR, I propose adding it to the History section in the introduction.
As I searched Kubeflow git org history, I found an expanded explanation, which is hyperlinked in the markdown for the extra-curious and proper attribution.
> add history on KF logo

- content/en/docs/components/training/user-guides/fine-tuning.md
Follow up from https://github.com/kubeflow/training-operator/pull/2261 as this is a user facing change.
> [KFTO-SDK] Add doc on customising base images for Train API

- content/en/docs/components/katib/user-guides/metrics-collector.md
This PR aims at guiding users using push-based metrics collection: https://github.com/kubeflow/katib/issues/2340.
I rewrote the metrics-collector chapter and divided it into three parts:
1. Overview: Introduce the type and the config of the metrics collector.
2. Pull-based Metrics Collector: The original part of this chapter. I removed `None` MC.
3. Push-based Metrics Collector: Describe the usage of `Push` MC, with an example attached.
cc👀 @kubeflow/wg-automl-leads . Please let me know if you have any suggestions.
> doc(katib): update push-based metrics collector.

- content/en/docs/about/contributing.md
- content/en/docs/about/membership.md
We discussed that we want to add the section about emeritus approvers to the Kubeflow membership doc: https://github.com/kubeflow/training-operator/pull/2343#issuecomment-2516351222
I took the info from the Kubernetes docs: https://www.kubernetes.dev/docs/guide/owners/#emeritus
/assign @kubeflow/wg-training-leads @anishasthana @kubeflow/kubeflow-steering-committee @akgraner
> Add Emeritus Approvers Info to the Kubeflow Membership

- content/en/docs/components/pipelines/legacy-v1/installation/standalone-deployment.md
Update of two links to machines types and kustomize.
> Fix links to machine types and kustomize configuration

- content/en/docs/components/central-dash/customize.md
Fixed outdated key in the `externalLinks` section of the ConfigMap example. 
Fixes #3803 
- Replaced `url` with `link` in the `externalLinks` section of the ConfigMap example.
- The change applies to two instances of the `url` key.
```
"externalLinks": [
{
"type": "item",
"iframe": false,
"text": "Kubeflow Website",
"url": "https://www.kubeflow.org/",
"icon": "launch"
}
```
```
"externalLinks": [
{
"type": "item",
"iframe": false,
"text": "Kubeflow Website",
"link": "https://www.kubeflow.org/",
"icon": "launch"
}
```
> Fix outdated 'url' key to 'link' in ConfigMap example

- content/en/docs/components/pipelines/legacy-v1/installation/localcluster-deployment.md
[Documentation](https://www.kubeflow.org/docs/components/pipelines/legacy-v1/installation/localcluster-deployment/#deploying-kubeflow-pipelines) for deploying KFP standalone locally has the following two inconsistencies around pns.
1. The install step installs the `platform-agnostic` manifest, which is based on the emissary executor.
```kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/env/platform-agnostic?ref=$PIPELINE_VERSION"```
However, the uninstall step uninstalls the `platform-agnostic-pns` executor.
```kubectl delete -k "github.com/kubeflow/pipelines/manifests/kustomize/env/platform-agnostic-pns?ref=$PIPELINE_VERSION"```
(**Why are we uninstalling a different version from what was installed???**)
2. There is a note that "Process Namespace Sharing (PNS) is not …
> fix: inconsistent deploy documentation pns references

- content/en/docs/components/katib/getting-started.md
- content/en/docs/components/katib/user-guides/metrics-collector.md
**What this PR does:**
Before creating Katib Experiments, the label for metrics collector injection `katib.kubeflow.org/metrics-collector-injection: enabled` should be presented in the namespace. 
This PR updates the user guide to inform users of the effect of this label.
**Which issue(s) this PR fixes:**
Fixes https://github.com/kubeflow/katib/issues/2499
> Update user guide for namespace label in Katib Python SDK example

- content/en/docs/about/membership.md
This clarifies the new member instructions to help new members know what needs to happen after their PR is merged. 
Note: this is related to a companion PR on the internal-acls repo, which has already merged. https://github.com/kubeflow/internal-acls/pull/737
> clarified new-member instructions

- content/en/docs/components/spark-operator/getting-started.md
This PR updates Spark Operator Metrics section in the documentation with correct metrics for Spark Application and Work Queue metrics.
Addresses [Issue](https://github.com/kubeflow/spark-operator/issues/2417).
> Update Spark Operator Prometheus Metrics Guide

- content/en/_redirects
Fixes: https://github.com/kubeflow/trainer/issues/2433
This should fix this redirect: https://www.kubeflow.org/docs/components/training
/assign @kubeflow/wg-training-leads @gaocegege
> fix(trainer): Fix redirect for /components/training/

- content/en/docs/started/installing-kubeflow/index.md
We are trying to reduce confusion for users who are trying to figure out which distributions support their Kubernetes clusters.
This PR makes the following changes:
- Rewords `"All Certified Kubernetes Distributions"` to `"Multiple"`
- I have __only__ updated deployKF, if other distributions want, they can copy this in their own PRs.
- Also adds a `[list]` reference, which links to that distribution's list of supported Kubernetes platforms.
- Makes the `[version matrix]` and `[release notes]` references lowercase (makes it less busy on screen)
> Reword "All Certified Kubernetes Distributions" to "Multiple" 

- content/en/_redirects
- content/en/docs/components/trainer/legacy-v1/_index.md
- content/en/docs/components/trainer/legacy-v1/explanation/_index.md
- content/en/docs/components/trainer/legacy-v1/explanation/fine-tuning.md
- content/en/docs/components/trainer/legacy-v1/getting-started.md
- content/en/docs/components/trainer/legacy-v1/installation.md
- content/en/docs/components/trainer/legacy-v1/overview.md
- content/en/docs/components/trainer/legacy-v1/reference/_index.md
- content/en/docs/components/trainer/legacy-v1/reference/architecture.md
- content/en/docs/components/trainer/legacy-v1/reference/distributed-training.md
- content/en/docs/components/trainer/legacy-v1/reference/fine-tuning.md
- content/en/docs/components/trainer/legacy-v1/user-guides/_index.md
- content/en/docs/components/trainer/legacy-v1/user-guides/fine-tuning.md
- content/en/docs/components/trainer/legacy-v1/user-guides/jax.md
- content/en/docs/components/trainer/legacy-v1/user-guides/job-scheduling.md
- content/en/docs/components/trainer/legacy-v1/user-guides/paddle.md
- content/en/docs/components/trainer/legacy-v1/user-guides/prometheus.md
- content/en/docs/components/trainer/legacy-v1/user-guides/pytorch.md
- content/en/docs/components/trainer/legacy-v1/user-guides/tensorflow.md
- content/en/docs/components/trainer/legacy-v1/user-guides/xgboost.md
We forgot to add deprecation message to all Training Operator v1 docs.
Also, I fixed the PyTorch guide redirect.
/assign @kubeflow/wg-training-leads @astefanutti @Electronic-Waste @deepanker13 @varodrig @rimolive @hbelmiro @thesuperzapper
> trainer: Add deprecation warning to Training Operator v1 docs

- content/en/docs/components/katib/user-guides/metrics-collector.md
See https://github.com/kubeflow/katib/pull/2467
> katib metrics-collector: mention supported writers

- content/en/events/upcoming-events/gsoc-2025.md
**Checklist:**
As I discussed with @andreyvelich in the slack, we agreed that WG AutoML/Training should remove project 9 because our effort is limited and can accept at most 3 projects. And I propose to add @rudeigerc as backup mentor for `Support Volcano Scheduler in Kubeflow Trainer`. He has rich experience in scheduling and will surely help us a lot with the project.
So I:
-  Remove project 9
- Add @rudeigerc as mentor for `Support Volcano Scheduler in Kubeflow Trainer`
/cc @kubeflow/kubeflow-steering-committee @kubeflow/wg-training-leads @kubeflow/wg-automl-leads @rudeigerc
Closes: #
/area gsoc
---
> gsoc: remove project 9 & update mentors

- content/en/docs/started/support.md
The goal is to improve the status quo. It also removes some bankrupt companies or companies that are not actively involved with Kubeflow anymore.
Here is a screenshot
**Checklist:**
> Update of the support page

- content/en/events/upcoming-events/gsoc-2025.md
> fix: SeaweedFS PoC link in GSoC project

- content/en/docs/components/trainer/getting-started.md
**Checklist:**
Update the get-started example of trainer according to changes in `train()` API: https://github.com/kubeflow/trainer/pull/2513
- Rename `Trainer` to `CustomTrainer`
/cc @andreyvelich 
Closes: #
/area trainer
---
> trainer: update get-started example of trainer.

- content/en/docs/components/trainer/getting-started.md
**Checklist:**
The getting-started page for Kubeflow Trainer requires updates to reflect the following API changes:
- The `TrainerClient().train` function now takes a `runtime` instead of a `runtime_ref`.
- A `TrainJob` no longer has the `components` attribute. The `steps` attribute is now used instead.
- `Step` names are prefixed with `node-` instead of `trainer-node-`.
A minor spelling change (`defines` to `define`) was also updated in this PR.
Closes: #
/area trainer
/area website
---
> trainer: update getting-started.md to reflect API changes

- content/en/events/upcoming-events/gsoc-2025.md
/area gsoc
Replaces https://github.com/kubeflow/website/pull/4060
This is a quick update to link to the proposal template added to `kubeflow/community` in https://github.com/kubeflow/community/pull/843.
It should fix the failing builds because it has the head of master as its base.
> gsoc: add proposal guide to 2025 page

- README.md
- config.toml
- layouts/partials/footer.html
- netlify.toml
- package-lock.json
- package.json
/area website
This PR fixes the error introduced by https://github.com/kubeflow/website/pull/4083 where fontawsome is loaded multiple times on every page, and has two conflicting versions. This was a serious issue because it affects page load times, but also because the `integrity` arg was not set on the `<link>` which was added to the footer.
It also partially reverts the readme update which put an image above the title of the root readme. This hurts SEO of the repo, because the title needs to be at the top. But it also implies that this is the "kubeflow" repo (when its just the website source). Note, we already have a logo on the [`kubeflow/kubeflow` readme](https://github.com/kubeflow/kubeflow), and it sits below the title.
__WARNING:__ after this PR, everyone will need to stop doing …
> website: properly update fontawsome + partial revert #4083

- content/en/docs/components/pipelines/concepts/component.md
This is a major update to the component concept page for KFP. The old page was confusing and lacked important information for the main KFP users (ML engineers). This update seeks to fix this by treating the "component" from the perspective of an MLE, providing a useful introduction on what a component is, and how to use it in the KFP world.
**Checklist:**
Closes: #
---
> pipelines: updated KFP component concept page

- content/en/docs/started/installing-kubeflow/index.md
kubeflow training-operator repo is renamed to [trainer](https://github.com/kubeflow/trainer) now, so update the link accordingly
> website: update the link from training-operator to trainer

- layouts/shortcodes/alpha-status.html
- layouts/shortcodes/beta-status.html
🔬 the spaces in the if/then/else does not count towards the necessary space in the rendered text 
@varodrig @andreyvelich @thesuperzapper @rimolive @hbelmiro 
**Checklist:**
Closes: #
/area website
---
> website: fix Alpha, Beta tooltip box (missing space)

- content/en/docs/components/model-registry/getting-started.md
- content/en/docs/components/model-registry/overview.md
Guide the Reader to the correct issue-selector screen on the repo
@varodrig @andreyvelich @milosjava
@rareddy @rimolive 
**Checklist:**
Closes: #
---
> model-registry: better link to issue selector screen

- content/en/docs/components/pipelines/operator-guides/configure-object-store.md
[s3forcePathStyle](https://github.com/kubeflow/pipelines/blob/master/backend/src/v2/config/s3.go#L38C30-L38C44) was added in https://github.com/kubeflow/pipelines/pull/11246
> add a new s3.forcePathStyle configuration parameter to the samples.

- config.toml
- layouts/partials/version-banner.html
**Checklist:**
This PR updates the archive banner text so when `archived_version=true` it's more clear that the branch is archived.
___NOTE:__ this PR only updates the templates so that when we next fork off the `main` branch to a `v1.11-branch` it is easy to just set `archived_version=true`_
___NOTE 2:__ this is not a new change, it has already been done to all the old branches, but this means its less work for future versions._
/area website
> website: update main branch archive banner

- content/en/docs/components/spark-operator/developer-guide.md
- content/en/docs/components/spark-operator/overview/_index.md
- content/en/docs/components/spark-operator/user-guide/using-sparkapplication.md
- content/en/docs/components/spark-operator/user-guide/working-with-sparkapplication.md
**Checklist:**
Closes: #4088 
/area spark-operator
---
> spark-operator: Remove docs associated with sparkctl

- config.toml
- layouts/partials/head.html
- layouts/partials/version-banner.html
**Checklist:**
This PR archives the 1.9 branch in the same way as we have done for all past releases, it adds a warning banner to say please use the latest version by setting `archived_version=true`.
This should be less work in future versions after https://github.com/kubeflow/website/pull/4119 is merged, because we will only need to set `archived_version=true`, not update the template to add the banner.
/area website
> website: add archive banner for 1.9 branch

- config.toml
- layouts/partials/version-banner.html
**Checklist:**
This is a back port of https://github.com/kubeflow/website/pull/4119 to the `v1.10-branch`, so that we only have to set the `archived_version=true` flag when we release 1.11 (and want to add the archive banner to the 1.10 branch.
___NOTE:__ this does NOT add the banner right now to the 1.10 branch, it just makes it a single config to turn it on when we want to in the future (see the preview to confirm)._
/area website
> website: update (but not set) archive banner for 1.10 branch

- config.toml
**Checklist:**
Updated the GSoC 2025 status in the navigation menu from "Coming Soon" to "Application Closed" to reflect the current application status.
Closes: # (no specific issue)
/area gsoc
/area website
> gsoc: Update GSoC 2025 status to Application Closed

- .github/pull_request_template.md
- .github/workflows/pr_title_check.yaml
**Checklist:**
- [*] You have [signed off your commits](https://www.kubeflow.org/docs/about/contributing/#sign-off-your-commits)
- [*] Ensure you follow best practices from our guide. [Contributing](https://github.com/kubeflow/website/blob/master/content/en/docs/about/contributing.md). 
- [*] You have included screenshots when changing the website style or adding a new page.
- Closes: #4050 
- Closes: #4079 
/area website
> website: added logic to the pr_title_check.yaml to put error message as a comment

- content/en/docs/components/katib/user-guides/llm-hp-optimization.md
- content/en/docs/components/trainer/legacy-v1/user-guides/fine-tuning.md
…es config, remove unsupported params
**Checklist:**
As per andrey's recommendation I added the changes mentioned in the following screenshots attached. A minimal work.
Closes: #2522
/area katib 
/area website 
---
> katib: Update LLM HP tuning guide to clarify tunable fields and fix resource section

- assets/scss/_styles_project.scss
- config.toml
**Checklist:**
Partially reverts: https://github.com/kubeflow/website/pull/4136
Currently, after https://github.com/kubeflow/website/pull/4136 the header of the website is broken, it does not wrap correctly and will extend beyond the edge of the screen, causing it to not be possible to see the version or dark/light drop-downs.
This PR:
- reverts the incorrect style update which prevented wrapping of header text on smaller screens
- reduces the width of the announcements text (say "Kubeflow Summit" which is shorter)
- uses the standard format of "date", "location" for the icons below the Kubeflow Summit entry
- comments out the GSOC one, as we can only fit 3 announcements, and GSOC is already underway, so doesn't need a header announcement
/area website
---
> website: fix header and announcements

- .github/workflows/pr_title_check.yaml
- content/en/docs/components/trainer/operator-guides/migration.md
**Checklist:**
This PR adds a new migration guide under the Kubeflow Trainer documentation.
It provides users with a clear migration path from the legacy Training Operator (v1) APIs (e.g., PyTorchJob) to the new unified Trainer V2 APIs (e.g., TrainingRuntime). The guide includes:
- A side-by-side example of migrating a PyTorchJob to TrainingRuntime.
- A compatibility table for Trainer versions, CRDs, and Kubernetes requirements.
- Notes on key changes, deprecations, and architectural improvements in Trainer V2.
This contribution addresses the request in [kubeflow/trainer#2412 [(comment)]](https://github.com/kubeflow/trainer/issues/2412#issuecomment-3054291878)
> trainer: migration guide from training operator to Trainer V2

- content/en/docs/components/model-registry/reference/architecture.md
Follow-up to https://github.com/kubeflow/model-registry/issues/865
**Checklist:**
- [n/a] You have included screenshots when changing the website style or adding a new page.
/area model-registry
/hold for review and alignment with https://github.com/kubeflow/community/pull/871#pullrequestreview-3028214847
cc @Al-Pragliola
> model-registry: update architecture

- content/en/docs/components/trainer/getting-started.md
- content/en/docs/components/trainer/user-guides/pytorch.md
- content/en/docs/started/architecture.md
Since we've moved `pyproject.toml` to root in https://github.com/kubeflow/sdk/pull/61, I updated its references on the website
/assign @andreyvelich
> trainer: Update kubeflow sdk reference

- content/en/docs/components/trainer/operator-guides/installation.md
We should appropriately set the `VERSION` env during installation.
We noticed that in some shell environment, it won't get saved without `export`
/cc @kubeflow/wg-training-leads @astefanutti @raravena80
> trainer: Fix the version in installation guide

- content/en/docs/components/trainer/operator-guides/runtime.md
As we discussed here, we agreed on the `trainer.kubeflow.org/support: deprecated` label to the Kubeflow Trainer deprecated runtimes: https://github.com/kubeflow/trainer/pull/2791/files#r2307816311
/cc @kubeflow/kubeflow-trainer-team @astefanutti
> trainer: Change label for deprecated runtimes

- content/en/docs/about/community.md
Add slack link of `kubeflow-outreach` to the community page. https://www.kubeflow.org/docs/about/community/#slack-channels
Closes: #4199
> website: kubeflow outreach slack link
