kubeflow/website

- OWNERS
> Add agwl to OWNERS of kubeflow/website

- themes/kube/static/css/kube.css
- themes/kube/static/css/master.css
Some css is not valid like: `xx: 1rem/4` or `overflow: none`, and some can be optimized.
Now fixed these small bugs.
> optimize css

- themes/kube/layouts/partials/footer.html
- themes/kube/layouts/partials/header.html
> Remove header and footer

- OWNERS
> Add pdmack to OWNERS

- content/docs/getting-started-gke.md
Fixes https://github.com/kubeflow/website/issues/20
/assign @abhi-g
> Getting started with GKE Doc

- content/docs/getting-started-gke.md
* PUlls in the doc changes from kubeflow/kubeflow#956
> Copy over latest gke_docs from the kubeflow repository.

- content/docs/contributing.md
- content/docs/started/getting-started.md
making a couple of draft documents accessible
- getting-started
- contributing
> Make drafts accessible

- content/docs/started/getting-started-gke.md
Add missing steps, resolve confusing parts in gke doc.
> update gke doc

- OWNERS
adding myself as one of the owners.
> Added myself as one of the approvers and reviewers

- content/docs/started/getting-started-gke.md
Related to: kubeflow/kubeflow#912
> Add instructions about cloning the ksonnet app into a source repository.

- themes/kf/layouts/index.html
> update community section on FP.

- content/docs/started/getting-started-minikube.md
- content/docs/started/getting-started.md
- themes/kf/layouts/docs/single.html
Added installation steps for Minikube, and for deploying Kubeflow using bootstratpper. Resolves #19
> Updated minikube deployment document

- content/docs/started/getting-started.md
also reformat to replace ```\r\n``` with ```\n```
> add bootstrapper doc to getting-started

- content/docs/started/getting-started-gke.md
Fixes https://github.com/kubeflow/website/issues/48
/assign @jlewi
> Fix link in gke doc

- content/blog/_index.md
- themes/kf/layouts/blog/list.html
- themes/kf/layouts/blog/single.html
Add missing files from blogs section layout.
> Blogs layout

- content/docs/user_guide.md
Moving user guide from kubeflow repo for consistency
> Adding user guide doc

- content/docs/user_guide.md
Should be OK to point users at the latest.
<fingers-crossed>
/assign @abhi-g 
/assign @ewilderj
> Bump ksonnet reference to 0.11.0

- content/docs/started/getting-started.md
Sorry, missed this ref. :-(
/assign @abhi-g 
/assign @ewilderj
> ks version update in GS guide

- content/docs/user_guide.md
/assign @abhi-g 
/assign @ewilderj
> Fix some markdown issues in the UG

- content/docs/about/contributing.md
- content/docs/about/user_guide.md
- content/docs/started/getting-started-gke.md
- content/docs/started/getting-started-minikube.md
- content/docs/started/getting-started.md
* Explain how to use the new simple example prototype to generate a job.
* Fix some broken links
* Fix #62 - broken links to user guide
* Add instructions for doing upgrades; Fix #57
> Update TFJob docs and document how to upgrade Kubeflow

- content/docs/about/pytorch.md
* The docs are based on the README
https://github.com/kubeflow/pytorch-operator
> Add PyTorch docs to the website.

- content/docs/started/getting-started-gke.md
- content/docs/started/getting-started.md
* The getting started process now uses deploy scripts and
doesn't rely on bootstrapper.
> Update the docs for v0.2.1

- content/docs/about/user_guide.md
- content/docs/started/getting-started-gke.md
- content/docs/started/getting-started.md
* 0.2.2 includes some fixes to deploy.sh.
* Update the user_guide to use the new deploy.sh script. Rather than duplicate the actual commands 
in the script just refer users to the deploy script since the commands will likely get outdated.
Fix kubeflow/kubeflow#1201
> Bump the Kubeflow version from 0.2.1 to 0.2.2.

- content/docs/started/getting-started-gke.md
* Add warning about not checking service account keys into source control.
> * Fix indentation.

- content/docs/guides/components/tfserving.md
From https://github.com/kubeflow/kubeflow/blob/master/components/k8s-model-server/request-logging.md
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/125)
> Add request logging doc for TF serving

- content/docs/guides/components/seldon.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/127)
> Update docs for Seldon 0.2 update

- OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/132)
> Add richardsliu to OWNERS in kubeflow/website

- content/docs/guides/components/tftraining.md
- content/docs/guides/monitoring.md
* Fix a typo in one of the monitoring.md queries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/134)
> Add instructions for fetching TFJob logs by pod labels.

- content/docs/guides/troubleshooting.md
- content/docs/started/getting-started-gke.md
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/131)
> Add doc on AVX2 and Haswell

- content/docs/guides/components/tfserving.md
Slight refactor and inclustion of S3 to our tf-serving docs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/135)
> Create S3 documentation for tf-serving

- .gitignore
- content/docs/started/getting-started-minikube.md
Add one-liner install commands for kubectl & minikube
Ignore .DS_Store files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/140)
> Add one-liner install commands

- config.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/149)
> Change version name in v0.2 website

- OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/154)
> Added sarahmaddox to website OWNERS.

- content/docs/guides/components/ksonnet.md
- content/docs/guides/requirements.md
- content/docs/started/getting-started.md
Clarify cluster setup instructions
Remove broken links
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/150)
> Add links to self-paced scenarios

- content/docs/started/getting-started-gke.md
- content/docs/started/getting-started.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/158)
> Document how to use GKE using kfctl

- content/docs/guides/components/tftraining.md
- content/docs/guides/monitoring.md
* Fix a typo in one of the monitoring.md queries.
Cherrypick #134
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/142)
> Add instructions for fetching TFJob logs by pod labels to 0.2 instructions. (#134)

- content/docs/about/contributing.md
- themes/kf/layouts/index.html
Added a call to participate in UX Research on Contributions page. Also added a link to Contributing page from the home page Community section.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/156)
> Added call for UX Research participation.

- content/docs/guides/components/ksonnet.md
- content/docs/guides/requirements.md
- content/docs/guides/troubleshooting.md
- content/docs/started/getting-started.md
Fixes issue #152
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/153)
> Adds context to ksonnet guide and fixes various references

- content/docs/about/contributing.md
- themes/kf/layouts/index.html
Cherry pick UX participation changes into v0.2 as well, so that its live on kubeflow.org
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/161)
> Added call for UX Research participation. (#156)

- content/blog/announcing_kubeflow_0.2.md
- content/docs/guides/components/mpi.md
Closes #77
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/159)
> Add MPI job docs to the website

- content/docs/about/events.md
Fixes #157 
Update links to past events and add videos & slides
Add links to upcoming events
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/162)
> Add events links

- content/blog/announcing_kubeflow_0.2.md
- content/docs/guides/components/mpi.md
/assign @jlewi 
fix #77
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/164)
> cherry pick mpi job docs

- content/docs/guides/components/jupyter.md
Added two sections
* Submitting k8s resources from Jupyter Notebook
* Building docker images from Jupyter Notebook on GCP
/assign @kunmingg @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/166)
> Add sections to jupyter notebook doc

- content/docs/guides/advanced.md
- content/docs/guides/components/jupyter.md
- content/docs/guides/components/ksonnet.md
- content/docs/guides/troubleshooting.md
- content/docs/guides/usage-reporting.md
Update to kubeflow/kubeflow :  https://github.com/kubeflow/kubeflow/pull/1207
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/91)
> Split kubeflow-core into individual prototypes

- content/docs/about/events.md
This is my first pull request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/170)
> Fix 3rd-level indentation for videos and slides (#169)

- content/docs/about/events.md
Add events links (#162)
* Add links
Update links to past events and add videos & slides
Add links to upcoming events
* Add origins video & interview with jlewi
* Fix title
* Update start time of video
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/179)
> Cherry-picking Michelle's update to links into v0.2

- content/docs/guides/components/mxnet.md
Add MXNet operator into website repo for doc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/172)
> Add mxnet operator (https://github.com/kubeflow/community/issues/136)

- content/docs/about/kubeflow.md
- content/docs/guides/components/components.md
At the high level of our docs, we tend to describe our mission rather than giving an overview of how we accomplish that mission.
This PR:
* Updates the "About Kubeflow" page to include a practical description of what Kubeflow is.
* Adds a "Components Overview" page as a handy destination to link to, from the above page and potentially from other pages too.
Fixes issue #183
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/184)
> Added a practical description of Kubeflow

- content/docs/guides/requirements.md
- content/docs/started/getting-started-gke.md
- content/docs/started/getting-started.md
This PR adds a few improvements to the docs, for better flow and understanding:
* Improves the introduction to the guides section on the "Requirements" page.
* Fixes product branding, to help readers identify the various products (what is GCFS vs GCS, or is IAP a Google Cloud product or a generic protocol, or what is GCP/GCR/GKE, for example) and to conform to Google Cloud branding guidelines.
* Fixes a few links and other minor errors in the generic getting-started guide and the GKE getting-started guide.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/182)
> Doc UX improvements

- content/docs/about/kubeflow.md
- content/docs/guides/components/components.md
Pulling in Sarah's update to v0.2 branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/193)
> Added a practical description of what Kubeflow is. (#184)

- content/docs/guides/components/jupyter.md
- content/docs/guides/usage-reporting.md
Fix: https://github.com/kubeflow/website/issues/160
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/190)
> Disable reporting

- content/docs/started/getting-started-gke.md
- content/docs/started/getting-started.md
Related to kubeflow/kubeflow#1476
/hold Need to wait for 0.2.5 to be cut.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/206)
> Update the docs to use 0.2.5

- content/docs/about/events.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/209)
> Add event submitted by Josh Bottum

- themes/kf/layouts/partials/footer.html
fixes #217
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/218)
> Added links to Privacy and Terms of Service pages.

- themes/kf/layouts/partials/footer.html
Also add TOS and Privacy terms to v0.2 site.
See https://github.com/kubeflow/website/pull/218 for master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/219)
> Added links to Privacy and Terms of Service pages. (#218)

- content/docs/about/kubeflow.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/221)
> Updating the documentation about the history of Kubeflow and parallel projects.

- content/docs/guides/components/tfbatchpredict.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/194)
> Add a page under component for tf-batch-prediction

- content/docs/guides/monitoring.md
/cc @kunmingg 
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/233)
> Add doc for prometheus

- content/docs/guides/components/tfserving.md
- about http api
- about sending request
Fix https://github.com/kubeflow/kubeflow/issues/1634
/cc @abhi-g
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/238)
> Add more doc for tfserving

- content/docs/guides/components/tfserving.md
/cc @abhi-g
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/239)
> add doc on tf serving with gpu

- content/docs/guides/gke/troubleshooting-gke.md
* The variable is named BACKEND_NAME not BACKEND_ID
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/244)
> Fix a bug in the debug command for GKE.

- content/docs/guides/gke/cloud-filestore.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/248)
> Fix typo in the GCFS docs.

- content/docs/started/getting-started-gke.md
- content/docs/started/getting-started.md
- themes/kf/layouts/shortcodes/kf-stable-tag.html
* Create a shortcode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/249)
> Update the tag to point to v0.3.0

- content/docs/started/getting-started-gke.md
change the directory env in comman line
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/256)
> change KUBEFLOW_SRC to KUBEFLOW_REPO

- content/docs/started/getting-started.md
fixes #266
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/267)
> Modify content to make deployment using download.sh vs deploy from source a bit more clear

- content/docs/started/getting-started-minikube.md
- themes/kf/layouts/shortcodes/kf-stable-tag.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/271)
> Update stable tag to v0.3.1

- content/docs/guides/components/hyperparameter.md
Fix #250 
Signed-off-by: YujiOshima <yuji.oshima0x3fd@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/263)
> update katib doc

- content/docs/about/community.md
Pending merge of [Community #203](https://github.com/kubeflow/community/pull/203)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/282)
> Add a pointer to inclusivity guide

- content/docs/about/kubeflow.md
Fixes: https://github.com/kubeflow/website/issues/268.
Copy "What is Kubeflow" information from master to v0.2-branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/288)
> Change "What is Kubeflow" in v0.2 branch from master branch

- content/docs/about/kubeflow.md
Fixes: https://github.com/kubeflow/website/issues/268.
Copy information "What is Kubeflow" from v0.2 branch to master branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/292)
> Change "What is Kubeflow" in master from v0.2 branch

- content/docs/guides/components/hyperparameter.md
* Remove Deploy Kaitb ( Katib will deploy by default )
* Replace ModelDB with KatibUI
/cc @richardsliu 
Signed-off-by: YujiOshima <yuji.oshima0x3fd@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/295)
> update katib doc use katib-ui

- content/docs/about/events.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/296)
> Add Kubecon Seattle talks & Data@Scale video

- content/docs/started/getting-started-gke.md
Fixes: #278
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/298)
> Add click to deploy as an option to the website.

- content/docs/guides/components/hyperparameter.md
Fixes #293 
Blocked by a fix for [katib-245](https://github.com/kubeflow/katib/issues/245).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/294)
> Change namespace katib -> kubeflow

- themes/kf/layouts/index.html
- themes/kf/sass/src/index.html
Signed-off-by: silenceshell <me@ieevee.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/301)
> should be CPUs

- content/docs/started/getting-started-gke.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/299)
> Fixes click-to-deploy instructions.

- content/docs/guides/components/tftraining.md
Fixes #214
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/300)
> Adds TFJob UI details.

- content/docs/guides/upgrade.md
Fixes: https://github.com/kubeflow/website/issues/309.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/311)
> Fix broken link to upgrade ks

- content/docs/guides/pipelines/pipelines-overview.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/313)
> Fixed links to point to website docs.

- content/docs/guides/components/tftraining.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/315)
> Clarifies relationship between tf-operator and TFJob.

- OWNERS
- content/docs/guides/components/pytorchserving.md
Implements [#1117](https://github.com/kubeflow/kubeflow/issues/1117) and adds dsdinter as reviewer and approver.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/316)
> Add Pytorch Serving documentation in website

- content/docs/guides/requirements.md
Fixes: https://github.com/kubeflow/website/issues/323
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/325)
> Fix broken list in requirements

- content/docs/guides/gke/troubleshooting-gke.md
- content/docs/started/getting-started-gke.md
Fixes [kubeflow/kubeflow #1898](https://github.com/kubeflow/kubeflow/issues/1898)
Updated [GKE quickstart](https://www.kubeflow.org/docs/started/getting-started-gke/) and [troubleshooting](https://www.kubeflow.org/docs/guides/gke/troubleshooting-gke/) docs to address the outstanding issues in [kubeflow/kubeflow #1898](https://github.com/kubeflow/kubeflow/issues/1898).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/326)
> Update GKE getting started docs.

- content/docs/guides/components/istio.md
- add routing path information
- update grafana section
The link for grafana virtual service manifest is depending on https://github.com/kubeflow/kubeflow/pull/2025
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/319)
> Update istio doc

- content/docs/about/contributing.md
* Instructions explain how to send a PR adding yourself to the GitHub org
* Add info about getting credit for companies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/334)
> Update instructions for how to join GitHub org

- content/docs/about/kubeflow.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/343)
> Added a link to the getting-started guide.

- content/docs/guides/gke/gcp-e2e.md
- content/docs/started/getting-started-gke.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/352)
> Clarified how to add an authorized redirect URI.

- content/docs/started/getting-started-minikube.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/350)
> update typos error from Mikikube to Minikube

- content/docs/guides/components/hyperparameter.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/349)
> fix typo error of katib doc

- themes/kf/sass/src/styles/modules/_navigation.sass
- themes/kf/static/css/styles.css
http://joxi.ru/J2bxdlDiXKl6xr
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/354)
> navigation fix (header)

- content/docs/about/contributing.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/358)
> Update typos error in the kubeflow document

- content/docs/guides/gke/gcp-e2e.md
/fixed #353
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/359)
> Fixed port forwarding command.

- content/docs/about/events.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/365)
> Add videos & decks for recent events

- content/docs/guides/components/pytorch.md
- content/docs/guides/components/seldon.md
- content/docs/guides/components/tfserving_new.md
- content/docs/guides/components/tftraining.md
Try tutorials using AWS EKS and notice several documentation are outdated and need to update.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/362)
> Update aws related documents for 0.4 release

- content/docs/about/kubeflow.md
Fixes: https://github.com/kubeflow/website/issues/369
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/372)
> Remove duplicate information from "What is Kubeflow"

- content/docs/guides/accessing-uis.md
Fixes: https://github.com/kubeflow/website/issues/373
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/375)
> Change port-forward ambassador from pod to service 

- content/docs/about/events.md
Add links to slides
Replace David's name with Holden's for Strata workshop
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/368)
> Add "https://" to codelab link

- content/docs/started/getting-started-gke.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/377)
> Clarified use of name fields in OAuth instructions.

- themes/kf/layouts/shortcodes/kf-stable-tag.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/380)
> Update latest KF stable release to 0.3.5

- content/docs/guides/gke/gcp-e2e.md
See issue [#261](https://github.com/kubeflow/website/issues/261).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/387)
> Added a note that the GKE e2e guide needs upgrading.

- content/docs/started/getting-started.md
See: https://github.com/kubeflow/kubeflow/issues/1914
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/390)
> Update getting started guide by adding zone.

- content/docs/guides/components/modeldb.md
Fixes https://github.com/kubeflow/kubeflow/issues/1861
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/364)
> Docs for using ModelDB

- content/docs/about/docs.md
- content/docs/guides/components/istio.md
- content/docs/guides/gitops-for-kubeflow.md
- content/docs/guides/gke/gcp-e2e.md
- content/docs/guides/pipelines/pipelines-metrics.md
- content/docs/guides/pipelines/pipelines-overview.md
- content/docs/started/getting-started-gke.md
- resources/_gen/assets/js/js/search.js_b4bb3e7b21b43e920b7c367ff787d383.content
Used Bootstrap styling to add margins, padding, border where necessary to improve the way screenshots appear on the page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/395)
> Added styling to the screenshots that needed it

- content/docs/guides/components/mpi.md
This is to be consistent with mpi-operator's [README.md](https://github.com/kubeflow/mpi-operator/blob/master/README.md) with slight re-organization, copy edits, more details, and some references.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/400)
> Update MPI Operator guide

- README.md
My merge in PR #397 caused an unexpected error, so I've recreated the change in a new PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/401)
> Added Docsy theme info to the docs README.

- OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/405)
> Add pipelines team to OWNERS.

- content/docs/guides/pipelines/output-viewer.md
/metadata.json should be /mlpipeline-ui-metadata.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/404)
> Corrected file name

- content/docs/guides/pipelines/output-viewer.md
- Corrected metadata file name to match code
- Added the values of the `type` field for each plot type
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/403)
> Corrections to "Use an Output Viewer"

- layouts/shortcodes/ksonnet-min-version.html
Signed-off-by: Abhilash Pallerlamudi <stp.abhi@gmail.com>
Fixes kubeflow/kubeflow#2250
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/408)
> Suggest KubeFlow to use ksonnet 0.13.1 as minimal version

- content/docs/about/contributing.md
This fixes a couple of typos I found while reading CONTRIBUTING.md.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/411)
> Fix a couple of typos in CONTRIBUTING.md

- content/docs/guides/components/tftraining.md
Signed-off-by: Abhilash Pallerlamudi <stp.abhi@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/414)
> update doc to reflect current apiVersion of tfjobs.kubeflow.org CRD

- content/docs/guides/components/pytorch.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/413)
> Add note about beta version in Kubeflow 0.4.0 for Pytorch operator

- content/docs/guides/pipelines/pipelines-samples.md
same as https://github.com/kubeflow/website/pull/407, update pipeline version to 0.1.7.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/426)
> update Kubeflow Pipelines SDK version

- content/docs/components/hyperparameter.md
Fixes https://github.com/kubeflow/website/issues/438
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/439)
> Corrected some syntax and formatting.

- content/docs/pipelines/pipelines-concepts.md
- content/docs/pipelines/pipelines-metrics.md
- content/docs/pipelines/pipelines-ui.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/442)
> Updated document for pipeline.

- content/docs/about/events.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/451)
> Add links for Data Day TX

- content/docs/examples/resources.md
Fix spelling of Katacoda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/463)
> Add links to codelabs & qwiklabs

- content/docs/pipelines/enable-gpu-and-tpu.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/460)
> Create guide on how to use GPU and TPU on KFP

- config.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/468)
> Release website for 0.4 branch

- content/docs/pipelines/pipelines-metrics.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/467)
> Add conventions on the metrics file.

- content/docs/started/getting-started.md
Added useful instructions on how to remove KubeFlow, I happen to use this if I broke something in KF and want to reset it. It was not in the documentation but I can imagine it helps someone.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/464)
> Added instructions to remove KubeFlow again

- content/docs/pipelines/enable-gpu-and-tpu.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/465)
> Removed the "advanced user" statement

- content/docs/components/ksonnet.md
- content/docs/started/getting-started.md
- layouts/shortcodes/ksonnet-min-version.html
Removes obsolete info from ksonnet guide and tidies up some text and links.
Fixes https://github.com/kubeflow/website/issues/459
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/472)
> Fixes the ksonnet guide

- content/docs/started/getting-started-gke.md
Also makes a few wording tweaks.
Fixes https://github.com/kubeflow/website/issues/479
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/481)
> Fixes URL in the GKE get-started guide.

- config.toml
- content/search.md
- layouts/partials/sidebar-tree.html
- resources/_gen/assets/js/js/search.js_b4bb3e7b21b43e920b7c367ff787d383.content
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/471)
> Added search to the Kubeflow website.

- config.toml
- google65401334ad4c38b1.html
- layouts/partials/head.html
- layouts/partials/seo_schema.html
- layouts/sitemap.xml
Fixes https://github.com/kubeflow/website/issues/98
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/473)
> Improving website SEO.

- content/docs/about/events.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/488)
> Add NEXT & AI NEXTCon

- content/docs/other-guides/monitoring.md
/cc @abhi-g
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/496)
> Fix link in prometheus section

- content/docs/other-guides/advanced.md
The component is not jupyterhub, just jupyter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/495)
> Fix jupyter component name

- content/docs/pipelines/build-component.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/497)
> Update outdated links to kfp DataProc components

- layouts/partials/footer.html
- layouts/partials/navbar.html
Fixes https://github.com/kubeflow/website/issues/482
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/500)
> Adjusted header and footer to open external links in new tab.

- content/docs/pipelines/pipelines-quickstart.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/461)
> Add instruction to access UI without IAP

- content/docs/components/ksonnet.md
- content/docs/gke/gcp-e2e.md
- content/docs/started/getting-started-gke.md
- content/docs/started/requirements.md
- layouts/shortcodes/ksonnet-min-version.html
Fixes https://github.com/kubeflow/website/issues/491
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/499)
>  Added direct links to ksonnet downloads and directed all installation guides to the ksonnet page

- content/docs/components/tftraining.md
Add ks init command and update ks generate command
fixes https://github.com/kubeflow/website/issues/501
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/502)
> Fix ks command to run tfjob

- content/docs/about/events.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/503)
> Added KF Contributor Summit 2019 to Events Calendar

- config.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/509)
> Added Google Analytics and a feedback option to the website.

- content/docs/components/seldon.md
Fix a bad link in seldon.md, there is no web in the old link. Thanks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/511)
> fix a bad link in seldon doc

- content/docs/pipelines/build-pipeline.md
- bump SDK release version
- clarify some instructions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/512)
> build-pipeline.md nits

- content/docs/pipelines/output-viewer.md
The changes are made here: https://github.com/kubeflow/pipelines/pull/897.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/517)
> [Pipelines] Doc changes for markdown viewer

- content/docs/pipelines/reusable-components.md
Addresses issue https://github.com/kubeflow/website/issues/525
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/528)
> Added an index of reusable Kubeflow Pipelines components.

- content/docs/started/getting-started-minikf.md
Add instructions for installing MiniKF, as presented at Kubeflow Day LA at SCaLE 17x.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/534)
> Add MiniKF guide for Kubeflow

- content/docs/pipelines/upgrade.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/527)
> add instruction to upgrade to specific version

- content/docs/components/jupyter.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/523)
> Added a doc on how to create kubeflow compatible custom Jupyter Image

- OWNERS
added dansanche to OWNERs, at the suggestion of sarahmaddox@
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/542)
> Add dansanche to owners

- content/docs/components/istio.md
while reading Istio document, met some minor problems such as link is not right and some items number are not reasonable, the PR is going to fix those problems. Thanks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/543)
> fix some minor problems on istio page

- content/docs/components/istio.md
Fixed #544
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/554)
> Fixed 2 links in the Istio guide.

- content/docs/about/events.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/552)
> Adding Kubeflow Contributor Summit slides

- content/docs/started/getting-started-gke.md
Fixes #533
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/556)
> Expanded and clarified the GCP setup.

- content/docs/pipelines/sdk/static-type-checking.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/562)
> add dsl type check doc

- content/docs/components/mxnet.md
Update documentation for [PR#2909](https://github.com/kubeflow/kubeflow/pull/2909).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/571)
> mxnet documentation for v1beta1

- README.md
- content/_redirects
- content/docs/components/tfserving_new.md
- content/docs/components/tftraining.md
- content/docs/components/trtinferenceserver.md
- content/docs/gke/_index.md
- content/docs/gke/cloud-filestore.md
- content/docs/gke/custom-domain.md
- content/docs/gke/customizing-gke.md
- content/docs/gke/deploy/_index.md
- content/docs/gke/deploy/deploy-cli.md
- content/docs/gke/deploy/deploy-ui.md
- content/docs/gke/deploy/next-steps.md
- content/docs/gke/deploy/oauth-setup.md
- content/docs/gke/deploy/project-setup.md
- content/docs/gke/gcp-e2e.md
- content/docs/gke/private-clusters.md
- content/docs/gke/troubleshooting-gke.md
- content/docs/other-guides/accessing-uis.md
- content/docs/pipelines/pipelines-overview.md
- content/docs/pipelines/pipelines-quickstart.md
- content/docs/pipelines/tutorials/build-pipeline.md
- content/docs/pipelines/tutorials/pipelines-tutorial.md
- content/docs/pipelines/upgrade.md
- content/docs/started/getting-started-gke.md
- content/docs/started/getting-started-minikube.md
- content/docs/started/getting-started.md
Typographical and link fixes as followup to PR https://github.com/kubeflow/website/pull/568.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/582)
> Textual and link fixes as followup to PR #568

- content/docs/gke/deploy/deploy-ui.md
- content/docs/gke/deploy/monitor-iap-setup.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/581)
> Add a page on monitoring and debuggin IAP setup.

- content/docs/components/modeldb.md
Updating the setup and usage documentation for ModelDB v2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/602)
> Update documentation for ModelDB v2.

- content/docs/fairing/_index.md
- resources/_gen/assets/js/js/search.js_b4bb3e7b21b43e920b7c367ff787d383.content
fixes #590
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/599)
> Create a Fairing section for the documentation

- content/docs/pipelines/upgrade.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/610)
> update pipeline upgrade doc with new kfctl

- content/docs/pipelines/sdk/dsl-overview.md
- content/docs/pipelines/sdk/dsl-recursion.md
- content/docs/pipelines/sdk/enable-gpu-and-tpu.md
- content/docs/pipelines/sdk/static-type-checking.md
fixes https://github.com/kubeflow/website/issues/524
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/613)
> Added an introduction to the Pipelines DSL

- content/docs/pipelines/reference/_index.md
- content/docs/pipelines/reference/component-spec.md
fixes https://github.com/kubeflow/website/issues/570
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/604)
> Added the component specification

- content/docs/reference/downloads.md
Fixes https://github.com/kubeflow/website/issues/598
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/607)
> Added a downloads page for kfctl

- content/docs/pipelines/concepts/component.md
- content/docs/pipelines/pipelines-overview.md
- content/docs/pipelines/reusable-components.md
- content/docs/pipelines/sdk/best-practices.md
- content/docs/pipelines/sdk/build-component.md
- content/docs/pipelines/sdk/component-development.md
- content/docs/pipelines/sdk/dsl-overview.md
fixes https://github.com/kubeflow/website/issues/609
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/624)
> Linked up various new pages

- content/docs/components/hyperparameter.md
- content/docs/components/istio.md
- content/docs/components/pytorchserving.md
- content/docs/components/seldon.md
- content/docs/components/tfbatchpredict.md
- content/docs/components/tfserving_new.md
- content/docs/components/tftraining.md
- content/docs/other-guides/troubleshooting.md
fixes https://github.com/kubeflow/website/issues/619
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/625)
> Clarified meaning of environment in KF_ENV

- content/docs/pipelines/upgrade.md
fixes https://github.com/kubeflow/website/issues/612
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/629)
> Fixed typo 'anys'

- content/docs/about/_index.md
- content/docs/components/_index.md
- content/docs/examples/resources.md
- content/docs/fairing/_index.md
- content/docs/gke/_index.md
- content/docs/other-guides/_index.md
- content/docs/pipelines/_index.md
- content/docs/started/_index.md
- content/docs/use-cases/_index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/637)
>  Multiplied page weights by 10 to make it easier to add more pages

- content/docs/components/hyperparameter.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/628)
> Fixed links to katib random example

- content/docs/components/tftraining.md
issue: https://github.com/kubeflow/website/issues/462
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/646)
> update tfjob yaml info

- content/docs/components/tftraining.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/654)
> clean up some details on the tfjob yaml example

- content/docs/fairing/fairing-overview.md
Adds an overview doc for Kubeflow Fairing that describes what Fairing does, how to get started, and the goals of the Kubeflow Fairing project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/652)
> Adds fairing-overview.md

- content/docs/components/mxnet.md
- content/docs/components/tftraining.md
- content/docs/fairing/gcp-local-notebook.md
- content/docs/pipelines/sdk/component-development.md
- content/docs/pipelines/tutorials/build-pipeline.md
- gen-api-reference/gen-pytorchjob-api.sh
- gen-api-reference/gen-tfjob-api.sh
As the title says.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/661)
> Updated to a more secure bash syntax

- layouts/shortcodes/pipelines-compatibility.html
Making it less ominous, as we are running KFP framework on IKS as well
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/662)
> Update Kubeflow Pipeline dependency statement

- content/docs/gke/private-clusters.md
- members.yaml
Related to: kubeflow/kubeflow#3081
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/660)
> Update the private GKE cluster docs to also describe VPC.

- content/docs/gke/private-clusters.md
/assign @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/663)
> small fix on private ip cluster instruction

- content/docs/components/seldon.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/664)
> Fix the broken link Seldon Model wrappers

- content/docs/about/community.md
- content/docs/about/events.md
- content/docs/components/mpi.md
- content/docs/components/tfserving_new.md
- content/docs/examples/resources.md
- content/docs/gke/gcp-e2e.md
- content/docs/notebooks/setup.md
- content/docs/other-guides/troubleshooting.md
Capitalized brand names for TensorFlow, GitHub and Jupyter
/assign @abhi-g
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/666)
> Capitalized brand names

- README.md
- content/_index.html
- content/docs/about/contributing.md
- content/docs/components/tfserving_new.md
- content/docs/components/tftraining.md
- content/docs/examples/resources.md
- content/docs/gke/deploy/deploy-cli.md
- content/docs/gke/deploy/deploy-ui.md
- content/docs/gke/deploy/monitor-iap-setup.md
- content/docs/gke/deploy/next-steps.md
- content/docs/gke/troubleshooting-gke.md
- content/docs/other-guides/advanced.md
- content/docs/pipelines/upgrade.md
- content/docs/started/getting-started-k8s.md
Resolved a set of typos.
/assign @abhi-g
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/665)
> Resolved typos

- content/docs/components/modeldb.md
Added carriage return to fix bullet list rendering.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/667)
> Update modeldb.md to fix samples formatting issue

- content/docs/aws/deploy/existing-cluster.md
Fix issue https://github.com/kubeflow/website/issues/677
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/678)
> Fix typo in existing cluster deployment doc

- content/docs/started/getting-started.md
fixes https://github.com/kubeflow/website/issues/670
fixes https://github.com/kubeflow/website/issues/671
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/672)
> Getting-started guide: Linked to AWS docs and did a tech writer review

- content/docs/gke/private-clusters.md
* The cloud endpoints issue has been fixed so we can remove that bug.
Fix: #2086  Deploy Kubeflow in private GKE
Fix: #3081  Document how to deploy kubeflow with VPC service controls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/682)
> Update the private cluster instructions

- content/docs/started/getting-started-icp.md
fixes #333 
The PR is to add document for how to run kuebflow on IBM Cloud Private.
/cc @gyliu513
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/684)
> add get start kubeflow with icp

- content/docs/components/nuclio.md
- resources/_gen/assets/js/js/search.js_b4bb3e7b21b43e920b7c367ff787d383.content
Adding nuclio component documentation and examples
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/686)
> Adding nuclio component doc

- content/docs/gke/deploy/deploy-cli.md
- content/docs/gke/deploy/monitor-iap-setup.md
Refactored the guide to monitoring IAP setup, and clarified the process of setting up access control in the CLI deployment guide.
Fixes https://github.com/kubeflow/website/issues/681
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/697)
> Clarified IAP monitoring and auth services

- content/docs/pipelines/preemptible.md
Fixes https://github.com/kubeflow/website/issues/669
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/699)
> Added Pipelines preemptible VMs and GPUs

- content/docs/started/getting-started-k8s.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/698)
> Highligt how to install k8s cluster.

- content/docs/gke/cloud-filestore.md
Related to #650
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/702)
> Update cloud filestore instructions for 0.5

- content/docs/gke/gcp-e2e.md
In the PR https://github.com/kubeflow/examples/pull/546, we replaced ksonnet with kustomize. 
The PR is to update the gcp-e2e page accordingly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/700)
> update gcp-e2e page since ksonnet is removed

- content/docs/pipelines/pipelines-quickstart.md
Fixes https://github.com/kubeflow/website/issues/648
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/705)
> Expands introduction to Kubeflow Pipelines quickstart

- content/docs/components/tfbatchpredict.md
- content/docs/components/tftraining.md
- content/docs/gke/troubleshooting-gke.md
- content/docs/other-guides/troubleshooting.md
Fixes https://github.com/kubeflow/website/issues/632
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/713)
> Replaced 'k8s' with full brand name where relevant

- content/docs/aws/deploy/install-kubeflow.md
- content/docs/aws/troubleshooting-aws.md
Address #714
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/719)
> Add notes for eksctl incompatible version issue

- content/_index.html
- content/docs/components/nuclio.md
add pipline example
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/717)
> nuclio-edits

- content/docs/about/events.md
/assign @abhi-g
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/728)
> Added the doc sprint to the events page

- content/docs/started/getting-started-minikf.md
Update the MiniKF guide to be consistent with the latest MiniKF version.
- Add an "Upgrade notes" section
- Slightly change the "MiniKF installation" section
- Replace the MiniKF installation video with the latest version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/739)
> Update the MiniKF guide

- content/docs/pipelines/reference/_index.md
- content/docs/pipelines/sdk/install-sdk.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/740)
> Added the link to the SDK reference docs

- content/docs/other-guides/job-scheduling.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/741)
> Update Scheduler name

- OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/765)
> Adds joeliedtke as a website approver

- content/docs/gke/cloud-filestore.md
Fixes https://github.com/kubeflow/website/issues/422
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/774)
> Fixed assumption that KFAPP variable includes path

- content/docs/other-guides/accessing-uis.md
- content/docs/pipelines/pipelines-quickstart.md
Fixes https://github.com/kubeflow/website/issues/320
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/773)
> Added instruction to install kubectl

- content/docs/components/tftraining.md
Fixes https://github.com/kubeflow/website/issues/443
See current code in this file: https://github.com/kubeflow/tf-operator/blob/master/pkg/util/train/train_util.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/775)
> Fixed info about container exit codes

- content/docs/started/getting-started-k8s.md
Fixes https://github.com/kubeflow/website/issues/631
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/778)
> Added next steps to the on prem getting-started guide

- content/docs/azure/_index.md
- content/docs/azure/deploy/_index.md
- content/docs/azure/deploy/existing-cluster.md
- content/docs/azure/deploy/install-kubeflow.md
- content/docs/azure/deploy/uninstall-kubeflow.md
- content/docs/azure/troubleshooting-azure.md
Co-authored-by: rem20806 t-remcfa@microsoft.com
Co-authored-by: mohona17 t-moahme@microsoft.com
Not a robust and complete deployment guide, but more than enough to get Kubeflow deployed and running on Azure. 
Upcoming PRs will have information on authentication. Will also serve as a base to be expanded upon during the upcoming doc sprint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/780)
> Added a section for deployment on Azure

- content/docs/components/pytorch.md
- content/docs/components/tftraining.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/784)
> Update TF/PyTorch example references to v1

- OWNERS
Duplicates PR https://github.com/kubeflow/website/pull/764, which is currently stuck awaiting conflict resolution.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/786)
> Removed yebrahim from OWNERS file

- content/docs/azure/authentication.md
- content/docs/azure/deploy/_index.md
- content/docs/azure/deploy/install-kubeflow.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/787)
> Added Azure auth and minor typo/link fixes

- content/docs/gke/deploy/monitor-iap-setup.md
- content/docs/gke/troubleshooting-gke.md
- content/docs/other-guides/accessing-uis.md
Added information about expiry of Let's Encrypt certificates and hooked up the various troubleshooting guides. Also fixed up the list of apps on the Kubeflow UI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/796)
> Expanded information about Let's Encrypt certificates

- content/docs/reference/pytorchjob/v1/pytorch.md
- content/docs/reference/pytorchjob/v1beta2/pytorch.md
- content/docs/reference/tfjob/v1/common.md
- content/docs/reference/tfjob/v1/tensorflow.md
- content/docs/reference/tfjob/v1beta2/common.md
- content/docs/reference/tfjob/v1beta2/tensorflow.md
- gen-api-reference/gen-pytorchjob-api.sh
- gen-api-reference/gen-tfjob-api.sh
- simple update of table styling in api gen scripts: tf job, pytorch job.
- h3->code could use a better color for highlighting.
- See #680.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/805)
> update tfjob, pytorchjob ref scripts, style tables

- content/docs/gke/deploy/deploy-cli.md
Hi, could you please review the changes for the issue https://github.com/kubeflow/website/issues/785 ? please advise me if any additional changes required in the doc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/813)
> Typo in Documentation on GCP/Deploying Kubeflow/Deploy using CLI

- content/docs/azure/deploy/install-kubeflow.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/821)
> Removed initialization of Azure CLI, updated formatting issues for KF's Azure installation

- content/docs/started/getting-started-k8s.md
Update docs for installing Kubeflow on an existing Kubernetes Cluster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/833)
> platform-existing: update docs for deploying on existing k8s cluster

- content/docs/pipelines/sdk/sdk-overview.md
Supplement the KFP SDK Overview with the following entities
* kfp.dsl.ResourceOp
* kfp.dsl.VolumeOp
* kfp.dsl.VolumeSnapshotOp
* kfp.dsl.PipelineVolume
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/837)
> KFP SDK Overview: Add mentions to more DSL entities

- content/docs/started/getting-started-icp.md
* throgh -> through
* fixed numbering
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/839)
> fix typo & ol in icp getting started guide

- content/docs/pipelines/overview/interfaces.md
Created a page introducing the fact that there are various Pipelines interfaces: SDK, UI, and API. The page gives an overview of when you'd use each interface, and links to other guides for further info.
Fixes https://github.com/kubeflow/website/issues/574
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/829)
> Added an overview of Pipelines interfaces

- content/docs/started/getting-started-k8s.md
Reverts kubeflow/website#833
See issue https://github.com/kubeflow/website/issues/840
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/848)
> Revert "platform-existing: update docs for deploying on existing k8s cluster"

- content/docs/azure/deploy/install-kubeflow.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/846)
> Add note about GPU based AKS cluster

- content/docs/gke/deploy/monitor-iap-setup.md
fix #852 . 
/cc @jlewi @kunmingg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/883)
> update doc for iap

- content/docs/gke/deploy/deploy-cli.md
related to #864 . 
/cc @jlewi  @kkasravi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/887)
> update kfctl doc for kustomize

- OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/908)
> Add the driftofwords as a reviewer

- content/docs/components/hyperparameter.md
Fixes #865
Was: https://github.com/kubeflow/website/pull/892
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/906)
> Katib v1alpha2 documentation update

- content/docs/examples/resources.md
Added a new pipelines tutorial
Fixed title font to match other sections
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/902)
> Added a new tutorial to Examples section

- content/docs/started/getting-started-gke.md
Fixes #899
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/907)
> Add video to GKE getting started

- content/docs/reference/images.md
This is the cleaned up version of our fixes for pr832.
/assign @sarahmaddox @carmine
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/925)
> Table of source locations for Docker images

- content/docs/components/metadata.md
- content/docs/other-guides/accessing-uis.md
Fixes #879
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/909)
> Add metadata component doc for KF v0.6

- content/docs/notebooks/submit-kubernetes.md
- content/docs/notebooks/why-use-jupyter-notebook.md
Added new topic and content from https://groups.google.com/forum/#!msg/kubeflow-discuss/v1jwuGIjetk/4tdYZqw9BgAJ
@sarahmaddox @abhi-g First go at this topic. Have I missed anything?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/914)
> Added new topic - Using Jupyter notebooks in kubeflow

- content/docs/gke/deploy/deploy-cli.md
Making new PR to update docs. 
[Also, Closed the PR: #762 ]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/934)
> Updating documentation of deploy-cli

- content/docs/notebooks/setup.md
Issue: https://github.com/kubeflow/website/issues/891
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/941)
> [doc-sprint] Linked to simple notebook pipeline example

- content/docs/components/training/pytorch.md
- content/docs/components/training/tftraining.md
Part of https://github.com/kubeflow/website/issues/930
/assign @johnugeorge
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/939)
> Update instructions for TFJob and PytorchJob

- content/_index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/955)
> fix typos in overview

- content/docs/components/training/tftraining.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/961)
> fix: add missing "-f" for kubectl apply

- content/docs/started/getting-started.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/967)
> Fix a minor typo

- content/docs/gke/authentication.md
Fix #946 I am adding steps to setup credentials for namespaces consuming Kubeflow.
/assign @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/957)
> Add namespace credentials setup steps

- content/docs/other-guides/multi-user-overview.md
Add default GCP IAM role for users under multi-user mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/970)
> add steps for onboard users

- content/docs/pipelines/upgrade.md
instructions for upgrade will be a separate PR
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/972)
> Update kfp reinstall instructions for kubeflow 0.6

- README.md
- config.toml
Fixes https://github.com/kubeflow/website/issues/952
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/979)
> Added version number to top menu bar

- content/docs/pipelines/sdk/sdk-overview.md
- content/docs/started/getting-started-gke.md
- See #963
- See #982
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/985)
> fix a few typos

- layouts/partials/scripts.html
Not meant to be perfect, but I think this is very helpful in sharing links to specific sections.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1009)
> Add anchor links to markdown headings.

- content/docs/pipelines/sdk/sdk-overview.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1018)
> Fixed link to xgboost-training-cm.py in sdk-overview

- content/docs/components/serving/istio.md
- content/docs/components/serving/pytorchserving.md
- content/docs/components/serving/seldon.md
- content/docs/components/serving/tfserving_new.md
- content/docs/components/serving/trtinferenceserver.md
- content/docs/components/training/chainer.md
- content/docs/components/training/mpi.md
- content/docs/components/training/mxnet.md
Fixes https://github.com/kubeflow/website/issues/989.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1015)
> Add references to kustomize issues

- content/docs/aws/authentication.md
- content/docs/aws/deploy/existing-cluster.md
- content/docs/aws/deploy/install-kubeflow.md
- content/docs/aws/deploy/uninstall-kubeflow.md
Update aws provision process to use kfctl golang cli and kustomize
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1030)
> Update aws docs for 0.6 release

- content/docs/pipelines/pipelines-quickstart.md
- content/docs/pipelines/sdk/build-component.md
- content/docs/pipelines/sdk/dsl-recursion.md
- content/docs/pipelines/sdk/lightweight-python-components.md
- content/docs/pipelines/sdk/sdk-overview.md
- content/docs/pipelines/sdk/static-type-checking.md
- content/docs/pipelines/tutorials/build-pipeline.md
Fixes https://github.com/kubeflow/pipelines/issues/1743
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1057)
> update sample link after kfp sample restructure

- content/docs/components/misc/metadata.md
- content/docs/reference/metadata.md
- content/docs/reference/metadata/v1alpha1/kubeflow-metadata-api-spec.html
- content/docs/reference/overview.md
Fixes #580
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1058)
> Add metadata API reference doc

- content/docs/components/misc/metadata.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1078)
> Change will to may in metadata warning

- content/docs/components/serving/seldon.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1073)
> Update Seldon docs

- content/docs/pipelines/pipelines-quickstart.md
- layouts/shortcodes/pipelines-compatibility.html
The doc is mostly update-to-date.
Updated:
* a minor improvement on where a link is
* updated an issue to the latest issue that tracks new info
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1080)
> Update pipeline quickstart for kf 0.6

- content/docs/started/k8s/kfctl-k8s-istio.md
Fix issue #1099
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1111)
> Issue 1099 broken link

- content/docs/components/training/tftraining.md
- content/docs/other-guides/accessing-uis.md
Closes #1091.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1120)
> remove content for TFJob dashboard

- content/docs/azure/deploy/existing-cluster.md
- content/docs/azure/deploy/install-kubeflow.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1119)
> Update Azure installation docs

- content/docs/pipelines/sdk/manipulate-resources.md
- content/docs/pipelines/sdk/sdk-overview.md
Add documentation for:
* ResourceOp
* VolumeOp
* PipelineVolume
* VolumeSnapshotOp
I believe this PR closes both #757 and #758.
Of course, if you have a different opinion, feel free to remove any of the following lines.
Closes #757 
Closes #758 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1122)
> KFP SDK: Add Documentation on K8s Resource Manipulation

- content/docs/pipelines/tutorials/cloud-tutorials.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1135)
> Update cloud-tutorials.md to include new end-to-end Azure tutorial

- content/docs/pipelines/sdk/lightweight-python-components.md
- content/docs/pipelines/sdk/sdk-overview.md
- content/docs/pipelines/sdk/static-type-checking.md
- content/docs/pipelines/tutorials/build-pipeline.md
Fix temporarily broken links.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1141)
> Fix some links changed in KFP samples

- content/docs/started/k8s/kfctl-existing-arrikto.md
- content/docs/started/k8s/kfctl-k8s-istio.md
1) Added a "Follow, the instructions..." from arrikto to istio doc page (in order to make it generally consistent).
2) Fixed link in arrikto ( #1149  ) 
3) Added dot for last item for both of the pages  (in order to make it generally consistent).
> Corrections for "getting started" pages.

- config.toml
Fixes https://github.com/kubeflow/website/issues/1159
Fixes https://github.com/kubeflow/website/issues/1160
/cc @sarahmaddox @jlewi 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1168)
> default to v0.6 docs

- OWNERS
I'm some projects maintainer, can review the related docs and also review docs from IBM member such as for IBM Cloud Private. Thanks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1180)
> Add jinchihe to OWNERS

- content/docs/pipelines/sdk/parameters.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1161)
> Deemphasized manual creation of `PipelineParam` objects

- content/docs/pipelines/sdk/sdk-overview.md
fix broken link - tfx oss using components example and replace with a simple component build example
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1164)
> fix broken link

- content/docs/about/community.md
see https://github.com/kubeflow/community/issues/15#issuecomment-536132461
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1178)
> update the slack invite link

- content/docs/components/misc/metadata.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1182)
> Fix link to notebook.

- content/docs/started/cloud/getting-started-icp.md
I hit these issues when installing kubeflow in a default installation of ICP. I believe this troubleshooting section will help others who are interested in installing kubeflow in ICP
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1176)
> Added a troubleshooting section in ICP

- content/docs/components/misc/metadata.md
- content/docs/components/misc/nuclio.md
- content/docs/components/serving/istio.md
- content/docs/components/training/mpi.md
- content/docs/components/training/tftraining.md
- content/docs/other-guides/kustomize.md
- content/docs/other-guides/virtual-dev/getting-started-minikube.md
- content/docs/pipelines/sdk/build-component.md
Issue #1184 describe issue this PR suppose to fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1185)
> Multiple dead/broken links fixed see #1184

- OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1194)
> Will be owning the docs for KFServing

- netlify.toml
Fixes https://github.com/kubeflow/website/issues/793
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1191)
> Upgrade Hugo

- content/docs/started/getting-started.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1190)
> Fixed syntax to match sibling bullet points

- content/docs/pipelines/sdk/gcp/preemptible.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1170)
> add hard_constraint support for the preemptible VMs in KFP

- content/docs/pipelines/sdk/build-component.md
- content/docs/pipelines/sdk/output-viewer.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1157)
> update tfx cab sample links

- content/docs/gke/deploy/deploy-cli.md
- content/docs/gke/troubleshooting-gke.md
- layouts/shortcodes/config-uri-gcp-basic-auth.html
- layouts/shortcodes/config-uri-gcp-iap.html
- Point config to v0.6 branch head 
- Publish trouble shooting instruction for kubeflow deployment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/975)
> point config to v0.6 branch head and add deployment trouble shooting instruction

- content/docs/started/k8s/kfctl-existing-arrikto.md
- content/docs/started/k8s/kfctl-k8s-istio.md
Thanks to @deepdad for suggesting this change in PR https://github.com/kubeflow/website/pull/1074
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1220)
> Added hint about characters in kfctl path

- content/docs/pipelines/tutorials/build-pipeline.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1230)
> Fix a broken link in KFP sample

- content/docs/other-guides/kubeflow-on-multinode-cluster.md
change all four unbound pvc after nfs-client-provisioner installation on existing kubeflow installation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1232)
> add pvc/metadata-mysql for storage class change

- content/docs/other-guides/virtual-dev/getting-started-minikube.md
Signed-off-by: yeya24 <yb532204897@gmail.com>
fixes https://github.com/kubeflow/kubeflow/issues/4025
@jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1254)
> fix broken links

- content/docs/aws/customizing-aws.md
- content/docs/aws/deploy/install-kubeflow.md
- content/docs/aws/troubleshooting-aws.md
- layouts/shortcodes/config-uri-aws-cognito.html
- layouts/shortcodes/config-uri-aws-standard.html
Resolve #1267
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1271)
> Pin aws manifests to 0.7.0 and Update aws docs

- content/docs/started/k8s/kfctl-existing-arrikto.md
Update existing_arrikto docs for v0.7.
/cc @sarahmaddox
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1265)
> existing_arrikto: v0.7 docs

- content/docs/gke/authentication.md
/cc @kunmingg @jlewi 
fix https://github.com/kubeflow/website/issues/1175
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1269)
> add doc on workload identity

- content/docs/pipelines/sdk/manipulate-resources.md
Part of the curriculum organization https://github.com/kubeflow/pipelines/issues/2490
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1276)
> Moving the advanced topic "Manipulate Kubernetes Resources" down

- content/docs/pipelines/reference/component-spec.md
- content/docs/pipelines/sdk/best-practices.md
- content/docs/pipelines/sdk/component-development.md
The recently added artifact passing feature makes data passing and component development much simpler.
Updating the tutorials.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1277)
> [Pipelines] Greatly simplified the "Create Reusable Components" tutorial

- content/docs/pipelines/sdk/component-development.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1286)
> [Pipelines] Small fix for component guide

- content/docs/components/hyperparameter-tuning/hyperparameter.md
for now, in kubeflow release, katib version is v1alpha3, so we should update katib doc for v1alpha3, too
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1287)
> Update doc for katib 0.7

- content/docs/components/misc/metadata.md
Initial introduction to metadata watcher for v0.7 by pointing to the Github readme.
Once the watcher is more mature, we can expand this section.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1285)
> Add a paragraph to introduce the metadata watcher

- content/docs/reference/images.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1291)
> Update katib dockerfile link

- content/docs/aws/deploy/install-kubeflow.md
from v1alpha1 which doesn't exist anymore to v1beta1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1298)
> Update the example of the Profile YAML apiVersion

- README.md
Updated shortcodes directory path in README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1300)
> Update shortcodes path in README.md

- content/docs/started/workstation/getting-started-linux.md
Fixes https://github.com/kubeflow/website/issues/1302
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1303)
> WtD fixit: Readability improvements for Kubeflow on Linux

- content/docs/started/k8s/overview.md
Document compatible Kubernetes versions 
fixes #1281
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1319)
> Document compatible Kubernetes versions

- content/docs/components/serving/kfserving.md
Rearranged KFServing writeup
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1320)
> Kfserving update

- content/docs/other-guides/virtual-dev/getting-started-minikube.md
Fix kubeflow/kubeflow#4388
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1325)
> Delete docs that reference deleted minikube script.

- content/docs/fairing/reference/_index.md
- content/docs/fairing/reference/sdk.md
Related with https://github.com/kubeflow/fairing/issues/413
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1327)
> Add reference for fairing SDK docs

- content/docs/gke/authentication.md
- content/docs/other-guides/multi-user-overview.md
fix https://github.com/kubeflow/website/issues/1313
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1318)
> update profile doc API; add instrucitons for GCP access fine grain control

- layouts/shortcodes/config-uri-existing-arrikto.html
Pin the existing_arrikto config to a certain commit in order to ensure total reproducibility.
/cc @sarahmaddox 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1340)
> existing_arrikto: pin config to certain commit

- content/docs/components/training/tftraining.md
Fixes https://github.com/kubeflow/website/issues/1345
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1350)
> WtD fixit: Readability improvements for TensorFlow Training (TFJob)

- content/docs/about/contributing.md
Fixes https://github.com/kubeflow/website/issues/1352 and https://github.com/kubeflow/website/issues/1331
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1362)
> WtD fixit: Readability improvements for Contributing to Kubeflow

- content/docs/started/workstation/getting-started-windows.md
A few headings were changed to sentence case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1356)
> Change headings to sentence case.

- content/docs/upgrading/upgrade.md
https://www.kubeflow.org/docs/upgrading/upgrade/
Issue #1355
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1388)
> WtD fixit: Readability improvements for removing an extra colon

- content/docs/azure/deploy/install-kubeflow.md
Fix https://www.kubeflow.org/docs/azure/deploy/install-kubeflow/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1392)
> WtD fixit: Readability improvements for Install Kubeflow

- content/docs/started/workstation/getting-started-linux.md
Fixes https://github.com/kubeflow/website/issues/1344
https://www.kubeflow.org/docs/started/workstation/getting-started-linux/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1358)
> WtD fixit: Readability improvements for WtD fixit: Kubeflow on Linux

- content/docs/other-guides/troubleshooting.md
Fixes https://github.com/kubeflow/website/issues/1357
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1363)
> WtD fixit: Readability improvements for Troubleshooting

- content/docs/azure/azureEndtoEnd.md
Fixes this issue:  https://github.com/kubeflow/website/issues/1342
(Thanks for the lovely intro and exercise at WTD!)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1359)
> WtD fixit: Readability improvements for End-to-End Pipeline Example on Azure

- content/docs/other-guides/virtual-dev/getting-started-multipass.md
Fixes https://github.com/kubeflow/website/issues/1341
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1377)
> WtD fixit: Readability improvements for: Microk8s for Kubeflow

- content/docs/notebooks/setup.md
Fixes https://github.com/kubeflow/website/issues/1361
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1364)
> WtD fixit: Readability improvements for Set Up Your Notebooks

- content/docs/pipelines/sdk/gcp/enable-gpu-and-tpu.md
Fixes https://github.com/kubeflow/website/issues/1370
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1380)
> WtD fixit: Readability improvements for Enable GPU and TPU

- content/docs/pipelines/sdk/python-based-visualizations.md
Fixes https://www.kubeflow.org/docs/pipelines/sdk/python-based-visualizations/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1383)
> WtD fixit: Readability improvements for Python Based Visualizations

- content/docs/started/cloud/getting-started-icp.md
Fixes https://github.com/kubeflow/website/issues/1346
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1384)
> WtD fixit: Readability improvements for IBM Cloud Private for Kubeflow

- content/docs/about/kubeflow.md
https://www.kubeflow.org/docs/about/kubeflow/
Fixes #1349
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1401)
> WtD fixit: Readability improvements for the title

- content/docs/gke/troubleshooting-gke.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1368)
> Address review comments on PR #975

- content/docs/about/community.md
Fixes https://github.com/kubeflow/website/issues/1366
Note I can't get https://kubeflow.slack.com/messages/C985VJN9F to load, but talking to Alec, this could be due to a Slack issue. Assuming that the Slack link is correct!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1389)
> WtD fixit: Readability improvements for Community

- content/docs/started/cloud/getting-started-gke.md
Fix #1386
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1390)
> Remove outdated video

- content/docs/components/serving/kfserving.md
Fixed: https://github.com/kubeflow/website/issues/1396
Additional note: It's not clear what the "Examples" are of. I'm not familiar enough with the software to update the heading to something more appropriate, though.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1399)
> WtD fixit: Readability improvements for KFServing

- content/docs/fairing/fairing-overview.md
Fixes https://www.kubeflow.org/docs/fairing/fairing-overview/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1369)
> WtD fixit: Readability improvements for Overview of Kubeflow Fairing

- content/docs/pipelines/standalone-deployment-gcp.md
https://www.kubeflow.org/docs/pipelines/standalone-deployment-gcp/
https://github.com/kubeflow/website/issues/1391
Fixes Readability improvements for Pipelines Standalone Deployment in GCP
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1398)
> WtD fixit: Update standalone-deployment-gcp.md

- content/docs/pipelines/upgrade.md
Fixes https://github.com/kubeflow/website/issues/1371
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1378)
> WtD fixit: Readability improvements for Upgrading and Reinstalling

- content/docs/about/contributing.md
Fixes https://github.com/kubeflow/website/issues/1332
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1411)
> Clarified links to good first issues in contrib guide

- content/docs/other-guides/kubeflow-on-multinode-cluster.md
As PVCs change from version to version, the generalized steps for storage class change will be applicable for any PVCs in any namespaces.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1409)
> generalized steps for storage class change

- content/docs/gke/deploy/monitor-iap-setup.md
for https://github.com/kubeflow/website/issues/1261
/cc @jlewi @sarahmaddox
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1330)
> update iap doc

- content/docs/components/serving/overview.md
Fixes #1239 
@ellis-bigelow
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1405)
> Serving Comparison Page

- content/docs/components/misc/metadata.md
- content/docs/reference/metadata/_index.md
- content/docs/reference/metadata/sdk.md
Fixes https://github.com/kubeflow/website/issues/1206
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1430)
> Added links to the Metadata SDK reference docs

- content/docs/other-guides/virtual-dev/getting-started-minikube.md
This PR updates the installation instructions for the MacOS Minikube. Also edited the reference of the "detailed installation instructions" to the "Getting Started" of the official Minikube documentation.
Fixes #1433
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1436)
> Update macos installation instructions

- content/docs/components/serving/tfserving_new.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1413)
> add selector in Deployment spec

- content/docs/gke/customizing-gke.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1432)
> Add GPU node pool to an existing kubeflow cluster

- content/docs/notebooks/setup.md
Documents the **Configurations** and **Extra Resources** fields in the Notebooks setup screen
Fixes https://github.com/kubeflow/website/issues/1268
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1419)
> Added guide to additional configurations and resources for notebook servers

- layouts/shortcodes/pipelines-compatibility.html
Fixes https://github.com/kubeflow/website/issues/1247
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1434)
> Changed the pipelines limitation note to mention just one issue (GCR)

- content/docs/notebooks/troubleshoot.md
This PR fixes a minor typo, should be ready to merge immediately.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1440)
> Fix typo in troubleshooting doc

- content/docs/components/training/mpi.md
fix kubeflow/mpi-operator#157
Related to: kubeflow/website#930 - remove ksonnet
Signed-off-by: Abhilash Pallerlamudi <stp.abhi@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1447)
> Update mpi-operator installation doc to use Kustomize

- content/docs/upgrading/upgrade.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1455)
> Kubeflow upgrade instructions

- content/docs/components/serving/overview.md
Clarifies the serving overview:
* Adds an introductory paragraph to the page.
* Shortens and clarifies some sentences.
* Styles the table.
* Changes Xs to check marks and moves the links to aliases
Fixes https://github.com/kubeflow/website/issues/1459
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1454)
> Clarifications to the serving overview

- layouts/shortcodes/config-uri-existing-arrikto.html
/cc @sarahmaddox 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1462)
> existing-arrikto: Update config to v0.7.1

- content/_redirects
- content/docs/other-guides/gitops-for-kubeflow.md
- content/docs/other-guides/job-scheduling.md
- content/docs/use-cases/_index.md
Fixes https://github.com/kubeflow/website/issues/1422
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1473)
> Moved guides from use-cases to other-guides section

- content/docs/started/getting-started.md
- layouts/shortcodes/config-file-existing-arrikto.html
Fixes https://github.com/kubeflow/website/issues/1338
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1467)
> Added a matrix of deployment platforms and config files

- content/docs/pipelines/sdk/python-based-visualizations.md
1. Add a video of how to generate TFDV visualization in KFP.
2. Add short instructions explaining the steps in the video.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1487)
> Add an exmaple of how to use TFDV visualization in KFP

- content/docs/components/training/mpi.md
kubectl support kustomize after k8s 1.14
so the command should be 
kubectl kustomize base | kubectl apply -f -
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1490)
> update kustomize deploy common

- content/docs/other-guides/kubeflow-on-multinode-cluster.md
instal to install
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1488)
> Fix typo in kubeflow-on-multinode-cluster doc

- content/docs/gke/authentication.md
Signed-off-by: sakshamgupta93 <saksham.gupta@nagarro.com>
Fixed the indentation for authentication.md file
Relates to issue #1476
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1491)
> Fixed the indentation for authentication.md file

- content/docs/gke/customizing-gke.md
Fix typo in doc 'customizing_gke.md'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1496)
> Typo fix in 'customizing_gke.md'

- content/_redirects
- content/docs/gke/pipelines/enable-gpu-and-tpu.md
- content/docs/gke/pipelines/preemptible.md
- content/docs/pipelines/sdk/gcp.md
Fixes https://github.com/kubeflow/website/issues/1448
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1498)
> Moved GCP-specific pipelines SDK docs to GCP pipelines section

- content/docs/components/hyperparameter-tuning/experiment.md
katib support `custom` collector and custom metrics format
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1506)
> Update katib metrics colllector doc

- content/docs/other-guides/troubleshooting.md
- content/docs/reference/images.md
Sync up with change of https://github.com/kubeflow/katib/issues/1004
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1514)
> Sync up with katib component rename

- content/docs/components/misc/metadata.md
This PR reflects recent change of metadata manifest structure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1515)
> Update Metadata installation from Manifest

- content/docs/pipelines/installation/_index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1525)
> Fixed typo

- content/docs/pipelines/sdk/python-based-visualizations.md
See issue #1505.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1526)
> update formatting of code blocks

- content/docs/gke/private-clusters.md
Fixes https://github.com/kubeflow/website/issues/1542
Preview: https://deploy-preview-1547--competent-brattain-de2d6d.netlify.com//docs/gke/private-clusters/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1547)
> Added alpha banner to GKE private cluster page

- config.toml
Part of issue https://github.com/kubeflow/website/issues/1513
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1561)
> Created v0.7 branch of docs and set archived_version param to true

- config.toml
Part of issue https://github.com/kubeflow/website/issues/1513
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1562)
> Added v0.7 to version menu on main site

- content/docs/started/workstation/getting-started-windows.md
Clarification of message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1579)
> Simplification of installation instructions

- content/docs/started/workstation/getting-started-linux.md
Removal of one sentence for simplification.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1578)
> Simplification of doc paragraph.

- content/docs/components/training/mpi.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1580)
> Update MPI Operator instructions to use v1alpha2

- content/docs/ibm/_index.md
- content/docs/ibm/existing-cluster.md
- content/docs/ibm/install-kubeflow.md
- content/docs/ibm/uninstall-kubeflow.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1575)
> Initial IBM Cloud deployment instructions

- content/docs/components/serving/seldon.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1600)
> Add 1.0 update for Seldon

- content/docs/examples/codelabs-tutorials.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1601)
> fix broken link for pipeline tutorial

- content/docs/other-guides/support.md
- content/docs/other-guides/troubleshooting.md
This PR recreates PR https://github.com/kubeflow/website/pull/1520/files, which we merged and then reverted.
Fixes https://github.com/kubeflow/website/issues/1131
Preview: https://deploy-preview-1591--competent-brattain-de2d6d.netlify.com/docs/other-guides/support/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1591)
> Added a support page for Kubeflow v1.0.0

- content/docs/examples/blog-posts.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1597)
> Add an ML-orchestration blog reference

- content/docs/other-guides/job-scheduling.md
Fixes https://github.com/kubeflow/website/issues/1604
Preview: https://deploy-preview-1607--competent-brattain-de2d6d.netlify.com/docs/other-guides/job-scheduling/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1607)
> Added alpha banner to job scheduling page

- content/docs/components/training/mpi.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1610)
> Add note on the use of kubectl kustomize

- content/docs/examples/kubeflow-samples.md
Preview: https://deploy-preview-1629--competent-brattain-de2d6d.netlify.com/docs/examples/kubeflow-samples/
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1629)
> Fixes a link in the samples page

- content/docs/about/contributing.md
Added link from contributor guide to inclusivity document.
Fixes # 454
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1632)
> Added link to inclusivity document

- content/docs/gke/troubleshooting-gke.md
Fixes https://github.com/kubeflow/website/issues/1181
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1634)
> Fix typo in GKE troubleshooting guide

- content/docs/components/serving/seldon.md
Updated Seldon Serving page for Kubeflow Doc sprint.
I fiddled with the list item text (gateway, namespace label).
Happy to modify or change the text back to the original text.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1631)
> Seldon Serving: update headings, text, list numbering

- content/docs/components/hyperparameter-tuning/hyperparameter.md
https://github.com/kubeflow/website/issues/1599
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1633)
> Update katib example to use user profile

- content/docs/gke/custom-domain.md
- layouts/shortcodes/needs-update.html
https://github.com/kubeflow/website/issues/1605
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1642)
> Add banner for outdated pages

- content/docs/gke/deploy/delete-cli.md
- content/docs/gke/deploy/deploy-cli.md
- content/docs/gke/deploy/project-setup.md
I found listing problem in three files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1645)
> #1621 : fixed list formatting

- content/docs/components/training/tftraining.md
- content/docs/gke/troubleshooting-gke.md
Partially fixes https://github.com/kubeflow/website/issues/1554
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1638)
> Update TFJob instructions for user profile namespace

- content/docs/components/hyperparameter-tuning/experiment.md
- content/docs/components/hyperparameter-tuning/overview.md
- content/docs/other-guides/virtual-dev/getting-started-multipass.md
- content/docs/pipelines/upgrade.md
- content/docs/upgrading/upgrade.md
Fixes #1618
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1649)
> Standardise the alpha notices in the docs

- content/docs/gke/custom-domain.md
This fixes #1166 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1650)
> Update 'Using your own domain' (#1166)

- content/docs/about/kubeflow.md
- content/docs/about/use-cases.md
@jbottum @elviraux 
Closes #1596 
https://docs.google.com/document/d/1emDtEXJ4CKqYq1evjDW4laLTlKml8U1bKfL-Aw6ubok/edit#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1644)
> Use cases page for Kubeflow website 

- content/docs/started/workstation/getting-started-macos.md
The word "that" was missing from the first sentence.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1654)
> Added a missing word

- content/docs/about/kubeflow.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1646)
> Added product and component roadmaps to kubeflow.md (#1594)

- content/_index.html
See issue #1211, Kubeflow Doc Sprint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1663)
> Add bold to linked text on home page

- content/docs/gke/cloud-filestore.md
Update the path to the cloud filestore yaml file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1658)
> Update cloud filestore instruction

- content/docs/pipelines/overview/concepts/pipeline.md
Fixes #1624
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1657)
> Link Pipeline concepts page to relevant concept docs

- content/docs/components/serving/_index.md
- content/docs/components/training/_index.md
Fixes #1655
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1668)
> Rename training and serving section titles

- content/docs/components/serving/tfserving_new.md
Fixes #240 
Kubeflow repo fix is in[ PR  #4760](https://github.com/kubeflow/kubeflow/pull/4760)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1666)
> Move info about IAP and TFServing to the docs website

- content/docs/notebooks/submit-kubernetes.md
fixes #1576
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1680)
> update description of notebooks permissions

- content/docs/pipelines/overview/pipelines-overview.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1679)
> fix link in pipeline overview

- content/docs/components/_index.md
Fixes #1674
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1678)
> Move components section higher in the left-hand nav

- scripts/validate-urls.py
Related to https://github.com/kubeflow/website/issues/1683
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1684)
> Add script to validate urls in .md

- content/docs/other-guides/kubeflow-on-multinode-cluster.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1695)
> Added line continuation

- content/docs/about/events.md
This is part of fix for issue #1683 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1706)
> Fixed broken links in About directory

- content/docs/pipelines/sdk/install-sdk.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1708)
> Fix typo in install-sdk.md

- content/docs/components/misc/nuclio.md
This is part of fix for issue [#1683](https://github.com/kubeflow/website/issues/1683) .
@sarahmaddox 
Please note I cannot find any working notebooks for "TensorFlow Serving Function" and "Predictive Infrastructure Monitoring" in https://github.com/v3io/tutorials, I have replaced them with other working notebooks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1713)
> Fixed broken links in components-misc directory

- content/docs/aws/logging.md
- content/docs/aws/private-access.md
Resolve #1714
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1715)
> Deprecate Private Access and Logging - use awcli instead

- content/docs/gke/gcp-e2e.md
Remove unreferenced/unused broken links so that they will NOT be reported in the [url-validation tool](https://github.com/kubeflow/website/issues/1683).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1725)
> Remove unreferenced broken links

- OWNERS
I want to contribute more. So far, I have 25 commits in this repo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1726)
> Add janeman98 as reviewer

- content/docs/other-guides/troubleshooting.md
Fixes https://github.com/kubeflow/website/issues/1712
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1727)
> Added troubleshooting for unsigned binary on macOS

- content/docs/aws/customizing-aws.md
- content/docs/aws/iam-for-sa.md
Address #1667
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1719)
> Add documentation for AWS service authentication

- content/docs/aws/deploy/install-kubeflow.md
Address #1722
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1723)
> Simplify installation flow for AWS

- content/docs/gke/anthos.md
Fixes https://github.com/kubeflow/website/issues/1720
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1729)
> Added a page about Anthos GKE

- content/docs/aws/deploy/install-kubeflow.md
Address #1736 
Not sure if there's better way to resolve this issue.  Currently, I change indent to 2 to make it work. The problem I think is `-` in code snippet is recognized as markdown list if I use indent 4.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1737)
> Fix code snippet format issue

- content/docs/pipelines/installation/standalone-deployment.md
Resolves https://github.com/kubeflow/pipelines/issues/3074.
This is a common confusion.
/assign @joeliedtke 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1724)
> Reduce confusion about hashicorp/go-getter format

- content/docs/pipelines/sdk/enviroment_variables.md
Updates environment variables page with changes for kubeflow/website #1732.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1733)
> Formats code samples and updates link text

- content/docs/gke/troubleshooting-gke.md
Part of fix for [issue # 1683](https://github.com/kubeflow/website/issues/1683)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1740)
> Fixed broken links in gke troubelshooting

- content/docs/gke/gcp-e2e.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1731)
> Clarified some things in the intro page for the MNIST notebook

- content/docs/pipelines/installation/standalone-deployment.md
See issue #1622.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1689)
> format lists and cleanup, KFP standalone

- content/docs/other-guides/job-scheduling.md
- content/docs/other-guides/troubleshooting.md
Part of fixes for[ issue 1683](https://github.com/kubeflow/website/issues/1683).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1763)
> Fixed broken links in other-guides directory

- content/docs/components/serving/seldon.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1767)
> Fix typo in Seldon Serving Gateway Spec

- content/docs/notebooks/setup.md
Fixes https://github.com/kubeflow/website/issues/1761
Fixes https://github.com/kubeflow/website/issues/1507
A number of options have changed in the notebook setup for Kubeflow 1.0.0. This PR updates the setup guide accordingly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1762)
> Updated notebook setup guide for Kubeflow 1.0.0 UI

- content/docs/gke/private-clusters.md
Fixes https://github.com/kubeflow/website/issues/1769
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1781)
> Update instruction on deleting cert-manager

- content/docs/components/serving/seldon.md
- content/docs/reference/version-policy.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1777)
> Add Seldon to stable components and fix Seldon name

- content/docs/aws/authentication.md
Explained what is "Authorization Code Grant"
Issue is from [kubeflow repo](https://github.com/kubeflow/kubeflow/issues/4826)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1783)
> updated docs for "Authorization code grant"

- content/docs/examples/codelabs-tutorials.md
- content/docs/examples/kubeflow-samples.md
Fixes https://github.com/kubeflow/website/issues/1773
We should re-add the links to specific samples/codelabs when those examples are in working order.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1774)
> Cleaned up the samples and codelabs/tutorials pages

- content/docs/pipelines/overview/pipelines-overview.md
Introduced link to KFP standalone installation.
First stab at a bit of cleanup.
For further information, see issue #1623 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1791)
> add standaline install link, other cleanup

- content/docs/azure/deploy/install-kubeflow.md
as discussed, @berndverst
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1798)
> for azure end to end tutorial to work

- content/docs/about/community.md
- content/docs/about/events.md
- content/docs/about/gsoc.md
Added a page with info for GSoC students and mentors. Linked to the page from the Community page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1806)
> Added a GSoC page

- content/docs/components/hyperparameter-tuning/hyperparameter.md
Per this issue: https://github.com/kubeflow/website/issues/1686 I added updating the namespace too the hyperparameter tuning examples.
First PR, :) so I'm sorry if this is missing more info needed here! please just let me know! It's only WIP because I want to see it's preview first but I think it is all there!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1813)
> Added namespace updates too examples

- content/docs/gke/deploy/project-setup.md
Closes #1814 
Added enable cloud build API in step 4 [here](https://www.kubeflow.org/docs/gke/deploy/project-setup/)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1817)
> added enable Cloud Build API

- content/docs/aws/custom-domain.md
https://{YOUR_DOMAIN_NAME}/oauth2/idresponse -> https://{YOUR_DOMAIN_NAME}/oauth2/idpresponse
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1815)
> fixed domain url spelling

- content/docs/pipelines/tutorials/api-pipelines.md
- content/docs/pipelines/tutorials/build-pipeline.md
- content/docs/pipelines/tutorials/cloud-tutorials.md
- content/docs/pipelines/tutorials/sdk-examples.md
Summary of changes:
- Updates to sdk-examples for terminology, grammar, and clarity. ([Kubeflow/Website #1819 ](https://github.com/kubeflow/website/issues/1819))
- Reorders the files in the KFP Samples and Tutorials directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1820)
> TW updates to sdk-examples, and reorder KFP Samples and Tutorials

- OWNERS
I'll be mostly maintaining the docs for MPI as well as potentially adding docs for other operators we maintain.
> Add @terrytangyuan to OWNERS

- OWNERS
Reducing the number of **approvers** to a handful, and removing some **reviewers** who have either left the project or not shown much activity in the last year.
Also added @Jeffwan as reviewer, so that he can LGTM the AWS-related PRs.
> Thinned out the website OWNERS file

- content/docs/components/multi-tenancy/getting-started.md
Fixes https://github.com/kubeflow/website/issues/1283
> Added gcloud commands for cluster access

- content/docs/started/workstation/minikube-linux.md
Added hints and tips section to minikube tutorial.
> Added hints and tips section to minikube tutorial

- content/docs/gke/customizing-gke.md
- content/docs/other-guides/kustomize.md
- content/docs/started/getting-started.md
Fixes https://github.com/kubeflow/website/issues/1438
> Added kustomize min version in more places

- content/docs/pipelines/sdk/component-development.md
- content/docs/started/k8s/kfctl-istio-dex.md
Fixes #1826
https://www.kubeflow.org/docs/pipelines/sdk/component-development/
program.py will give error when number of line requested is more than the actual number of line in the input file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/website/1831)
> Fixed program.py when num of line requested is more than actual num

- content/docs/about/kubeflow.md
Added below lines to insert Kubeflow 101 video to the About Kubeflow page.
line 23:  Watch the following video which provides an introduction to Kubeflow.
line 25: {{< youtube cTZArDgbIWw >}}
> Added the Kubeflow 101 video to the About Kubeflow page.

- content/docs/aws/storage.md
> storage.md

- OWNERS
Below are my highlights:
-- 38 commits in website repo (3rd contributor)
-- Fixed all broken urls in all md files in website repo
-- Added Minikube tutorial
-- Added Katib API reference
> Added Jane to owner

- content/docs/pipelines/caching.md
Re-submitting https://github.com/kubeflow/website/pull/1875 due to the problem outlined here: https://github.com/kubeflow/website/pull/1875#issuecomment-613740305
> [Doc]KFP caching

- content/docs/upgrading/upgrade.md
Fixes https://github.com/kubeflow/website/issues/1873
> Clarified the upgrade spec

- OWNERS
Adding myself as a reviewer so I can help review docs, especially for Azure.
> Adding Reviewers for Azure Documentation

- content/en/docs/other-guides/kustomize.md
Fixes #1917 
Fixed instruction for installing kustomize.
> Fixed instruction for installing kustomize

- content/en/docs/started/workstation/getting-started-linux.md
- content/en/docs/started/workstation/minikube-linux.md
Did a quick pass of the guide to apply the Kubeflow docs style guide, and linked from the Linux guide to the Minikube guide.
Preview: https://deploy-preview-1921--competent-brattain-de2d6d.netlify.app/docs/started/workstation/minikube-linux/
> Tech writing review of Minikube guide

- content/en/_index.html
Also change "MXNet" to "Apache MXNet"
> Add XGBoost and MPI on homepage

- OWNERS
Remove myself from the list of approvers, as I'll be focusing on internal projects for a while. This update helps other contributors know that I won't be actively reviewing/approving PRs.
> Update website approvers

- content/en/docs/components/training/tftraining.md
Fix hyperlinks in documentation to point to correct source.
> Fix hyperlinks

- content/en/docs/pipelines/OWNERS
/assign @rmgogogo @joeliedtke 
Propose adding engs to approvers of pipelines folder, so that we can fix minor issues much faster.
> OWNERS for pipelines folder

- content/en/docs/pipelines/sdk/pipelines-metrics.md
Upstream PR: kubeflow/pipelines#3741
Once it gets merged, we can merge this.
UPDATE: upstream PR merged.
> Change pipelines metric name regex limitation for kubeflow/pipelines#3741

- content/en/docs/started/workstation/getting-started-multipass.md
Providing a more comprehensive documentation to deploying Kubeflow on Microk8s and accessing the dashboard.
> Update do Microk8s.enable Kubeflow docs

- netlify.toml
Adds configuration to specify the version of Hugo that is used to deploy branches.
> Adds configuration for Netlify deployments to branches

- netlify.toml
> Updates netlify config for branch deployments. (#2004)

- OWNERS
> prune the current ownership file

- content/en/docs/components/training/tftraining.md
> Adds note and example annotation for tfjob

- content/en/docs/aws/OWNERS
- content/en/docs/images/aws/OWNERS
Fine grain control on AWS contents.
> Add OWNERS file in AWS content folder

- content/en/docs/ibm/install-kubeflow.md
Supports #2000 by using GitHub OAuth app as 3rd party auth provider.
> Documents multi-tenant, auth-enabled deployment on IBM cloud

- content/en/docs/aws/deploy/install-kubeflow.md
- content/en/docs/aws/notebook-server.md
**Which issue is resolved by this Pull Request:**
Resolves #2014 #2026 
Write docs for describing Kubeflow 1.1 changes on AWS side.
1. Dex basic authentication solution
2. ECR Kubeflow Notebook Image.
3. Multi-user KFP workaround by using public endpoint.
> [AWS] Description of KF 1.1 changes on AWS

- content/en/docs/pipelines/installation/overview.md
Fixes https://github.com/kubeflow/pipelines/issues/4264
Changes:
* more information in installation option comparison
* provided a Q/A based workflow for choosing installation option
* Update some outdated information and urls
Preview: https://deploy-preview-2050--competent-brattain-de2d6d.netlify.app/docs/pipelines/installation/overview/
> doc: KFP installation options doc update for 1.0

- content/en/docs/components/serving/OWNERS
- content/en/docs/components/serving/overview.md
* Adds initial OWNERS file for serving
* Remove alter for overview.md
> OWNERS update for Serving Docs

- content/en/docs/aws/authentication-oidc.md
- content/en/docs/aws/authentication.md
- content/en/docs/aws/custom-domain.md
- content/en/docs/aws/customizing-aws.md
- content/en/docs/aws/deploy/uninstall-kubeflow.md
- content/en/docs/aws/features.md
- content/en/docs/aws/iam-for-sa.md
- content/en/docs/aws/logging.md
- content/en/docs/aws/notebook-server.md
- content/en/docs/aws/pipeline.md
- content/en/docs/aws/private-access.md
- content/en/docs/aws/storage.md
- content/en/docs/aws/troubleshooting-aws.md
For 1.1 release
related to #2066  #2080
> Remove outdate banner for AWS docs

- content/en/docs/pipelines/installation/overview.md
/assign @rmgogogo 
before we figure out a more detailed instructions that can make sure there's no user data loss
> Hide upgrade instructions for AI Platform Pipelines managed storage instructions

- content/en/docs/ibm/pipelines.md
Fixes #2069 
The requirement on public endpoint and HTTPS settings depend on #2071
> [IBM Cloud] Multi-user Piplines on IBM Cloud

- content/en/docs/gke/pipelines/authentication-sdk.md
- content/en/docs/pipelines/installation/standalone-deployment.md
- content/en/docs/pipelines/multi-user.md
preview: https://deploy-preview-2086--competent-brattain-de2d6d.netlify.app/docs/gke/pipelines/authentication-sdk/
Part of https://github.com/kubeflow/pipelines/issues/4317
> doc: connect KFP SDK to GCP endpoints

- content/en/docs/pipelines/installation/overview.md
> Revert "Hide upgrade instructions for AI Platform Pipelines managed storage instructions"

- content/en/docs/components/pipelines/pipelines.md
- content/en/docs/pipelines/sdk/pipelines-metrics.md
/assign @rmgogogo @jingzhang36
> Remove outdated warning for reviewed KFP docs

- content/en/docs/components/multi-tenancy/getting-started.md
- content/en/docs/gke/pipelines/authentication-pipelines.md
- content/en/docs/pipelines/multi-user.md
Fixes https://github.com/kubeflow/pipelines/issues/4322
Part of https://github.com/kubeflow/pipelines/issues/4317
> doc: authenticate to GCP for KFP multi-user

- scripts/add_outdated_banner.py
Adds script that will mark outdated docs as requiring updating.
> Add script for mark outdated docs as requiring updating

- content/en/docs/gke/deploy/project-setup.md
Fixes https://github.com/kubeflow/gcp-blueprints/issues/110
/assign @jlewi
> doc(gcp): anthos service mesh setup

- content/en/docs/gke/deploy/deploy-ui.md
- content/en/docs/gke/deploy/oauth-setup.md
> doc(gcp): fix deploy-cli url and hide deploy-ui link from next steps

- content/en/docs/gke/authentication.md
Fixes https://github.com/kubeflow/website/issues/2091
/assign @jlewi @joeliedtke
> doc: update "Authenticating Kubeflow to GCP"

- content/en/docs/gke/pipelines/authentication-pipelines.md
- content/en/docs/gke/pipelines/upgrade.md
- content/en/docs/pipelines/installation/overview.md
/assign @jlewi @joeliedtke 
Part of https://github.com/kubeflow/pipelines/issues/4324
> doc: update KFP installation options regarding KF 1.1

- content/en/docs/about/community.md
- content/en/docs/about/contributing.md
- content/en/docs/about/docs.md
- content/en/docs/about/events.md
- content/en/docs/about/gsoc.md
- content/en/docs/about/kubeflow.md
- content/en/docs/about/style-guide.md
- content/en/docs/about/use-cases.md
Fixes: https://github.com/kubeflow/website/issues/2108.
I removed outdated banners and I fixed some broken links/types.
I think we should also modify [Community meeting](https://www.kubeflow.org/docs/about/community/#community-meetings) contact person.
@karlschriek Are you responsible for calendar changes?
/assign @Bobgy @joeliedtke @jbottum @8bitmp3
/cc @jlewi
> Modify about pages for Kubeflow 1.1

- content/en/docs/pipelines/installation/localcluster-deployment.md
we should show standalone deployment first
/assign @jingzhang36 @rmgogogo
> Change localcluster-deployment.md order

- content/en/docs/components/multi-tenancy/getting-started.md
- content/en/docs/gke/customizing-gke.md
- content/en/docs/gke/deploy/deploy-cli.md
This should answer future questions like https://kubeflow.slack.com/archives/C7REE0EHK/p1597386829039400?thread_ts=1597294388.025200&cid=C7REE0EHK.
Also, updated next steps for deploy-cli doc.
/assign @jlewi @joeliedtke
> doc: improve doc for add user to GKE Kubeflow

- content/en/docs/openshift/OWNERS
- content/en/docs/openshift/_index.md
- content/en/docs/openshift/install-kubeflow.md
This PR is to add an OWNERS file to Openshift installation pages and to update instructions to KF 1.0.
> Adding update to KF 1.0 installation instructions on OCP

- content/en/docs/components/fairing/configure-fairing.md
- content/en/docs/components/fairing/fairing-overview.md
- content/en/docs/components/fairing/gcp/configure-gcp.md
- content/en/docs/components/fairing/gcp/tutorials/gcp-local-notebook.md
- content/en/docs/components/fairing/install-fairing.md
- content/en/docs/components/fairing/tutorials/other-tutorials.md
> Fix bad link in Fairing Docs

- content/en/docs/gke/deploy/project-setup.md
/assign @joeliedtke @jlewi @8bitmp3
> Update Google Cloud project-setup.md

- content/en/docs/started/OWNERS
As discussed in #2127, I'm adding myself as an approver for Getting-started docs. 
Happy to add others to the list.
> Add OWNERs file to > started section

- content/en/docs/openshift/install-kubeflow.md
- content/en/docs/openshift/uninstall-kubeflow.md
Per comments in #2107 this PR is to delete the banner. 
/assign @crobby @vpavlin
> Removing the outdated banner for Openshift Documentation

- content/en/docs/aws/pipeline.md
> typo fix in pipeline.md

- content/en/docs/gke/deploy/deploy-cli.md
- content/en/docs/gke/deploy/management-setup.md
/assign @jlewi @joeliedtke @8bitmp3
> doc(gcp): pin v1.1.0 tag and clearly document some gcp blueprint frictions

- content/en/docs/gke/deploy/management-setup.md
> doc(gcp): fix broken format in management cluster setup

- content/en/docs/pipelines/multi-user.md
> doc(kfp): update multi-user isolation doc title and supported platforms

- OWNERS
Creating this PR as a follow-up on #2104.
> Add RFMVasconcelos to reviewers - see #2104

- content/en/docs/pipelines/installation/localcluster-deployment.md
/assign @alfsuse 
Follow up of https://github.com/kubeflow/website/pull/2056
>  localcluster-deployment.md - KFP platform-agnostic-pns env hasn't been released

- content/en/docs/pipelines/OWNERS
Hi all, I could help as a reviewer to the pipeline section so feel free to add me as a reviewer to the owner file.
> Add @alfsuse to the OWNERS file

- content/en/docs/started/k8s/OWNERS
Issue: https://github.com/kubeflow/website/issues/2172#issuecomment-692780497
/assign @RFMVasconcelos @Bobgy
> Add a new OWNERS file for KF Kubernetes Getting Started

- content/en/docs/gke/deploy/deploy-cli.md
Just wanted to add quick instructions for how to install Kustomize 3.2.1 on a Linux box.
> Adding in instructions for how to install Kustomize 3.2.1 on a Linux box

- content/en/docs/reference/version-policy.md
/assign @8bitmp3 @rmgogogo @jlewi 
EDIT: preview: https://deploy-preview-2204--competent-brattain-de2d6d.netlify.app/docs/reference/version-policy/
> Update KFP latest version and stability level

- content/en/docs/aws/OWNERS
Add PatrickXYS@ as AWS Content Approvers
> Add Myself into AWS OWNERS

- content/en/docs/aws/pipeline.md
Spelling: `communitation` to `communication`
> Update pipeline.md spelling

- content/en/docs/ibm/deploy/authentication.md
- content/en/docs/ibm/pipelines.md
- content/en/docs/ibm/using-icr.md
- Fix typos related to the IBM documentation.
> Fix typos IBM documentation

- content/en/docs/gke/anthos.md
- content/en/docs/gke/cloud-filestore.md
- content/en/docs/gke/deploy/management-setup.md
- content/en/docs/gke/pipelines/authentication-sdk.md
- content/en/docs/gke/private-clusters.md
- content/en/docs/gke/troubleshooting-gke.md
- Fix typos related to the GKE documentation.
> Fix typos GKE documentation

- content/en/docs/azure/azureEndtoEnd.md
- Fix typos related to the Azure documentation.
> Fix typos Azure documentation

- content/en/docs/started/OWNERS
Adding myself as a reviewer to help out here.
> Update OWNERS on getting started

- content/en/docs/started/workstation/minikube-linux.md
I've updated the minikube-linux section to support the 1.1.0 version of KF.
> Update minikube-linux.md 

- content/en/docs/azure/OWNERS
This PR creates an OWNERS file with approvers and reviewers for Kubeflow Azure docs.
It should help with the Issue and PR review process.
cc @aronchick (approver), @sudivate (reviewer) - let me know what you think. Should we add anyone else?
/assign @aronchick
> Create an OWNERS file with approvers and reviewers for Kubeflow Azure docs

- content/en/docs/components/multi-tenancy/overview.md
> doc: multi-user isolation overview page - pipelines supported

- content/en/docs/components/multi-tenancy/OWNERS
> Create OWNERS for multi tenancy doc

- content/en/docs/pipelines/sdk/python-based-visualizations.md
/assign @joeliedtke 
upstream issue https://github.com/kubeflow/pipelines/issues/4643
> doc(kfp)!: deprecate python based visualization

- content/en/docs/pipelines/tutorials/api-pipelines.md
- content/en/docs/pipelines/tutorials/build-pipeline.md
- content/en/docs/pipelines/tutorials/cloud-tutorials.md
- content/en/docs/pipelines/tutorials/sdk-examples.md
Part of https://github.com/kubeflow/pipelines/issues/4324
/assign @8bitmp3
> doc(kfp): remove outdated banner for pages up-to-date

- content/en/docs/gke/deploy/project-setup.md
> improve gke project-setup doc

- content/en/docs/aws/pipeline.md
Added reference to authenticate Python SDK with static Dex users
> Add reference to authenticate Python SDK with Dex

- content/en/docs/gke/custom-domain.md
Changing the section *Using Your Own Domain* to be compliant with Kubeflow 1.1 version using kpt.
> Update GCP doc - setting a custom domain

- content/en/docs/gke/deploy/project-setup.md
- content/en/docs/notebooks/setup.md
- content/en/docs/reference/version-policy.md
- content/en/docs/started/kubeflow-overview.md
Fixing broken links in the website pointing to wrong path.
> Fixing Fairing broken links

- content/en/docs/components/hyperparameter-tuning/env-variables.md
- content/en/docs/components/hyperparameter-tuning/experiment.md
- content/en/docs/components/hyperparameter-tuning/hyperparameter.md
- content/en/docs/components/hyperparameter-tuning/katib-config.md
- content/en/docs/components/hyperparameter-tuning/overview.md
- content/en/docs/components/hyperparameter-tuning/trial-template.md
Fixes https://github.com/kubeflow/katib/issues/1341, https://github.com/kubeflow/katib/issues/1280.
Blocked by: https://github.com/kubeflow/website/pull/2312.
I have added doc about new Katib Trial Template.
Please take a look.
/assign @gaocegege @johnugeorge @8bitmp3 @RFMVasconcelos
> New trial template design for Katib

- content/en/docs/azure/azureMySQL.md
Adding documents for Azure Database for MySQL. The content is coming from [this PR](https://github.com/kubeflow/manifests/pull/1587/files)
> Adding docs for Azure MySQL

- content/en/docs/gke/pipelines/upgrade.md
Kpt renamed blueprints to package in https://github.com/GoogleContainerTools/kpt/pull/1109
> Update blueprint to package

- content/en/docs/components/serving/kfserving.md
> update kfserving website for 0.4.1 release

- content/en/docs/other-guides/kubeflow-behind-proxy.md
Following on-prem WG discussion and issue #2137
> Add kubeflow-behind-proxy.md - see issue #2137

- content/en/docs/azure/azureMySQL.md
Cherrypick of "Adding docs for Azure MySQL (#2304)"
* Adding docs for Azure MySQL
* Edit kustomization.yaml to use relative path in the example
* Linting the code
> Cherrypick of "Adding docs for Azure MySQL (#2304)"

- content/en/docs/azure/machinelearningcomponent.md
Adding an index page for Azure Machine Learning Component to provide capability to use Azure Machine Learning Service to register and deploy.
> Adding index page for Azure Machine Learning Component

- content/en/docs/gke/deploy/delete-cli.md
- content/en/docs/gke/deploy/management-setup.md
- content/en/docs/gke/deploy/monitor-iap-setup.md
- content/en/docs/gke/deploy/upgrade.md
/assign @joeliedtke @chensun @subodh101 
for review
> docs(gcp): management cluster install/upgrade instruction for KF 1.2

- content/en/docs/pipelines/sdk/pipelines-metrics.md
/assign @Ark-kun @8bitmp3 
website now shows 1.1-branch by default, so let's cherry pick
> cherrypick of "KFP - Updated the documentation regarding metrics #2171"

- content/en/docs/aws/pipeline.md
Resolve #2388 
/cc @8bitmp3 @karlschriek
> [AWS] Fix Cognito Pipeline-Notebook Authentication

- content/en/docs/notebooks/troubleshoot.md
- Add a section explaining how to delete notebooks manually in the `docs/notebooks/troubleshoot.md` documentation.
- Closes https://github.com/kubeflow/website/issues/2269.
> Add delete notebooks section to troubleshoot

- content/en/docs/pipelines/sdk/component-development.md
- Fix missing import in sample pipeline code ea91ba5
- Remove some stray whitespaces in the doc 6bcb3ac
> Component development doc fixes

- content/en/docs/pipelines/installation/standalone-deployment.md
> docs(kfp): fix namespaced deploy instructions for KFP standalone

- content/en/docs/gke/deploy/delete-cli.md
- content/en/docs/gke/deploy/deploy-cli.md
- content/en/docs/gke/deploy/reasons.md
- content/en/docs/gke/private-clusters.md
Fixes https://github.com/kubeflow/gcp-blueprints/issues/175
/assign @joeliedtke
> docs(gcp): unify terminology for CNRM as Config Connector

- content/en/docs/azure/authentication-oidc.md
- content/en/docs/azure/deploy/install-kubeflow.md
- layouts/shortcodes/azure/config-uri-azure-oidc.html
- layouts/shortcodes/azure/config-uri-azure.html
Updates the deploy instructions for KF 1.2 on Azure
Also addresses some config file confusion, #2398
> Update Azure Deployment Docs for KF 1.2

- content/en/docs/started/cloud/OWNERS
Help solve `Getting Started` section OWNER responsibilities
https://github.com/kubeflow/website/issues/2177
/cc @RFMVasconcelos @8bitmp3
> Add OWNERS for Getting Started Section

- content/en/docs/aws/deploy/install-kubeflow.md
> Small typo in AWS Deploy doc

- config.toml
> Fix outdated blog url in top-level navigation

- content/en/docs/gke/deploy/upgrade.md
* Two additional env variables are required for kf cluster setup
* clearer env var reference for management cluster update
Side note: is there a way to test the update was successful? aside from no errors in console?
> Improve update instruction steps

- content/en/docs/components/training/tftraining.md
While reading the documentation, it took me some time to understand the first two points. Modified it a bit to be more legible.
> Add some missing punctuation marks

- content/en/docs/ibm/deploy/authentication.md
This documents what adjustments are needed to get KFServing working on IBM Cloud Kubernetes Service with HTTPS.
> [IBM] Update HTTPS docs with KFServing config steps

- content/en/docs/components/training/OWNERS
Fixes #2444.
/cc  @Bobgy 
Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>
> Add OWNERS file for training component documentation

- content/en/docs/pipelines/reference/component-spec.md
* help should be description
* Add missing `optional` input argument
> Fix Component spec example

- content/en/docs/components/serving/kfserving.md
Easy navigation and easy reading for others
> Fix broken urls in KFServing docs

- content/en/docs/started/workstation/kubeflow-on-microk8s.md
Updates to Kubeflow on MicroK8s docs.
cc @jtfogarty (added user group, as you noted)
@8bitmp3, these are small changes. It would be great if you can take a look ;)
> Update KF on MicroK8s docs

- content/en/docs/pipelines/_index.md
> Add "Kubeflow" to "Pipelines" title

- content/en/docs/components/multi-tenancy/_index.md
> Remove "in Kubeflow" from "Multi-Tenancy"

- content/en/docs/components/_index.md
> Remove "of Kubeflow" from "Components"

- content/en/docs/about/community.md
Adding this as per request from SIG on-prem
> Slack channels alphabetization + add on-prem SIG

- content/en/docs/pipelines/reference/sdk.md
> doc(kfp): remove outdated banner for generated reference

- content/en/docs/pipelines/caching.md
Updating caching doc with new mutatingwebhookconfiguration naming pattern.
https://github.com/kubeflow/pipelines/issues/4984
> fix(doc): Update caching doc

- content/en/docs/gke/deploy/deploy-cli.md
- content/en/docs/gke/deploy/management-setup.md
Wording tweaks to streamline and clarify the yq v3 instructions.
> Updates the wording of the yq v3 instructions

- content/en/docs/about/community.md
Join Slack link has to be refreshed after 30 days
> Updated Join Slack link with a fresh link

- content/en/docs/ibm/create-cluster-vpc.md
- content/en/docs/ibm/create-cluster.md
- content/en/docs/ibm/deploy/install-kubeflow-on-iks.md
vpc-gen2 cluster has special setup for accessing cluster networks, this guide tries to cover those aspects. 
cc @Tomcli and @moficodes
> doc: Add instructions to access cluster with IBM Cloud vpc-gen2.

- content/en/_redirects
Deletes old redirects - pages do not exist anymore
> Deletes old redirects - pages do not exist anymore

- content/en/docs/distributions/ibm/deploy/install-kubeflow-on-IBM-openshift.md
* Target commit `552a4ba84567ed8c0f9abca12f15b8eed000426c` for working tekton installtion
* Update argo installation url.
> [IBM] Update openshift kubeflow installation

- content/en/docs/distributions/gke/OWNERS
> Update GCP distribution OWNERS

- layouts/shortcodes/pipelines/OWNERS
> Update KFP shortcodes OWNERS

- content/en/_redirects
> Add redirect for MicroK8s move - missed on #2577

- content/en/docs/gke/deploy/deploy-cli.md
- content/en/docs/gke/deploy/management-setup.md
- content/en/docs/gke/deploy/upgrade.md
> Kubeflow on GCP v1.2.1 doc update

- content/en/docs/components/training/mpi.md
- content/en/docs/components/training/mxnet.md
/cc @kubeflow/wg-training-leads @RFMVasconcelos @kimwnasptd @thesuperzapper @andreyvelich
Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>
> docs: Update MPI and MXNet operator pages

- content/en/docs/distributions/gke/deploy/deploy-cli.md
There are issues installing Kubeflow with version v4. 
Note: 
https://github.com/kubeflow/website/issues/2570
https://github.com/kubeflow/kubeflow/issues/5755
> Pin the version of kustomize, v4 is not supported.

- assets/scss/_variables_project.scss
- layouts/partials/footer.html
fix issue https://github.com/kubeflow/website/issues/2592
> fix footer

- content/en/docs/components/kfserving/kfserving.md
- content/en/docs/components/serving/overview.md
> Update KFServing docs for Kubeflow 1.3

- content/en/docs/distributions/openshift/OWNERS
- content/en/docs/distributions/openshift/_index.md
- content/en/docs/distributions/openshift/install-kubeflow.md
- content/en/docs/distributions/openshift/uninstall-kubeflow.md
This is an update to the documentation for KF 1.3 on OCP
> Updating documentation for KF 1.3 on Openshift

- content/en/_redirects
> add minikf subdir to minikf redirects

- content/en/docs/started/installing-kubeflow.md
Fixes #2651
This improves readability for users scanning the install page.
cc @thesuperzapper @castrojo @shannonbradshaw @Bobgy
> Headers for increased clarity of install options

- content/en/docs/components/multi-tenancy/OWNERS
- content/en/docs/components/pipelines/OWNERS
- content/en/docs/components/pipelines/sdk/OWNERS.md
- content/en/docs/distributions/azure/OWNERS
- content/en/docs/distributions/gke/OWNERS
- content/en/docs/distributions/ibm/OWNERS
- content/en/docs/distributions/ibm/deploy/OWNERS
- content/en/docs/distributions/microk8s/OWNERS
- content/en/docs/other-guides/OWNERS
@RFMVasconcelos @Bobgy Updating the OWNERS. I'll continue to provide input and help with edits. Thank you 👍
> Kubeflow OWNERS update

- content/en/docs/components/multi-tenancy/design.md
This appears to be not version specific.
> Remove "Out of date"

- content/en/docs/started/installing-kubeflow.md
@RFMVasconcelos @Bobgy as agreed in our meeting.
> add column for version to distro table

- content/en/docs/distributions/ibm/OWNERS
- content/en/docs/distributions/ibm/deploy/OWNERS
Have been focusing on IBM Cloud kubeflow docs
PR- 
#2660 
#2560 
#2476 
#1752
Review- 
#2680 
#2530 
#2518 
#2327
> add moficodes to ibm docs owners file

- content/en/docs/started/installing-kubeflow.md
@knkski @DomFleischmann As soon as we have tested MicroK8s Kubeflow Add-on v1.3, please lgtm this
> Update MicroK8s KF version to v1.3

- content/en/docs/reference/version-policy.md
fix issue https://github.com/kubeflow/website/issues/2687
Removed broken links
after fix
**Review page**
https://deploy-preview-2693--competent-brattain-de2d6d.netlify.app/docs/reference/version-policy/
> update version-policy.md links

- content/en/docs/distributions/charmed/install-kubeflow.md
Replaces #2676, which is failing tests.
> Fix un-rendered note

- content/en/docs/distributions/microk8s/kubeflow-on-microk8s.md
> Replaces `xip.io` with `nip.io`

- content/en/docs/components/pipelines/sdk/parameters.md
fix issue https://github.com/kubeflow/website/issues/2710
> fix parameters.md link

- content/en/docs/other-guides/kubeflow-on-multinode-cluster.md
fix issue https://github.com/kubeflow/website/issues/2712
/assign @RFMVasconcelos
> fix kubeflow-on-multinode-cluster.md link

- content/en/_index.html
> chore: fix getting started button link to not require redirect

- content/en/docs/distributions/microk8s/kubeflow-on-microk8s.md
We've had many users reach out via Slack about troubleshooting. Hopefully, this improvement in docs will get users more successful and autonomous in troubleshooting.
@evilnick could you please review?
cc @DomFleischmann
> Adding Troubleshooting details to MicroK8s add-on

- content/en/docs/distributions/gke/deploy/delete-cli.md
Fix make argument for deleting GCP resource
Fix kubectl command to switch context.
> Fix some commands in the delete-cli.md

- content/en/docs/reference/tfjob/v1beta2/common.md
fix issue https://github.com/kubeflow/website/issues/2731
/assign @RFMVasconcelos
> TFJob Common fix links

- content/en/docs/reference/tfjob/v1/common.md
fix issue https://github.com/kubeflow/website/issues/2734
> TFJob v1 Common fix links

- content/en/docs/distributions/charmed/install-kubeflow.md
@DomFleischmann I believe this small explanation is beneficial. wdyt?
> Small fix: clarity to Charmed Operators install

- content/en/docs/other-guides/kubeflow-on-multinode-cluster.md
> Fix broken link, linking to main install page

- content/en/docs/reference/notebook/v1/_index.md
fix issue https://github.com/kubeflow/website/issues/2746
some links have been replaced with text
example
> notebook v1 fix links

- content/en/docs/reference/version-policy.md
fix issue https://github.com/kubeflow/website/issues/2756
> fix Notebook web app link

- content/en/docs/examples/blog-posts.md
fix issue https://github.com/kubeflow/website/issues/2775
> fix markdown links

- content/en/docs/distributions/gke/deploy/management-setup.md
Explain how to select GKE locations for management cluster selection.
> fix(gke) Add explanation of GKE locations: available zones/regions

- README.md
- netlify.toml
update issue https://github.com/kubeflow/website/issues/2793
> update hugo version

- content/en/docs/components/katib/hyperparameter.md
Fixes: https://github.com/kubeflow/katib/issues/1528.
I updated docs for Katib MySQL volume.
/cc @RFMVasconcelos @gaocegege @johnugeorge @dnplas
> Update Katib MySQL volume settings

- content/en/docs/components/katib/katib-config.md
- content/en/docs/components/katib/resume-experiment.md
Fixes: https://github.com/kubeflow/katib/issues/1553.
I updated settings for `FromVolume` resume policy.
/cc @gaocegege @RFMVasconcelos @johnugeorge
> Update Katib settings for FromVolume resume policy

- content/en/docs/distributions/ibm/deploy/install-kubeflow-on-iks.md
Fix commands to support kustomize v3.2 and remove duplicated step.
> [IBM docs] Fix commands to support kustomize v3.2

- content/en/docs/components/katib/hyperparameter.md
Fixes: https://github.com/kubeflow/katib/issues/1467.
I added information about various Katib installs.
Please take a look @RFMVasconcelos @gaocegege @johnugeorge.
/hold for the review
> Explain different Katib installs

- content/en/docs/other-guides/support.md
fix issue https://github.com/kubeflow/website/issues/2810
> update blog link

- content/en/docs/other-guides/OWNERS
- content/en/docs/other-guides/_index.md
update for issue https://github.com/kubeflow/website/issues/2760#issuecomment-881430679
> clean section

- content/en/docs/distributions/charmed/install-kubeflow.md
> Add istio role to Charmed Kubeflow instructions

- content/en/_index.html
fix 1-s step
https://github.com/kubeflow/website/issues/2845
> update index blue section

- content/en/docs/distributions/gke/anthos.md
- content/en/docs/distributions/gke/custom-domain.md
- content/en/docs/distributions/gke/deploy/deploy-cli.md
- content/en/docs/distributions/gke/deploy/management-setup.md
- content/en/docs/distributions/gke/deploy/oauth-setup.md
- content/en/docs/distributions/gke/deploy/overview.md
- content/en/docs/distributions/gke/deploy/project-setup.md
- content/en/docs/distributions/gke/deploy/upgrade.md
Merge after https://github.com/kubeflow/gcp-blueprints/pull/296 is submitted.
> GoogleCloud: Update for Kubeflow 1.3.1 on Google Cloud

- content/en/docs/components/pipelines/sdk/v2/v2-compatibility.md
Reference: https://github.com/kubeflow/pipelines/issues/6241
> (pipelines) Update KFP version requirement for v2-compatible

- content/en/docs/external-add-ons/serving/mlrun.md
We've updated the code so we're updating documentation here as well.
> Fixing bug in mlrun serving

- content/en/docs/components/katib/experiment.md
- content/en/docs/components/katib/katib-config.md
This PR: https://github.com/kubeflow/katib/pull/1613 introduces Optuna Support in Katib.
We should update the docs.
/cc @RFMVasconcelos @c-bata @g-votte @gaocegege @johnugeorge
> Add Support for Optuna in Katib

- content/en/docs/components/pipelines/sdk/component-development.md
The current tutorial contains legacy data passing -- specifically passing a constant value to an input expect `inputPath`. This is not compatible with KFP v2 and Vertex Pipelines.
Update the sample to use compatible data passing that works on both KFP v1 and Vertex Pipelines.
Fixes: https://github.com/kubeflow/pipelines/issues/6112
> Update component-development.md to showcase v2 compatible data passing.

- content/en/docs/distributions/nutanix/OWNERS
- content/en/docs/distributions/nutanix/_index.md
- content/en/docs/distributions/nutanix/install-kubeflow.md
- content/en/docs/distributions/nutanix/nutanix-storage.md
- content/en/docs/distributions/nutanix/uninstall-kubeflow.md
- content/en/docs/started/installing-kubeflow.md
This adds the docs for deploying Kubeflow on Nutanix Karbon.
> Adding Docs for Kubeflow on Nutanix Karbon

- content/en/docs/components/katib/experiment.md
I added Algorithm Settings for TPE and Multivariate TPE in Katib.
/assign @c-bata @g-votte @gaocegege @johnugeorge 
/cc @RFMVasconcelos
> Add Katib Algorithm Settings for TPE and Multivariate TPE

- content/en/docs/components/multi-tenancy/design.md
- content/en/docs/components/pipelines/sdk/build-pipeline.md
- content/en/docs/distributions/aws/customizing-aws/rds.md
Easy navigation and easy reading for others
> fix broken links in docs

- content/en/docs/distributions/ibm/deploy/install-kubeflow-on-iks.md
Update IKS deployment instructions to 1.3.1
> Update installation instructions for IKS

- README.md
- netlify.toml
https://github.com/kubeflow/website/issues/2881
Checked everything locally
> hugo update

- content/en/docs/distributions/openshift/install-kubeflow.md
https://www.kubeflow.org/docs/distributions/openshift/install-kubeflow/#installing-kubeflow
**before**
**after update**
https://deploy-preview-2891--competent-brattain-de2d6d.netlify.app/docs/distributions/openshift/install-kubeflow/#installing-kubeflow
> link display fix

- content/en/docs/components/pipelines/installation/upgrade.md
Slightly update wording according to https://github.com/kubeflow/website/pull/2895#discussion_r697519583
> docs(kfp): update wording for feedback

- content/en/docs/components/pipelines/installation/localcluster-deployment.md
fix issue https://github.com/kubeflow/website/issues/2901
> update Argo Executors link

- content/en/docs/components/training/pytorch.md
- content/en/docs/components/training/tftraining.md
TFJob And PyTorchJob pages are updated with latest training operator repo changes
Related: #2915 
/cc @Jeffwan
> Update training operators doc

- content/en/docs/components/training/mxnet.md
Fix issues in existing doc. Address part of https://github.com/kubeflow/website/issues/2915
/cc @johnugeorge @andreyvelich
> Update docs for MXNet Jobs

- content/en/docs/about/style-guide.md
fix issue https://github.com/kubeflow/website/issues/2913
> fix hash link

- content/en/docs/components/training/mpi.md
Fixes https://github.com/kubeflow/mpi-operator/issues/423. See https://github.com/kubeflow/website/issues/2915. 
cc @kubeflow/wg-training-leads
> Update MPI operator docs

- content/en/docs/distributions/microk8s/OWNERS
We need more than one active approver for MicroK8s, so I am proposing myself.
> Update OWNERS for MicroK8s

- content/en/docs/distributions/ibm/deploy/install-kubeflow-on-iks.md
highlight the pip packages by using hyperlinks
address the comment here: https://github.com/kubeflow/website/issues/2928#issuecomment-915624890
> nit: add hyperlinks for pip packages

- content/en/docs/distributions/nutanix/install-kubeflow.md
- Add information about setting up a LoadBalancer using MetalLB
- Add information about accessing the kubeflow dashboard with ingressgateway external IP
> Update nutanix distribution docs

- content/en/docs/distributions/ibm/create-cluster.md
> Typo fix for IBM docs

- content/en/docs/distributions/ibm/deploy/install-kubeflow-on-iks.md
update links/file paths for kfp v1.4
> Update IKS to kfp v1.4

- content/en/docs/components/pipelines/installation/overview.md
Partial #2937.
We should make sure to keep updating this in the future, or write it down for future Kubeflow releases.
> pipelines: KFP Version for Kubeflow 1.3 table update. Partial #2937

- content/en/docs/about/style-guide.md
fix issue https://github.com/kubeflow/website/issues/2933
> fix page source link

- content/en/docs/components/katib/overview.md
> Fix small typo in Katib overview.md

- content/en/docs/components/pipelines/overview/concepts/output-artifact.md
Link to "output viewers" is broken
> Update output-artifact.md w/ Working Link

- OWNERS
> Add more Googler root OWNERS

- README.md
- netlify.toml
https://github.com/kubeflow/website/issues/2959
> update hugo to last version

- content/en/docs/distributions/ibm/deploy/install-kubeflow-on-iks.md
Add more details for multi-user deployment
and correct some out-dated commands.
Also update the started page to 1.4 and add
a link to IBM manifest repo.
> Refine some details for IKS deployment

- OWNERS
Dear community,
In the last 2 years, I have had the great pleasure to be part of the community building this amazing open-source tool. I am quite satisfied in feeling that I left a small dent in the overall experience for new users.
Today I see my path take a different course, which I am excited to invest my full energy into. 🚀
I was also very lucky to work on Canonical's distribution - which I leave in the great hands of @knkski  @DomFleischmann and more. 
If you want to stay in touch, please connect via [LinkedIn](https://www.linkedin.com/in/rui-vasconcelos/).
I nominate @knkski to take on some of the responsibilities I held, in his own capacity, given his 3 years of dedication to Kubeflow.
With Gratitude,
Rui
> rm RFMVasconcelos

- config.toml
This needs to be cherry-pick to v1.3-branch
> Show v1.3 branch under dropdown

- config.toml
By default, we show master branch
> Update master branch text label as `latest`

- content/en/docs/distributions/nutanix/install-kubeflow.md
Change recommended `kubeflow_version` terraform variable default value to `1.4.0`
> Update Kubeflow version in Nutanix distribution docs

- content/en/docs/components/pipelines/installation/overview.md
- content/en/docs/distributions/gke/deploy/deploy-cli.md
- content/en/docs/distributions/gke/deploy/management-setup.md
- content/en/docs/distributions/gke/deploy/upgrade.md
- content/en/docs/started/installing-kubeflow.md
Partial https://github.com/kubeflow/gcp-blueprints/issues/310
> gke: Prepare Kubeflow 1.4 deployment guide.

- content/en/docs/started/installing-kubeflow.md
update the version to 1.4 and add an external url pointing
to manifests repo
> Update kfp version for IKS

- content/en/docs/components/katib/hyperparameter.md
Add docs to describe how to install HA `katib-controller`.
Ref: https://github.com/kubeflow/katib/pull/1713
/assign @andreyvelich @gaocegege @johnugeorge
> Add docs to describe how to install HA katib-controller

- content/en/docs/distributions/azure/authentication-oidc.md
- content/en/docs/distributions/azure/deploy/install-kubeflow.md
fix issue https://github.com/kubeflow/website/issues/2983
> fix kfctl version

- OWNERS
Hello,
Adding myself, shannonbradshaw, to the website approvers list. I've mainly been working on the docs.
I contributed quite a bit to the design, organization, and review of docs for the 1.3 release:
kubeflow/website#2645
kubeflow/website#2655
kubeflow/website#2650
kubeflow/website#2641
kubeflow/website#2638
kubeflow/website#2630
kubeflow/website#2691
kubeflow/website#2963
And am actively involved in the community and docs efforts for the 1.4 release:
kubeflow/kubeflow#6082
kubeflow/website#2986
I led the docs team at MongoDB for several years and am excited to be able to contribute to the Kubeflow docs effort!
-Shannon
> add shannonbradshaw to approvers

- content/en/docs/about/style-guide.md
https://github.com/kubeflow/website/issues/3060
/assign @Bobgy
> update bootstrap version links

- assets/icons/pipelines.svg
- content/en/_index.html
- content/en/pipelines.svg
To fix https://github.com/kubeflow/pipelines/issues/6970
> [pipelines] Update pipeline overview link in everywhere in website

- content/en/docs/distributions/aws/customizing-aws/rds.md
Closes https://github.com/awslabs/kubeflow-manifests/issues/77
> Fixed Deploy RDS Commands Not Working For All Output Formats Preferences

- content/en/docs/started/architecture.md
Fixes broken tutorial link.﻿
I believe this is the correct link, but reviewer please confirm.
> fix broken MNIST link

- content/en/docs/distributions/aws/OWNERS
> update OWNERS for v1.3-branch AWS distro docs

- content/en/docs/distributions/aws/OWNERS
need for future similar to https://github.com/kubeflow/website/issues/3166
> update OWNERS for v1.4-branch AWS distro docs

- content/en/docs/components/pipelines/sdk/connect-api.md
Small change: fixed broken link.
> Fixed changed Kubeflow Pipelines on AWS link

- content/en/docs/distributions/aws/deploy/eks-compatibility.md
- content/en/docs/started/installing-kubeflow.md
AWS distro version update for #3131
> Update AWS distribution version

- content/en/docs/started/installing-kubeflow.md
Not 1.5, yet, but it updating it to be in sync with the latest supported version
cc @shannonbradshaw
> minikf: Update to v1.4

- content/en/docs/releases/kubeflow-1.5.md
> 1.5 release page

- config.toml
> Add 1.5 to version dropdown.

- content/en/docs/components/pipelines/sdk/connect-api.md
Fixed relative link to new AWS Pipelines page
> Fixed broken AWS Pipelines link for 1.3 docs branch

- content/en/docs/components/pipelines/sdk/build-pipeline.md
Changes the web_downloader_op link to working one because of folder reorg in repo.
> Fixed web_downloader_op link

- content/en/docs/components/katib/experiment.md
- content/en/docs/components/katib/katib-config.md
Usage details for PBT around https://github.com/kubeflow/katib/pull/1833.
> Katib: Population based training algorithm section

- content/en/docs/components/pipelines/reference/api/kubeflow-pipeline-api-spec.html
Previous PR doesn't take effect https://github.com/kubeflow/website/pull/3287
/assign @chensun
> pipeline: Add title section to enable navigation in KFP API reference doc

- content/en/docs/distributions/ibm/deploy/iks-compatibility.md
- content/en/docs/distributions/ibm/deploy/install-kubeflow-on-iks.md
- content/en/docs/distributions/ibm/deploy/uninstall-kubeflow.md
update instructions for kubeflow v1.6 and
compatibility table.
> update IKS doc for v1.6

- content/en/docs/components/pipelines/introduction.md
> add kfp v2 introduction

- content/en/docs/started/installing-kubeflow.md
> adding Oracle to Distribution table

- content/en/docs/components/pipelines/compile-a-pipeline.md
- content/en/docs/components/pipelines/compile-a-pipeline/_index.md
> add kfp v2 compile a pipeline

- content/en/docs/components/pipelines/author-a-pipeline/tasks.md
> add kfp v2 authoring/tasks

- content/en/docs/components/pipelines/author-a-pipeline/inputs-outputs-data-passing.md
> add kfp v2 component i/o

- content/en/docs/components/katib/env-variables.md
Add documentation for katib's postgres db
Fixes the katib issue : https://github.com/kubeflow/katib/issues/1938
> [katib] support postgres db

- content/en/docs/components/pipelines/v2/installation.md
- content/en/docs/components/pipelines/v2/introduction.md
- content/en/docs/components/pipelines/v2/quickstart.md
Date: Sep 22, 2022
* Step 4 in Quick Start still needs some work.
* Before publishing, be sure to remove all HTML comments marked as
* Made some minor reorg changes.
* Preferred tone: second person, active voice, and imperative (especially for procedures).
> v2 documentation - review of Introduction and Quick Start topics

- content/en/docs/releases/kubeflow-1.6.md
Signed-off-by: Anna Jung (VMware) <antheaj@vmware.com>
- Add 1.6.1 release info
cc @kubeflow/release-team
> Add 1.6.1 info

- content/en/docs/components/pipelines/v1/sdk-v2/component-development.md
- content/en/docs/components/pipelines/v1/sdk/component-development.md
- content/en/docs/components/pipelines/v1/sdk/pipelines-metrics.md
> Fix broken links on pipelines output viewer. Fixes #3397

- content/en/docs/components/training/paddlepaddle.md
> [PaddlePaddle] add paddlejob doc

- content/en/docs/distributions/gke/deploy/deploy-cli.md
Fixing typos on GKE deployment page
> Fix typos on GKE deployment page

- content/en/docs/started/installing-kubeflow.md
* Add a table entry in Installing Kubeflow
> Add Kubeflow on VMware vSphere documentation

- content/en/docs/about/community.md
- content/en/docs/about/style-guide.md
- content/en/docs/components/central-dash/customizing-menu.md
- content/en/docs/components/katib/experiment.md
- content/en/docs/components/pipelines/v1/reference/component-spec.md
- content/en/docs/components/pipelines/v1/sdk-v2/v2-compatibility.md
- content/en/docs/components/training/tftraining.md
- content/en/docs/distributions/ibm/iks-e2e.md
- content/en/docs/external-add-ons/feature-store/getting-started.md
- content/en/docs/external-add-ons/feature-store/overview.md
- content/en/docs/started/installing-kubeflow.md
resolve https://github.com/kubeflow/website/issues/3405
> update content links

- content/en/docs/components/training/job-scheduling.md
Signed-off-by: Yuki Iwai <yuki.iwai.tz@gmail.com>
I added the guide on how to use Scheduler Plugins with coscheduling.
> [Training] Add the guide on how to use Scheduler Plugins with coscheduling

- content/en/docs/about/community.md
This would be beneficial to the community and shows off the great Kubeflow ecosystem.
> Add link to awesome-kubeflow repo

- content/en/docs/components/pipelines/v2/author-a-pipeline/tasks.md
Updates docs to align with https://github.com/kubeflow/pipelines/pull/8836
> replace .set_gpu_limit with .set_accelerator_limit in KFP SDK docs

- content/en/docs/distributions/ibm/deploy/iks-compatibility.md
- content/en/docs/distributions/ibm/deploy/install-kubeflow-on-iks.md
- content/en/docs/distributions/ibm/deploy/uninstall-kubeflow.md
- update the deployment instructions to use v1.7-branch
- update the OWNERS files to reflect the ownership changes
> Update distribution doc for IBM IKS

- content/en/docs/distributions/ibm/OWNERS
- content/en/docs/distributions/ibm/deploy/OWNERS
update the OWNERS files based on the changes in IBM and sync the content.
> update OWNERS for ibm dist

- content/en/docs/distributions/ibm/deploy/deployment-process.md
- content/en/docs/distributions/ibm/deploy/install-kubeflow-on-iks.md
- content/en/docs/distributions/ibm/deploy/uninstall-kubeflow.md
update IKS installation instructions to use kustomize v5
> use kustomize v5.0 for IBM IKS

- content/en/docs/components/pipelines/v1/installation/standalone-deployment.md
> Fix link to kustomize glossary

- content/en/docs/releases/kubeflow-1.7.md
Add release page for Kubeflow 1.7
> Add Kubeflow 1.7 Release Page

- content/en/docs/components/pipelines/v2/version-compatibility.md
Closes: https://github.com/kubeflow/pipelines/issues/8728
> kfp: Add version compatibility matrix doc

- content/en/docs/components/pipelines/v2/load-and-share-components.md
- content/en/docs/components/pipelines/v2/pipelines/pipeline-basics.md
Fixes https://github.com/kubeflow/pipelines/issues/8726
> kfp: improve the doc on pipeline as component use case

- content/en/docs/components/notebooks/quickstart-guide.md
> Fixed typo in quickstart-guide.md

- content/en/docs/components/pipelines/v2/components/lightweight-python-components.md
resolve https://github.com/kubeflow/website/issues/3487
> update content folder link

- content/en/docs/started/installing-kubeflow.md
Update vSphere Kubeflow distribution version and the website link
> Update vSphere distro version and website link

- content/en/docs/components/pipelines/v2/cli.md
Fixes https://github.com/kubeflow/website/issues/3576
> improve kfp sdk cli docs

- assets/scss/_styles_project.scss
- config.toml
- content/en/docs/about/events.md
- content/en/events/OWNERS
- content/en/events/_index.md
- content/en/events/kubeflow-summit-2023.md
This is the initial PR to add "Kubeflow Summit 2023" to the website.
NOTE: this is a first-pass so we can share the link, but we will make updates very soon.
> add kubeflow summit 2023

- content/en/events/kubeflow-summit-2023.md
This PR fixes some incorrect information in the Kubeflow Summit 2023 agenda.
> fix kubeflow summit agenda

- content/en/events/kubeflow-summit-2023.md
Created another Pull Request to update my name. The previous rebase got a bit chaotic :)
> Fixing small typo in my name for KF summit 2023

- content/en/events/kubeflow-summit-2023.md
This PR updates the Kubeflow Summit 2023 with the final agenda.
Based on: https://docs.google.com/spreadsheets/d/11gdgKxlCzQfMLiRO-gaEYIQG91VbdzJCnARHLhG9YTQ/edit#gid=0
> update kubeflow summit agenda & speakers

- content/en/docs/components/pipelines/v2/data-types/artifacts.md
Also includes some general artifact content refreshes, organizational improvements, and clarity improvements.
> sdk: add kfp sdk pythonic artifact authoring documentation

- content/en/docs/components/pipelines/v2/platform-specific-features.md
> fix typo for platform-specific-features.md

- content/en/events/gsoc-2024.md
Add project ideas for Kubeflow's application to Google Summer of Code 2024, aiming to participate as an organization and recruit student contributors
> GSOC 2024 proposal

- content/en/docs/components/katib/hyperparameter.md
- content/en/docs/components/katib/katib-config.md
Fixes: https://github.com/kubeflow/katib/issues/2186.
I updated guide with the new Katib Config APIs.
Please take a look.
/assign @tenzen-y @johnugeorge 
/cc @kubeflow/release-managers
> Katib: Update Katib Config Guide with the new APIs 

- content/en/_index.html
This is to resolve issue #3654 to make the main component cards clickable to take to their respective pages.
> Making the components cards clickable on main page

- content/en/events/gsoc-2024.md
We are going to add Yuan to the list of mentors for Training Operator and Katib proposals during GSoC.
/assign @rareddy @tenzen-y @johnugeorge @terrytangyuan
> Add Yuan (Terry) Tang to GSoC Mentors

- content/en/docs/components/katib/hyperparameter.md
Based on [this comment](https://github.com/kubeflow/katib/pull/2303#pullrequestreview-1994643872), I updated the minimal Kubernetes version.
/assign @andreyvelich @johnugeorge 
/hold
for review
> Katib: Update the minimal requirements

- content/en/docs/started/architecture.md
Resolves: #3721
Removing Fairing link as Fairing pages are removed from #3553.
> Remove Fairing section

- config.toml
cc @kubeflow/kubeflow-steering-committee @akgraner
> Update banner to link to upcoming colocated event at KubeCon

- content/en/docs/about/community.md
cc @kubeflow/kubeflow-steering-committee
> Update Slack channels to new CNCF Slack channels

- OWNERS
- content/en/docs/components/pipelines/OWNERS
Adding myself as a reviewer to pipelines OWNERS.
@chensun do you suggest any other updates for the pipelines OWNERS?
/assign @andreyvelich @chensun
> Update to pipelines OWNERS

- content/en/docs/components/pipelines/OWNERS
> Added @rimolive as approver for Pipelines

- content/en/docs/components/pipelines/concepts/pipeline-root.md
- content/en/docs/components/pipelines/legacy-v1/sdk/output-viewer.md
Resolves: https://github.com/kubeflow/website/issues/3756
> Fixed sdk-v2 links in pipelines

- content/en/docs/components/pipelines/user-guides/data-handling/artifacts.md
Resolves: https://github.com/kubeflow/website/issues/3766
> Fixed links in Pipelines > user guides > data handling > artifacts

- content/en/docs/components/pipelines/OWNERS
> Pipelines - @hbelmiro promoted to approver and removed old members

- content/en/docs/components/pipelines/user-guides/core-functions/platform-specific-features.md
The code in this tutorial doesn't work without the import.
> fix(pipelines): Add missing kfp-kubernetes import

- content/en/docs/components/pipelines/reference/kfp-kubernetes.md
This PR adds a new page for [kfp-kubernetes](https://kfp-kubernetes.readthedocs.io).
> Added page for kfp-kubernetes

- content/en/docs/components/pipelines/operator-guides/installation/_index.md
Add port-forward to ml-pipeline-ui service
> Add port-forward to ml-pipeline-ui service

- content/en/_redirects
- content/en/docs/components/pipelines/operator-guides/multi-user.md
Resolves: https://github.com/kubeflow/website/issues/3749
cc @chensun
> Moved multi-user to KFP v2 docs

- content/en/docs/about/community.md
@kubeflow/kubeflow-steering-committee
> Add KSC info to the community page

- content/en/docs/components/spark-operator/OWNERS
- Add @ChenYi015 to spark-operator approvers
- Add @jacobsalway to spark-operator reviewers
> Update spark operator owners

- content/en/docs/components/spark-operator/developer-guide.md
Update spark-operator developer guide
> Update spark-operator developer guide

- content/en/docs/components/spark-operator/user-guide/running-multiple-instances-of-the-operator.md
Update the user guide to run multiple Spark operator instances
> Update the user guide to run multiple Spark operator instances

- content/en/docs/components/katib/user-guides/trial-template.md
- content/en/docs/components/training/user-guides/mpi.md
- content/en/docs/components/training/user-guides/tensorflow.md
- netlify.toml
Fix broken links in Training Operator #3812
> Fix broken links in Training Operator #3812

- content/en/docs/components/notebooks/api-reference/notebook-v1.md
- content/en/docs/components/pipelines/reference/component-spec.md
- content/en/docs/components/spark-operator/user-guide/writing-sparkapplication.md
Resolves https://github.com/kubeflow/website/issues/3900
update old and broken links across kubeflow documentation
> Update Documentation reference to the same version of Kubernetes API 1.29

- content/en/docs/components/pipelines/user-guides/core-functions/caching.md
Ref: https://github.com/kubeflow/pipelines/pull/11222
This feature has been released as part of the latest [KFP SDK release.](https://github.com/kubeflow/pipelines/milestone/14?closed=1)
> [Pipelines] Add doc on disabling default caching flag and env var

- config.toml
> Add Kubeflow Summit banner

- content/en/docs/components/katib/user-guides/env-variables.md
> Katib: Update env-variables.md

- content/en/events/upcoming-events/gsoc-2025.md
Adding myself as a mentor for the KServe Web App project.
> Add Griffin-Sullivan as a mentor for GSOC 2025

- content/en/events/upcoming-events/gsoc-2025.md
@kubeflow/kubeflow-steering-committee @chasecadet
I have reverted controversial changes from https://github.com/kubeflow/website/pull/4000 that are not aligned with the KSC and or mentors.
> Gsoc 2025 formatting

- content/en/docs/started/installing-kubeflow/index.md
> Update manifests description

- content/en/docs/started/installing-kubeflow/index.md
fixes #3147 
@varodrig for /lgtm
> clarify installation options

- content/en/events/upcoming-events/gsoc-2025.md
/area gsoc
Adding GSoC project for Empowering Kubeflow Docs with LLMs.
/hold for review
/assign @rareddy @kubeflow/kubeflow-steering-committee @varodrig @rimolive @shravan-achar
> website: Update GSoC projects with LLM-powered docs

- .github/workflows/pr_title_check.yaml
**Checklist:**
Adding the check for PRs to follow rule for **component_name: description**
Components to check are central-dashboard, katib, kserve, model-registry, notebooks, pipelines, spark-operator,trainer,gsoc,website,community
Closes: #4002
---
> website: Issue4002 GitHub action to check pr title

- content/en/docs/components/trainer/legacy-v1/user-guides/mpi.md
**Checklist:**
Changed the description of the yaml file in MPIJob's Scheduling Policy.
Closes: #https://github.com/kubeflow/mpi-operator/issues/682
/area trainer
/area website 
---
> Fix Scheduling Policy doc for MPIJob

- content/en/docs/components/spark-operator/user-guide/customizing-spark-operator.md
**Checklist:**
Closes: #3889
/area spark-operator
---
> spark-operator: customize spark operator

- content/en/docs/components/model-registry/installation.md
**Checklist:**
I found installing model registry from the instructions on the website to be rather hard to do. The instructions don't actually have all the steps needed, so it sent me to the README in the manifests repo. Which, confusingly, sent me right back to the website. Neither document is entirely complete so I had to coble together bits from both places.
I'm assuming these instructions are primarily useful to existing Kubeflow users who want to try out model registry so I've rewritten the "Installing on Kubeflow Platform" section with the idea to get those users up and running quickly. I'm further assuming that these users will want the UI (I mean, it's a good UI, who wouldn't?) so we can cut the "if you want the UI verbage" and simplify some of the …
> model-registry: update the installation guide

- content/en/docs/components/pipelines/overview.md
Updated and improved the KFP overview page, crucially adding two keys points that differentiate KFP to the "Why Kubeflow Pipelines?" section:
* Easily pass parameters and ML artifacts between pipeline components
* Keep experimentation and iteration light and Python-centric, minimizing the need to (re)build and maintain containers
**Checklist:**
Closes: #
---
> pipelines: Improvements to the KFP overview doc

- content/en/docs/about/community.md
- content/en/docs/components/katib/user-guides/llm-hp-optimization.md
We updated our Slack channel to `#kubeflow-trainer`
/assign @kubeflow/kubeflow-steering-committee @kubeflow/wg-training-leads @terrytangyuan
> trainer: Update Slack channel

- README.md
- config.toml
- content/en/_index.html
- layouts/partials/footer.html
Fixes #3684
Fixes #3633
Fixes #3683
Hi, I have added
- X (twitter), Slack, YouTube and KubeFlow CNCF icon in project readme
- New twitter icon, YouTube and LinkedIn on footer
-------------------------------------
> website: added social media icon on readme and footer

- content/en/docs/components/pipelines/OWNERS
This PR updates the OWNERS for the Pipelines component with the following changes:
- Add @HumairAK and @mprahl as approvers, since they're approvers in the [pipelines repo](https://github.com/kubeflow/pipelines/blob/master/backend/OWNERS).
- Removes `@connor-mccarthy`, which is no longer an active contributor.
**Checklist:**
Closes: #
/area pipelines
---
> pipelines: Updated Pipelines' OWNERS file

- content/en/docs/components/pipelines/overview.md
Fix doc broken link
**Checklist:**
Closes: #
---
> fix: getting-started broken link

- content/en/docs/components/trainer/legacy-v1/user-guides/fine-tuning.md
**Checklist:**
part of #https://github.com/kubeflow/trainer/issues/2162#issuecomment-2847104665
Closes: #
---
> trainer: update fine-tune example to use `eval_strategy`

- content/en/docs/components/model-registry/getting-started.md
**Checklist:**
Preview the changes here: https://deploy-preview-4048--competent-brattain-de2d6d.netlify.app/docs/components/model-registry/getting-started/#using-model-registry-custom-storage-initializer
Closes: https://github.com/kubeflow/model-registry/issues/801
/area model-registry
---
> model-registry: add YAML manifest example for creating InferenceService

- content/en/docs/components/pipelines/user-guides/components/importer-component.md
**Checklist:**
/area pipelines
> pipelines: Add KFP documentation for importing modelcars

- content/en/docs/about/community.md
- content/en/docs/about/governance.md
**Checklist:**
- Adds a page on governance linking to appropriate areas.
Closes: #
N/A
> website: Adding Governance page

- content/en/docs/components/model-registry/OWNERS
- layouts/shortcodes/model-registry/OWNERS
for consistency with
https://github.com/kubeflow/model-registry/blob/42d3fb7d1619ab9e34d71eaaac72da347cc187c7/OWNERS#L2C1-L2C17
**Checklist:**
Closes: #
---
> model-registry: add Al-Pragliola in approvers

- content/en/docs/components/trainer/getting-started.md
- content/en/docs/started/architecture.md
**Checklist:**
Updates the getting started guide for Trainer to use `kubeflow/sdk`.
/area trainer
---
> trainer: Update SDK source repo

- content/en/_index.html
**Checklist:**
Defining what is Kubeflow
Closes: #
---
> website: Defining what is kubeflow

- content/en/docs/components/pipelines/user-guides/migration.md
**Checklist:**
Closes: https://github.com/kubeflow/pipelines/issues/11740
/area pipelines
---
> pipelines: fix link in `Migrate to Kubeflow Pipelines v2`

- content/en/docs/components/trainer/getting-started.md
- content/en/docs/components/trainer/user-guides/_index.md
- content/en/docs/components/trainer/user-guides/pytorch.md
**Checklist:**
User guide for PyTorch Training
Closes: kubeflow/trainer#2543
/area trainer
---
> trainer: User guide for PyTorch Training

- content/en/docs/about/community.md
Add graduation call google doc
Closes: #4103
Related: #4103
> website: Add graduation call doc link

- content/en/docs/components/model-registry/installation.md
Added TLS configuration for local development as a followup for https://github.com/kubeflow/model-registry/pull/1438
Closes: #<issue number>
Related: #<issue number>
> model-registry: add TLS configuration for local development

- content/en/events/upcoming-events/gsoc-2025.md
Hi in this PR I added the selected contributors for GSoC 2025, project page and KEP/Issue/PR as applicable.
Closes: #4162
> website: added gsoc 25 project details

- content/en/docs/components/trainer/user-guides/deepspeed.md
- content/en/docs/components/trainer/user-guides/mlx.md
Blocked by: https://github.com/kubeflow/trainer/pull/2790
I've added the MLX guide for Kubeflow Trainer.
I would appreciate your review of the content!
/hold
/assign @kubeflow/kubeflow-trainer-team @astefanutti @kannon92 @kramaranya @rudeigerc
/cc @awni @Blaizzy @ivanfioravanti @AlexCheema
> trainer: Add MLX user guide

- content/en/docs/components/trainer/operator-guides/installation.md
Update the minimum Kubernetes version for trainer.
Relates to https://github.com/kubeflow/trainer/pull/2804
> trainer: Update minimum Kubernetes version in prerequisites
